### ISSUE TITLE
Feature request: Forcing order of in text citations

### ISSUE THREAD

**Issue by EoinTravers** [jgm/pandoc-citeproc#101]
At present, multiple BibTex keys within a Markdown document are rendered alphabetically.
For instance,

`[@sloman_two_2002; @sloman_empirical_1996; @darlow_two_2010].`

is rendered as

>(Darlow & Sloman, 2010; Sloman, 1996, 2002).

However, there are cases when it's desirable to override this, for example, it would be preferable to be able to enter

`Sloman's [-@sloman_empirical_1996; -@sloman_two_2002; @darlow_two_2010] dual process theory`

and render it as 

>Sloman's (1996; 2002; Darlow & Sloman, 2010) dual process theory

At present, because `Darlow` comes before `Sloman` alphabetically, this renders instead as

>Sloman's (Darlow & Sloman, 2010; 1996; 2002) dual process theory

An obvious workaround is to enter the citation manually, taking advantage of the fact that numbers come before letters "alphabetically", and use `nocite` fields

    Sloman's [1996; 2002; @darlow_two_2010] dual process theory

    ---
    nocite: @sloman_empirical_1996, @sloman_two_2002
    ...

...but it might be possible to implement an override in pandoc directly?

**Comment by jgm** [comment]
@nickbart, do you know if this is determined by the CSL style and configurable there?

**Comment by EoinTravers** [comment]
There's an old, but possibly related discussion on the Zotero forum [here](https://forums.zotero.org/discussion/2976/sort-multi-citations-in-text/).

**Comment by EoinTravers** [comment]
Also, digging around this a little, I've found the [relevant part of the CSL specification](http://citationstyles.org/downloads/specification.html#sorting).

Specifically, most styles, including APA.csl,
have a section as follows, specifying to sort citations by author,
and then by date

```
<sort>
    <key macro="author" names-min="3" names-use-first="3"/>
    <key variable="issued" sort="descending"/>
</sort>
```

The key question, which is beyond my knowledge of Pandoc, Haskell, or CSL, is if there's a way to override this for a specific section of the text, as changing this globally would be clearly undesirable.

**Comment by jgm** [comment]
+++ Eoin Travers [Jan 13 15 09:01 ]:
>   The key question, which is beyond my knowledge of Pandoc, Haskell, or
>   CSL, is if there's a way to override this for a specific section of the
>   text, as changing this globally would be clearly undesirable.

No, not currently.  Since you're going for an author-in-text
citation, have you tried this format?

    @citemefirst [pp. 37; @citemenext, p. 40]

I *think* that would force @citemefirst to be first,
and outside the parens.

**Comment by EoinTravers** [comment]
Correct. Thanks. I hadn't realized that Pandoc was this intelligent with regards to square brackets, etc.

`@sloman_empirical_1996 [-@sloman_two_2002; @darlow_two_2010] theory`

>Sloman (1996, 2002; Darlow & Sloman, 2010) theory

This doesn't solve the problem I had wished to avoid by forcing citations to display in order though, but which probably lies outside of this feature request - handling of possessive apostrophes: 

`Sloman's [-@sloman_empirical_1996] [-@sloman_two_2002; @darlow_two_2010] theory`

>Sloman's (1996) (Darlow & Sloman, 2010; 2002) theory

For the time being, I'll stick to my original solution, using the `nocite` feature.

**Comment by nickbart1980** [comment]
So this seems to be mostly solved already. Just to confirm, as far as I know, there is no way of overriding the sort instructions given in `<citation ...><sort>...</sort>... ... ...</citation>` for a specific section of the text. Some popular styles like chicago-author-date.csl or chicago-fullnote-bibliography.csl do not use any sorting for in-text citations, in line with what the Chicago Manual says in “15.29 Multiple text references”:

> Two or more references in a single parenthetical citation are separated by semicolons. The order in which they are given may depend on what is being cited, and in what order, or it may reflect the relative importance of the items cited. If neither criterion applies, alphabetical or chronological order may be appropriate. Unless the order is prescribed by a particular journal style, the decision is the author’s.

So if you want this kind of flexibilty, I'd say, just get rid of the `<sort>...</sort>` element inside `<citation>`.

**Comment by EoinTravers** [comment]
Yup, losing the `\<sort>...\</sort>` tags seems to be the only way preserve the order.

As an exercise/distraction from writing, I put together a python script to manually sort citations, except for those containing a `<!--NOSORT-->` comment, mimicing to a certain level of precision the behaviour of `apa.csl`, but allowing an override.

<https://gist.github.com/EoinTravers/33dfcd76714405a4e9c1>

This might be of interest to anyone coming across this issue - unfortunately, I have 0 Haskall skills, so I can't offer to try to implement anything similar within Pandoc.

**Comment by dfaligertwood** [comment]
Probably worth implementing it as a pandoc filter, see jgm/pandocfilters for relevant stuff (and my own pandoc-filters repo for more examples)

**Comment by jgm** [comment]
Closing this, as it seems resolved.
