### ISSUE TITLE
problem when parsing multiple citations within one set of square brackets

### ISSUE THREAD

**Issue by scaramouche1** [jgm/pandoc-citeproc#102]
Parsing `[see, e.g., @Smith12]` produces `(see, e.g., Smith 2012)`.

In contrast, parsing `[see, e.g., @Smith12, @Smith13]` produces `(see, e.g., Smith 2012, Smith (2013))`.  Note the extra, nested parentheses for Smith (2013).

This happens when exporting to PDF, docx, and HTML.

Is this a bug?  If it is not a bug, is there a simple workaround?

**Comment by timtylin** [comment]
Multiple citations in the same bracket should be separated by a semicolon `;` instead of a comma.

**Comment by scaramouche1** [comment]
Many thanks for the fast response!
