### ISSUE TITLE
Automatically footnote square-bracketed text w/o citations

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc-citeproc#117]
(Following on [this conversation](https://github.com/programminghistorian/jekyll/issues/46#issuecomment-82558415).)

Square-bracketed text without citations is usually ignored by citeproc, except when it's immediately preceded by a citation, as in this example from the User's Guide:

````@smith [p. 33] says blah.````

This yields **Smith<sup>1</sup> says blah.** while 

````@Smith, a great guy, [p. 33] says blah.```` yields **Smith,<sup>1</sup> a great guy, [p. 33] says blah.**

 This means that while notes with or following citations can be handled in whatever way is normal for the chosen style, notes without citations (and not immediately following them) cannot. Instead they need to be preceded by ^ to get them to be footnoted on their own. (The example I just gave is a little silly, but it's easy to come up with examples of note text not containing citations.)

If I have this right, I would love to be able not to worry about the contents of a note when writing it and just have all square-bracketed text be treated the same way, as notes. The second bit of text above would then yield **Smith,<sup>1</sup> a great guy,<sup>2</sup> says blah.** Since markdown normally escapes square brackets, I don't think this is a big imposition on editing, though perhaps an option to do this could be used.

**Comment by jgm** [comment]
How hard is it just to write

    @smith [p. 33], a great guy, says...

which seems more natural to me anyway?  Adding the feature you recommend would require indefinite lookahead and would add considerable complexity (and probably unanticipated bugs).  A secondary worry is that this would require much more escaping of square brackets than is normally needed in Markdown documents, breaking many existing documents. So, I'm not in favor.

+++ John Muccigrosso [Mar 18 15 12:38 ]:

**Comment by smith** [comment]
Aww thanks @jgm! :blush:

**Comment by Jmuccigr** [comment]
I don't want to cite anyone at all (no offence, @smith!).

The use case is when I want to put in a note that doesn't have a citation in it. In a footnote-using style, that requires a leading carat or pandoc-citeproc will ignore it. Personally I rarely use square brackets at all, so escaping them isn't a big deal for me. However if that's the problem, perhaps a flag within the brackets, like a sole "@" or a "@@@"?

**Comment by jgm** [comment]
+++ John Muccigrosso [Mar 19 15 09:57 ]:
>I don't want to cite anyone at all (no offence, @smith!).
>
>The use case is when I want to put in a note that doesn't have a citation in it.

So, you mean you want the "p. 33" to be a regular footnote?  As you know, you could just do

    ^[p. 33]

> In a footnote-using style, that requires a leading carat or pandoc-citeproc will ignore it. Personally I rarely use square brackets at all, so escaping them isn't a big deal for me.

It may be a problem for other people.

> However if that's the problem, perhaps a flag within the brackets, like a sole "@" or a "@@@"?

I don't see how

    [@@@p. 33]

is any better than

    ^[p. 33]

**Comment by Jmuccigr** [comment]
I see your point about a flag being a flag.

What I'm trying to do is both adhere to the statement that the better way to make notes for pandoc is to use just the square brackets, so that both in-line and footnoting styles will treat them appropriately (versus always using the carat) and not to have to worry about whether there's a citation in or preceding them in order to put in the carat deliberately. Perhaps I'm just going to have to live with the worry.

That the markdown renderer in MacDown (hoedown) won't recognize either of those as notes is another issue. I was using ````[^noteID]```` with a following ````[^noteID]: note text```` previously. That's a lot less intrusive and makes for more readable markdown text.

**Comment by Jmuccigr** [comment]
So here's a thought:

The markdown footnote method of using ````[^notemarker]```` followed by ````[^notemarker]: note text```` somewhere else in the text is appealing to me, and was in fact the method I was originally using. I like it because it allows me to keep the notes out of the main body of the text, making that a lot more readable.

pandoc-citeproc makes all these things into footnotes, regardless of the stylesheet in use. (I think it also doesn't format them the same way WRT punctuation.)

Why not treat these as notes of whatever kind of note the stylesheet dictates, instead of forcing them to be footnotes? IOW, treat any ````[^]```-enclosed text the way citation-including or -following square-brackted things are now? Then all notes would be treated the same way, regardless of the presence of a citation, and the markdown text would be readable. It would break the footnotes for anyone who doesn't have a csl indicated, since the default Chicago style is in-line (but perhaps it could be an option).

**Comment by jgm** [comment]
Some people like to use regular footnotes in addition to parenthetical
citations, for longer expository digressions that aren't just references.
So I don't think it would be good to convert footnotes into
parentheticals in cases like this.

+++ John Muccigrosso [Mar 27 15 08:28 ]:

**Comment by Jmuccigr** [comment]
Yes, I see how that would be problematic. Making the behavior optional would prevent that. Or those who want footnotes in an in-line style could use ````^[  ]````?

I notice that the CommonMarkdown spec handles ````[ ]```` all by itself differently, so maybe it's best to wait for that to continue this discussion? (Plus I don't see a lot of other people coming forward with the same concerns I have. :-) )
