### ISSUE TITLE
escaped character not taken into account

### ISSUE THREAD

**Issue by cdupont** [jgm/pandoc-citeproc#120]
In the reference for CSL they indicate that I can escape characters:
http://docs.citationstyles.org/en/latest/primer.html

    &lt; for <
    &gt; for >
    &amp; for &
    &apos; for '
    &quot; for "

However if I put this in the CSL:

    <text macro="title" font-weight="bold" display="block" suffix="&lt;/br&gt;"/>

Is is rendered like this in the source HTML code (special characters are not unescaped):

    “my title" lt;/br&gt; my_authors

What I really wanted is a line feed in the HTML, in order to have the paper title on a different line that the authors list  :)

**Comment by cdupont** [comment]
In fact it seems that the character list given in the above comment are the only one that are not unescaped:

    &amp;&apos;&quot;&#60;&#62;&#10;&#33;&#36;&#43;&#43;&#43;&#59;&#95;&#165;&#247;

Renders to:

    &amp;'&quot;&lt;&gt;!$+++;_¥÷

**Comment by jgm** [comment]
These are actually being escaped. However, pandoc-citeproc
interprets these fields as plain text, not as HTML.  Hence,
the result is re-escaped in HTML output.

I'm curious, does your modified file give you the result you
want with zotero/citeproc-js?  pandoc-citeproc could be
modified to treat these fields as HTML, if that is what is
called for.

+++ cdupont [Mar 24 15 10:02 ]:

**Comment by cdupont** [comment]
Hi John,
What I to achieve is to have the string "</br>" in the output.
But I cannot manage to achieve that...

**Comment by jgm** [comment]
@cdupont, there's no way to put raw HTML into these fields, sorry.
