### ISSUE TITLE
publisher-place variable getting mangled

### ISSUE THREAD

**Issue by palinurus** [jgm/pandoc-citeproc#121]
Pandoc-citeproc seems to be mangling publisher-place ("address") fields that include "and." Instead of, e.g., "Berkeley and Los Angeles" or "Oxford and New York," I get "Berkeley; Los Angeles" and "Oxford;  New York."

Here is an example of a bibTeX entry which, when called, produces this kind of error:

> @book{Carroll2006,
address = {Oxford and New York},
author = {Carroll, Maureen},
series = {Oxford Studies in Ancient Documents},
title = {{Spirits of the Dead. Roman Funerary Commemoration in Western Europe}},
year = {2006}
}

And here is the corresponding bibliography output: 

> Carroll, M. _Spirits of the Dead. Roman Funerary Commemoration in Western Europe._ Oxford; New York: Oxford University Press.

I don't know for sure that this is a problem with pandoc-citeproc, but I am not experiencing it using any other citation platforms with the same CSL file and it seems to occur regardless of the style I use (so long as the publisher-place field in its output, of course). Apologies if I am just being stupid.

**Comment by jgm** [comment]
It's definitely intentional, but I don't recall why it's there.
@nickbart1980 might remember.

The function `getLiteralList'` is used in `Text.CSL.Input.Bibtex'.  This
splits the field on "and" and intercalates the items with semicolons.
Note that this is only used for biblatex, not bibtex input.  (biblatex
is the default treatment of .bib files.)

+++ palinurus [Apr 01 15 13:09 ]:

**Comment by palinurus** [comment]
OK, thanks for the response-- I've now found your discussion about something similar at http://goo.gl/ZbXsiO and see the reasoning (although I don't think I fully agree with the solution, especially if one can't manipulate the process with CSL files anyway to, e.g., get an "and" or "et" instead of the semicolon [maybe I am misunderstanding? -- not actually a coder...]). Anyway, I get what I want from just changing from .bib to .bibtex, so that's good enough for me. Thanks!

**Comment by nickbart1980** [comment]
"and" is a list separator in the biblatex database format, not a literal string, and is being mapped by biblatex, the program, to whatever is required by a style; something that, regrettably, is not possible in CSL.
I maintain that mapping "and"s to semicolons is, while not perfect, the most sensible choice: It is language-independent, it works when three or more places are listed (unlike keeping "London and Paris and New York"), and it cannot be confused with a comma which usually separates city and state.
Anyone who wants a literal "and" should wrap it in curly braces.
