### ISSUE TITLE
An option to change numeric inline citations from "Reference 1" to  "ref. 1"?

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc-citeproc#125]
Pleas see https://github.com/citation-style-language/styles/issues/1535

Thanks!

**Comment by jgm** [comment]
I think we'll leave this as it is.  Ideally CSL would provide stylistic control over author-in-text citations, but until they do, I want to keep this as simple as possible, and not start creating our own new system for styling these.

**Comment by and3k** [comment]
See also #133
