### ISSUE TITLE
Request: allow ’ [smart apostrophe] in cite keys

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#127]
At least the xelatex/biber combo accepts these in biblatex cite keys.

zotxt generates "Easy Citekeys" containing `’` from names such as “O’Connor”, but currently pandoc chokes on these.

I don’t see any downside to permitting `’` just like many other UTF-8 chars (including accented and other modified chars) that work well in cite keys.

Apart from `’`, I don’t think there are any other non-letter characters that could be expected to occur in names, but in case there are, these should be allowed, too.

**Comment by jgm** [comment]
The problem I see is with things like this (author-in-text):

    according to @Smith’s study, ...

If the apostrophe is considered part of the cite key, then we
won't be looking for `Smith`, which is clearly what is intended here.

**Comment by njbart** [comment]
Agreed. Aesthetic considerations aside, there is nothing wrong with just using citekeys without any apostrophes. I’m closing this issue.
