### ISSUE TITLE
Remove brackets from author-in-text numerical citations?

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc-citeproc#133]
Hi!

Sorry that I’m being annoying about this topic, but would it be possible to remove the brackets for author-in-text numerical citations (which were introduced in e3a85ef31f2cea6f4a63bbf5be24f5694de27206)? If somebody wants the brackets they could just use the normal way.

**Example:**

The current way is a bit redundant:

```
[@ref1] says

@ref1 says
```

right now yields exactly the same thing:

```
<p><span class="citation">(<a href="#ref-ref1">1</a>)</span> says</p>
<p><span class="citation">(<a href="#ref-ref1">1</a>)</span> says</p>
```

Wouldn’t it be better to have this result:

```
<p><span class="citation">(<a href="#ref-ref1">1</a>)</span> says</p>
<p><span class="citation"><a href="#ref-ref1">1</a></span> says</p>
```

And then, if somebody (e.g. me) wants a prefix they could just write it into the text? Maximum flexibility but still simple!

Want do you think?

Thanks!!
Bela

**Comment by jgm** [comment]
Maybe not a bad solution. @nickbart, any thoughts?

Pandoc-citeproc strives to allow you to switch bib formats without
any changes in the source, and this change would break that.

On the other hand, the brackets are appropriate for ieee but not
for nature and some other styles.

I'm really not sure what the best approach is.

**Comment by nickbart1980** [comment]
Well, short of including specific formatting instructions into pandoc-citeproc that are dependent on but not included in the CSL style used, a plain number is probably the best solution.

This would also solve a minor problem with nature.csl and other styles using superscripts: (a) A superscript as grammatical part of the sentence looks very odd, and (b) any space between the number and preceding punctuation (like: end of previous sentence) is removed.

**Comment by and3k** [comment]
I now ran into exactly this problem with nature.csl ;) Both `@ref` and `[@ref]` render as superscript numbers and I concur that it would make more sense to render the first as a plain number and only the second as superscript.

I think this approach could be very systematic in that `@ref` would cause pandoc-citeproc to ignore certain arguments from the `<layout>` specifications. I.e. ignore Affixes (`prefix`, `suffix`)  and Formatting (`vertical-align`, etc), but honour `delimiter` …?

**Comment by jgm** [comment]
+++ Bela Hausmann [Aug 26 15 06:26 ]:
>   I now ran into exactly this problem with nature.csl ;) Both @ref and
>   [@ref] render as superscript numbers and I concur that it would make
>   more sense to render the first as a plain number and only the second as
>   superscript.
>
>   I think this approach could be very systematic in that @ref would cause
>   pandoc-citeproc to ignore certain arguments from the <layout>
>   specifications. I.e. ignore Affixes (prefix, suffix) and Formatting
>   (vertical-align, etc), but honour delimiter …?

That sounds reasonable to me.
