### ISSUE TITLE
CSL locales with just a two-letter code (ar, eu) do not work

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#140]
CSL locales with just a two-letter code (ar, eu) do not work.

~~~
pandoc -s -F pandoc-citeproc -t plain << EOT

@item1

# References

---
locale: ar
references:
- id: item1
  type: book
  editor:
  - family: Doe
    given: John
  issued:
  - year: 2015
  title: XXX
...
EOT

~~~

Output:

~~~
pandoc-citeproc: /Users/nick/Library/Haskell/share/ghc-7.8.3-x86_64/pandoc-citeproc-0.7.1/locales/locales-ar-AR.xml: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter pandoc-citeproc
~~~

It seems https://github.com/jgm/pandoc-citeproc/blob/master/src/Text/CSL/Data.hs#L74 needs to be updated.

As to `locale: eu` (Basque), this seems to be silently ignored.

~~~
pandoc -s -F pandoc-citeproc -t plain << EOT

@item1

# References

---
locale: eu
references:
- id: item1
  type: book
  editor:
  - family: Doe
    given: John
  issued:
  - year: 2015
  title: XXX
...
EOT
~~~

Actual:

~~~
Doe, John, ed. 2015. _XXX_.
~~~

Expected:

~~~
Doe, John, arg. 2015. _XXX_.
~~~

If `eu` needs to be configured explicitly then `la` for Latin should be added, too (`la` doesn't have a CSL locale file yet but this might change.)

**Comment by jgm** [comment]
+++ nickbart1980 [Jun 04 15 06:10 ]:
>CSL locales with just a two-letter code (ar, eu) do not work.

I've updated the locale files, and I get proper results with both
your examples.  However, I don't think the changes I made would have
affected these cases, so I'm wondering whether there's some other
problem on your end (e.g. with installation).

Is your version installed from the binary package or from 

Can you try with the latest?  (Be sure to `cabal install`, not just
`cabal build`, to make sure that the data files are installed in the
right place.)

**Comment by nickbart1980** [comment]
I had been using the latest, installed with `cabal install` but reinstalled just in case.

Now, it works as expected if `~/Library/Haskell/share/ghc-7.8.3-x86_64/pandoc-citeproc-0.7.1/locales/locales-ar-AR.xml` exists – but this file should *not* be there in the first place (ar-AR is an incorrect tag, that would be Arabic/Argentina). Note that no such file exists in `https://github.com/citation-style-language/locales`. The only correct language tag for Modern Standard Arabic is `ar`.

Now with `locales-ar.xml` but without `locales-ar-AR.xml` I still get the error from my original post. Same for `eu` (no error, but “ed.” rather than “arg.”).

I still suspect this is because neither `ar` nor `eu` are listed in https://github.com/jgm/pandoc-citeproc/blob/master/src/Text/CSL/Data.hs.
