### ISSUE TITLE
Question/feature request: How to suppress "clickable years" in citations?

### ISSUE THREAD

**Issue by jokorn** [jgm/pandoc-citeproc#141]
The issue [https://github.com/jgm/pandoc/issues/1117](https://github.com/jgm/pandoc/issues/1117) resulted in nice clickable years. However, not all journals support these kind of references. Is it possible to suppress the "clickable"/hyperref part when using pandoc-citeproc? For example by setting a variable in the YAML-header. I've searched the man page, stack-exchange and current+closed issues but can't find any mention of this. 
Sorry if the answer is obvious and thanks for the great work on this package.

**Comment by jgm** [comment]
I hope to add a feature soon to enable/disable this.
Indeed, I think it should be disabled by default.  A metadata field `link-citations: true` could turn it on.

**Comment by jokorn** [comment]
Wow, fast work! Just tested this and it works perfectly. Thank you very much and thank you for a great package!
