### ISSUE TITLE
Title is not transferred from markdown to AsciiDoc

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc-citeproc#144]
test.md:

```
---
title: Title
---

# Header

Text
```

```
pandoc test.md --filter pandoc-citeproc -t asciidoc
```

Output:

```
[[header]]
Header
------

Text
```

Expected output:

```
= Title

[[header]]
Header
------

Text
```

http://asciidoctor.org/docs/user-manual/#document-title

Thanks!
Bela

**Comment by and3k** [comment]
Arg… wrong repository. This bug belongs to https://github.com/jgm/pandoc. Shall I resubmit it or is this fine?

**Comment by and3k** [comment]
Author and Date metadata are also not transferred from markdown to AsciiDoc.

**Comment by jgm** [comment]
Use `-s` / `--standalone` if you want the metadata,
including title.

+++ Bela Hausmann [Jun 19 15 13:53 ]:

**Comment by and3k** [comment]
Oh, yes of course. That makes sense. Sorry about that!

Thanks!!
