### ISSUE TITLE
Install failed due network-uri

### ISSUE THREAD

**Issue by metal3d** [jgm/pandoc-citeproc#153]
I'm trying to create a container to install pandoc, pandoc-crossref and pandoc-citeproc.

At pandoc-citeproc install phase, there is an error:

```
Preprocessing library pandoc-citeproc-0.1.2.1...

src/Text/CSL/Parser.hs:30:8:
    Could not find module `Network.URI'
    It is a member of the hidden package `network-uri-2.6.0.3'.
    Perhaps you need to add `network-uri' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

I'm absolutly not a haskell and cabal expert but I found this:
https://github.com/haskell/cabal/issues/2063
And this:
https://github.com/jaspervdj/hakyll/commit/205f260eaf33c6c5a217f0d03e8ea7f5e3c40ca1

At this time, I'm blocked... Any help ?

**Comment by metal3d** [comment]
Forget... I saw the version that cabal want to install and then I checked the last release you've made. Seeing 0.7.1 I understood that cabal is in the past.

Forcing version worked. Sorry for that.

**Comment by amacfie** [comment]
I'm getting the same behavior. When I add `--constraint='network < 2.6'`, I get
the following. How exactly did you fix this, @metal3d ?

    [ 6 of 24] Compiling Text.CSL.Output.Pandoc ( src/Text/CSL/Output/Pandoc.hs, dist/dist-sandbox-511f2917/build/Text/CSL/Output/Pandoc.o )

    src/Text/CSL/Output/Pandoc.hs:85:55:

        Couldn't match expected type `Inline'

                    with actual type `Target -> Inline'

        In the return type of a call of `Link'

        Probable cause: `Link' is applied to too few arguments

        In the expression: Link (toStr $ snd u) u

        In the second argument of `toPandoc', namely

          `[Link (toStr $ snd u) u]'

    src/Text/CSL/Output/Pandoc.hs:85:61:

        Couldn't match type `[Inline]'

                      with `(String, [String], [(String, String)])'

        Expected type: Attr

          Actual type: [Inline]

        In the first argument of `Link', namely `(toStr $ snd u)'

        In the expression: Link (toStr $ snd u) u

        In the second argument of `toPandoc', namely

          `[Link (toStr $ snd u) u]'

    src/Text/CSL/Output/Pandoc.hs:85:76:

        Couldn't match type `(String, String)' with `[Inline]'

        Expected type: [Inline]

          Actual type: Target

        In the second argument of `Link', namely `u'

        In the expression: Link (toStr $ snd u) u

        In the second argument of `toPandoc', namely

          `[Link (toStr $ snd u) u]'

    src/Text/CSL/Output/Pandoc.hs:114:13:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link s r

        In a stmt of a pattern guard for

                       an equation for setCase':

          Link s r <- i

        In an equation for setCase':

            setCase' f i

              | Link s r <- i = Link (map (setCase f) s) r

              | otherwise = setCase f i

    src/Text/CSL/Output/Pandoc.hs:156:27:

        Couldn't match expected type `[Inline]' with actual type `(t0, t0)'

        In the second argument of `Link', namely `(s, s)'

        In the expression: Link x (s, s)

        In an equation for `escape': escape s x = Link x (s, s)

    src/Text/CSL/Output/Pandoc.hs:189:7:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link x t

        In a stmt of a pattern guard for

                       an equation for `clean':

          Link x t <- i

        In an equation for `clean':

            clean s b (i : is)

              | Superscript x <- i

              = split (isLink "baseline") (return . Superscript) x

                ++ clean s b is

              | Subscript x <- i

              = split (isLink "baseline") (return . Subscript) x ++ clean s b is

              | SmallCaps x <- i

              = split (isLink "nodecor") (return . SmallCaps) x ++ clean s b is

              | Emph x <- i

              = split (isLink' "emph") (return . Emph) x ++ clean s b is

              | Strong x <- i

              = split (isLink' "strong") (return . Strong) x ++ clean s b is

              | Link x t <- i = clean' s b (Link x t : clean s b is)

              | otherwise = clean' s b (i : clean s b is)

              where

                  unwrap f ls

                    | Link x _ : _ <- ls = clean' s b x

                    | _ : _ <- ls = f ls

                    | otherwise = []

                  isLink l il

                    | Link _ (x, y) <- il = x == l && x == y

                    | otherwise = False

                  isLink' l il

                    | Link _ (x, y) <- il = (x == l || x == "nodecor") && x == y

                    | otherwise = False

                  split _ _ [] = []

                  split f g xs

                    = let ... in concatMap (unwrap g) [...] ++ split f g (tail' r)

    src/Text/CSL/Output/Pandoc.hs:193:13:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link x _

        In the pattern: Link x _ : _

        In a stmt of a pattern guard for

                       an equation for `unwrap':

          Link x _ : _ <- ls

    src/Text/CSL/Output/Pandoc.hs:197:13:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link _ (x, y)

        In a stmt of a pattern guard for

                       an equation for `isLink':

          Link _ (x, y) <- il

        In an equation for `isLink':

            isLink l il

              | Link _ (x, y) <- il = x == l && x == y

              | otherwise = False

    src/Text/CSL/Output/Pandoc.hs:200:13:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link _ (x, y)

        In a stmt of a pattern guard for

                       an equation for isLink':

          Link _ (x, y) <- il

        In an equation for isLink':

            isLink' l il

              | Link _ (x, y) <- il = (x == l || x == "nodecor") && x == y

              | otherwise = False

    src/Text/CSL/Output/Pandoc.hs:209:7:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link inls (y, z)

        In a stmt of a pattern guard for

                       an equation for clean':

          Link inls (y, z) <- i

        In an equation for clean':

            clean' s b (i : is)

              | Link inls (y, z) <- i, y == "inquote", y == z

              = case headInline is of {

                  [x]

                    -> if x `elem` ".," && b then

                           if lastInline inls `elem` ... then

                               quote DoubleQuote inls : clean' s b (tailInline is)

                           else

                               quote DoubleQuote (inls ++ ...) : clean' s b (tailInline is)

                       else

                           quote DoubleQuote inls : clean' s b is

                  _ -> quote DoubleQuote inls : clean' s b is }

              | Quoted t inls <- i = quote t inls : clean' s b is

              | otherwise

              = if lastInline [i] == headInline is && isPunct then

                    i : clean' s b (tailInline is)

                else

                    i : clean' s b is

              where

                  quote t x = Quoted t (reverseQuoted t x)

                  isPunct = and . map (flip elem ".,;:!? ") $ headInline is

                  reverseQuoted t

                    = proc reverseQuoted'

                    where

                        reverseQuoted' q

                          | Quoted _ qs <- q, DoubleQuote <- t

                          = Quoted SingleQuote (reverseQuoted SingleQuote qs)

                          | Quoted _ qs <- q, SingleQuote <- t

                          = Quoted DoubleQuote (reverseQuoted DoubleQuote qs)

                          | otherwise = q

    src/Text/CSL/Output/Pandoc.hs:245:19:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link ls (x, y)

        In a stmt of a pattern guard for

                       an equation for reverseEmph':

          Link ls (x, y) <- e

        In an equation for reverseEmph':

            reverseEmph' e

              | bo, Emph inls <- e

              = Link (reverseEmph False inls) ("emph", "emph")

              | Emph inls <- e = Emph (reverseEmph True inls)

              | Link ls (x, y) <- e

              = if x == "nodecor" && x == y then Link ls ("emph", "emph") else e

              | otherwise = e

    src/Text/CSL/Output/Pandoc.hs:254:19:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link ls (x, y)

        In a stmt of a pattern guard for

                       an equation for reverseStrong':

          Link ls (x, y) <- e

        In an equation for reverseStrong':

            reverseStrong' e

              | bo, Strong inls <- e

              = Link (reverseStrong False inls) ("strong", "strong")

              | Strong inls <- e = Strong (reverseStrong True inls)

              | Link ls (x, y) <- e

              = if x == "nodecor" && x == y then

                    Link ls ("strong", "strong")

                else

                    e

              | otherwise = e

    src/Text/CSL/Output/Pandoc.hs:314:7:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link is t

        In a stmt of a pattern guard for

                       an equation for `initInline':

          Link is t <- i

        In an equation for `initInline':

            initInline (i : [])

              | Str s <- i = return $ Str (init' s)

              | Emph is <- i = return $ Emph (initInline is)

              | Strong is <- i = return $ Strong (initInline is)

              | Superscript is <- i = return $ Superscript (initInline is)

              | Subscript is <- i = return $ Subscript (initInline is)

              | Quoted q is <- i = return $ Quoted q (initInline is)

              | SmallCaps is <- i = return $ SmallCaps (initInline is)

              | Strikeout is <- i = return $ Strikeout (initInline is)

              | Link is t <- i = return $ Link (initInline is) t

              | otherwise = []

              where

                  init' s = if s /= [] then init s else []

    src/Text/CSL/Output/Pandoc.hs:344:7:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link is t

        In a stmt of a pattern guard for

                       an equation for `mapHeadInline':

          Link is t <- i

        In an equation for `mapHeadInline':

            mapHeadInline f (i : xs)

              | Str [] <- i = mapHeadInline f xs

              | Str s <- i = Str (f s) : xs

              | Emph is <- i = Emph (mapHeadInline f is) : xs

              | Strong is <- i = Strong (mapHeadInline f is) : xs

              | Superscript is <- i = Superscript (mapHeadInline f is) : xs

              | Subscript is <- i = Subscript (mapHeadInline f is) : xs

              | Quoted q is <- i = Quoted q (mapHeadInline f is) : xs

              | SmallCaps is <- i = SmallCaps (mapHeadInline f is) : xs

              | Strikeout is <- i = Strikeout (mapHeadInline f is) : xs

              | Link is t <- i = Link (mapHeadInline f is) t : xs

              | otherwise = i : xs

    src/Text/CSL/Output/Pandoc.hs:356:7:

        Constructor `Link' should have 3 arguments, but has been given 2

        In the pattern: Link is _

        In a stmt of a pattern guard for

                       an equation for `getInline':

          Link is _ <- i

        In an equation for `getInline':

            getInline i

              | Emph is <- i = is

              | Strong is <- i = is

              | Strikeout is <- i = is

              | Superscript is <- i = is

              | Subscript is <- i = is

              | Quoted _ is <- i = is

              | SmallCaps is <- i = is

              | Link is _ <- i = is

              | otherwise = []

    Failed to install pandoc-citeproc-0.1.2.1

**Comment by metal3d** [comment]
@amacfie ho my god that was one year ago. I really don't remember how I did. Anyway, I tried to install pandoc with cabal again last week and get a lot of "version" problem. I simply forced installation of dependecies with "--reinstall" option (if I'm not wrong) as soon as the installation crash.

BTW: I had to install and update cabal before.

Sorry to not give you more interesting information.

**Comment by metal3d** [comment]
One more information, I think I did:

```
cabal install network-uri-2.6.0.3
```

Then relaunch installation... Something like this

**Comment by metal3d** [comment]
And a last inforamtion, a working dockerfile that compiles pandoc as expected:

```dockerfile
FROM haskell:7.10
MAINTAINER Patrice FERLET <metal3d@gmail.com>

RUN set -xe; \
    cabal update; \
    cabal install pandoc
RUN set -xe; \
    apt-get update -y; \
    apt-get install -y \
        texlive-full; \
    apt-get clean;

VOLUME ["/workspace"]
WORKDIR /workspace
CMD ["/root/.cabal/bin/pandoc"]
```

texlive-full is huge, you can remove the installation to test pandoc compilation. I need texlive-full to not be blocked because a lack of latex package I need

**Comment by amacfie** [comment]
@metal3d Thanks! Still couldn't get cabal to work so I used [the Ubuntu 16.04 package](https://launchpad.net/ubuntu/xenial/amd64/pandoc-citeproc/0.9-1)
