### ISSUE TITLE
Set initial number for numerical citations?

### ISSUE THREAD

**Issue by and3k** [jgm/pandoc-citeproc#154]
Would it be possible to add a feature to start with a higher number than 1 when using numerical citations? e.g. the first citation number is ref. 10, instead of ref. 1.

Thanks,
Bela

**Comment by jgm** [comment]
I'm curious, why would you need this?

+++ Bela Hausmann [Aug 03 15 05:45 ]:

**Comment by and3k** [comment]
Separate documents which belong together. Like book chapters or a Paper + it’s Supplementary Material. But I had to anyway do  something more complex now, so feel free to also close this issue…
