### ISSUE TITLE
Controlling the presence or absence of href links in citations in output HTML?

### ISSUE THREAD

**Issue by lonniev** [jgm/pandoc-citeproc#155]
I am using pandoc and its citeproc filter to produce HTML that is fed to Prince XML for generation of formatted PDF from initial Markdown text. The workflow works quite well. Now, I have a conference that requires that the PDF be free of HREF links.

I am trying to figure out where in my workflow I can tell panic (or introduce a filter) such that it does not wrap the URLs from Zotero entries in "a href" spans. I am using the ieee-with-url.csl.

Is there a command-line flag to tell pandoc to not auto-wrap URLs when it emits its HTML output? If not, is there convenient XSLT that I can tweak in the CSL file to not do that wrapping? If not, is there an existing additional pandoc filter that strips out this "a href" wrappers?

The complete workflow is described in https://www.academia.edu/14436493/Stay_Focused_on_Content_with_an_Automation_Workflow_for_Professional_Publication complete with a bibliographic references section that illustrates the unwanted href links. (Note that the href links aren’t always unwanted, I just have a particular submission process that denies papers with them. I need something optional.)

**Comment by jgm** [comment]
+++ Lonnie VanZandt [Aug 05 15 14:14 ]:
>   I am using pandoc and its citeproc filter to produce HTML that is fed
>   to Prince XML for generation of formatted PDF from initial Markdown
>   text. The workflow works quite well. Now, I have a conference that
>   requires that the PDF be free of HREF links.
>
>   I am trying to figure out where in my workflow I can tell panic (or
>   introduce a filter) such that it does not wrap the URLs from Zotero
>   entries in "a href" spans. I am using the ieee-with-url.csl.
>
>   Is there a command-line flag to tell pandoc to not auto-wrap URLs when
>   it emits its HTML output? If not, is there convenient XSLT that I can
>   tweak in the CSL file to not do that wrapping? If not, is there an
>   existing additional pandoc filter that strips out this "a href"
>   wrappers?

In the most recent version of pandoc-citeproc (0.7.2), citation
linking is OFF by default, and you can turn it on by setting
the `link-citations` metadata field to a true value.

So, upgrade!

**Comment by lonniev** [comment]
Oh, sweet!

I’ll try that. Thanks.

-- 
Lonnie VanZandt
303-900-3048

On 06 August 2015 at 11:33:19, John MacFarlane (notifications@github.com) wrote:

+++ Lonnie VanZandt [Aug 05 15 14:14 ]:
> I am using pandoc and its citeproc filter to produce HTML that is fed
> to Prince XML for generation of formatted PDF from initial Markdown
> text. The workflow works quite well. Now, I have a conference that
> requires that the PDF be free of HREF links.
>
> I am trying to figure out where in my workflow I can tell panic (or
> introduce a filter) such that it does not wrap the URLs from Zotero
> entries in "a href" spans. I am using the ieee-with-url.csl.
>
> Is there a command-line flag to tell pandoc to not auto-wrap URLs when
> it emits its HTML output? If not, is there convenient XSLT that I can
> tweak in the CSL file to not do that wrapping? If not, is there an
> existing additional pandoc filter that strips out this "a href"
> wrappers?

In the most recent version of pandoc-citeproc (0.7.2), citation
linking is OFF by default, and you can turn it on by setting
the `link-citations` metadata field to a true value.

So, upgrade!

**Comment by jgm** [comment]
If it works, please close this issue.

+++ Lonnie VanZandt [Aug 06 15 10:35 ]:
>   Oh, sweet!
>   I’ll try that. Thanks.
>   --
>   Lonnie VanZandt
>   303-900-3048
>   On 06 August 2015 at 11:33:19, John MacFarlane

**Comment by lonniev** [comment]
/usr/local/Cellar/pandoc-citeproc/0.7.2/bin/pandoc-citeproc --version
pandoc-citeproc 0.7.2


Apparently, something is still wanting to help out. Those blue links in the PDF in Preview are live. I need them to be plain text.

-- 
Lonnie VanZandt
303-900-3048

On 06 August 2015 at 11:47:47, John MacFarlane (notifications@github.com) wrote:

If it works, please close this issue.

+++ Lonnie VanZandt [Aug 06 15 10:35 ]:
> Oh, sweet!
> I’ll try that. Thanks.
> --
> Lonnie VanZandt
> 303-900-3048
> On 06 August 2015 at 11:33:19, John MacFarlane

**Comment by jgm** [comment]
Oh, I see -- you're not talking about citations linking to
the bibliography, but about URLs in the bibliography itself.
(I jumped to conclusions w/o looking at your sample.)

The behavior is hardcoded (src/Text/CSL/Eval.hs at l. 213).

So maybe we need to think about how to turn it off.

As a workaround, if you don't want any links in your
document, maybe you could redefine \href at the beginning
of your document?

    \renewcommand{\href}[1]{#1}


+++ Lonnie VanZandt [Aug 06 15 10:51 ]:
>   /usr/local/Cellar/pandoc-citeproc/0.7.2/bin/pandoc-citeproc --version
>   pandoc-citeproc 0.7.2
>   Apparently, something is still wanting to help out. Those blue links in
>   the PDF in Preview are live. I need them to be plain text.
>   --
>   Lonnie VanZandt
>   303-900-3048
>   On 06 August 2015 at 11:47:47, John MacFarlane

**Comment by lonniev** [comment]
Ok.

Perhaps I just write an XSLT transform that strips those in the “references” div out of the intermediate HTML.

-- 
Lonnie VanZandt
303-900-3048

On 06 August 2015 at 12:22:15, John MacFarlane (notifications@github.com) wrote:

Oh, I see -- you're not talking about citations linking to
the bibliography, but about URLs in the bibliography itself.
(I jumped to conclusions w/o looking at your sample.)

The behavior is hardcoded (src/Text/CSL/Eval.hs at l. 213).

So maybe we need to think about how to turn it off.

As a workaround, if you don't want any links in your
document, maybe you could redefine \href at the beginning
of your document?

\renewcommand{\href}[1]{#1}


+++ Lonnie VanZandt [Aug 06 15 10:51 ]:
> /usr/local/Cellar/pandoc-citeproc/0.7.2/bin/pandoc-citeproc --version
> pandoc-citeproc 0.7.2
> Apparently, something is still wanting to help out. Those blue links in
> the PDF in Preview are live. I need them to be plain text.
> --
> Lonnie VanZandt
> 303-900-3048
> On 06 August 2015 at 11:47:47, John MacFarlane

**Comment by lonniev** [comment]
I stripped them out with a regex filter. Ping me here if you implement a way to ask citeproc not to wrap URLs in anchor tags.

**Comment by jgm** [comment]
OK, let's leave this issue open as a reminder.

+++ Lonnie VanZandt [Aug 10 15 13:04 ]:
