### ISSUE TITLE
No space before :sup: in the reStructeredText output

### ISSUE THREAD

**Issue by stvharman** [jgm/pandoc-citeproc#157]
Hello, I use vancouver-superscript.csl when converting from orgmode to rst. The reference list and entries look great. However, I obtain citations in my rst output such as this one:

Blah blah.:sup:`1`

Whereas for rst editors and programs to understand it correctly, there needs to be a space before the first colon. So, it should be:

Blah blah. :sup:`1`

I was wondering if I am missing something or if there can be anything done about this.

Thanks in advance,

Steve

**Comment by jgm** [comment]
I believe it's a pandoc issue, not a pandoc-citeproc issue.  But
first, what version of pandoc are you using?  Recent
versions seem to insert the necessary `\ ` before the
`:sup:`.

+++ stvharman [Aug 12 15 19:07 ]:

**Comment by stvharman** [comment]
Thank you, John. Here are my versions:

$ pandoc --version
pandoc 1.15.0.6

$ pandoc-citeproc --version
pandoc-citeproc 0.7.2

**Comment by jgm** [comment]
Can you give me something sufficient to reproduce the
problem?  A small Markdown sample, bibliography, and
the stylesheet you're using (or its name if it's from
the standard csl repository).

+++ stvharman [Aug 13 15 10:42 ]:

**Comment by stvharman** [comment]
Sure. Try this from the command line:

```bash
pandoc --filter pandoc-citeproc --bibliography  mybib.bib --csl vancouver-superscript.csl   test.org -s -o test.rst
```

You can download mybib.bib from here http://shelah.logic.at/mybib.bib  (or really use any bib file)

The content of test.org can be only one line:

#+BEGIN_SRC
Here is my reference [@small]
#+END_SRC

Then it will produce the following test.rst

#+BEGIN_SRC
Here is my reference:sup:`1`

.. raw:: html

   <div class="references">

.. raw:: html

   <div id="ref-small">

1. Freely I. A small paper. The journal of small papers. 1997;-1.

.. raw:: html

   </div>

.. raw:: html

   </div>
#+END_SRC

**Comment by stvharman** [comment]
Verified. It works. Thanks John.
