### ISSUE TITLE
Test suite failure for 0.7.3

### ISSUE THREAD

**Issue by snoyberg** [jgm/pandoc-citeproc#158]
```
--- expected    2015-08-14 08:02:18.141475999 +0000
+++ actual      2015-08-14 08:02:18.145475999 +0000
@@ -8,3 +8,3 @@
   issued:
-  - year: 2005
+  - year: '2005'
   title: First book
@@ -19,7 +19,7 @@
   issued:
-  - year: 2006
+  - year: '2006'
   title: Article
   container-title: Journal of Generic Studies
-  page: 33-34
-  volume: 6
+  page: '33-34'
+  volume: '6'

@@ -36,3 +36,3 @@
   issued:
-  - year: 2007
+  - year: '2007'
   title: Why water is wet
23 passed; 1 failed; 0 skipped; 0 errored.
Test suite test-pandoc-citeproc: FAIL
Test suite logged to: /home/stackage/work/logs/nightly/pandoc-citeproc-0.7.3/test-run.out
```

I'm slightly worried that this may be due to a change in the yaml package, though I'm unaware of any intended behavioral changes of this type.

**Comment by snoyberg** [comment]
Indeed, this is caused by a change in the yaml package, specifically https://github.com/snoyberg/yaml/pull/66/files#diff-21bb4e66a7625a4754dc68e9c7c40aaaL58 (pinging @phadej). @jgm Can you comment as to whether the new output is correct for your use case?

**Comment by phadej** [comment]
Yes, I changed `string` `YamlBuilder` to escape number looking strings (there was an issue in default `yaml` encoder: https://github.com/snoyberg/yaml/issues/31)

As `Builder` is tagged as an experimental module, I wasn't afraid to "fix" that behaviour.

If old functionality is needed, it's easily recovered in the use place, old version is in the diff.

**Comment by jgm** [comment]
This should be okay for us.  We convert numbers to strings
on input, allowing users to omit the quotes.  Although
having the quotes on the output is a bit worse from an
aesthetic point of view, it shouldn't break anything.

+++ Michael Snoyman [Aug 14 15 03:23 ]:

**Comment by jgm** [comment]
I'm not sure why only one test failed, though - since many
others lack quotes around numbers.  Will look into this.

**Comment by jgm** [comment]
Interesting. Compiling with latest yaml, I get:
28 passed; 115 failed; 0 skipped; 0 errored.

This made me realize that I was missing a line in
the cabal file data-files section:

    tests/biblio2yaml/*.biblatex


+++ Michael Snoyman [Aug 14 15 01:43 ]:
