### ISSUE TITLE
No hyperlink when converting from org to other formats. Possibly, a link-citations problem?

### ISSUE THREAD

**Issue by stvharman** [jgm/pandoc-citeproc#159]
Hello again! 

I use:

pandoc 1.15.0.6
pandoc-citeproc 0.7.2

In my orgmode file, exp.org, I have

#+CITATION-STYLE: chicago-author-date.csl
#+LINK-CITATIONS: true

When I produce an html file from exp.org

pandoc --filter pandoc-citeproc exp.org -s -o exp.html

It correctly shows my citations and references. However, there is no hyperlink.

What would be your thoughts on this?

thanks in advance,

--
steve

**Comment by stvharman** [comment]
Just to add, conversion to rst (which I'm actually interested in doing) has the same effect which is that there is no link. I was trying to if it worked for html but it didn't work for it either.

**Comment by jgm** [comment]
Looks like pandoc's org reader is parsing the "true" as a string
rather than a Boolean.  So I think what is needed is a
change to the org reader.  Pinging @tarleb who may know
more.

+++ stvharman [Aug 14 15 17:55 ]:

**Comment by jgm** [comment]
I think I'll just change pandoc-citeproc so it recognizes true-ish string values.

**Comment by stvharman** [comment]
When I downloaded this version, compiled, and ran, it did not work for me. However, my workaround is to use ox-pandoc.el from inside emacs. It accepts pandoc metadata. If I issue the following, then I get nice hyperlinks:

#+PANDOC_METADATA: link-citations:true

Any idea about why

#+LINK_CITATIONS: true

is not working?

thanks in advance

-- 
Steve

**Comment by jgm** [comment]
Tell us exactly what you did.
Output of `pandoc --version`, `pandoc-citeproc --version`,
exact command line, exact input.

+++ stvharman [Aug 17 15 12:04 ]:

**Comment by jgm** [comment]
Oh, I see the problem:  you have

    #+LINK_CITATIONS: true

but what you need is

    #+LINK-CITATIONS: true

+++ stvharman [Aug 17 15 12:04 ]:

**Comment by stvharman** [comment]
Thank you. You're right. It should be with a dash, not underscore. If you use a dash, it works.
However, when I produce an rst from the org file, there is a syntactic issue, i think. This is the current output

\ :sup:``1 <#ref-small>`__`

This doesn't work when I try to use the rst file as an input to Pelican (a static website generation tool)

Or, is the mechanism for linking citations currently intended to serve only html outputs?

thanks

**Comment by jgm** [comment]
+++ stvharman [Aug 17 15 14:22 ]:
>Thank you. You're right. It should be with a dash, not underscore. If you use a dash, it works.
>However, when I produce an rst from the org file, there is a syntactic issue, i think. This is the current output
>
>\ :sup:``1 <#ref-small>`__`
>
>This doesn't work when I try to use the rst file as an input to Pelican (a static website generation tool)
>
>Or, is the mechanism for linking citations currently intended to serve only html outputs?

It should ideally work in rst, too.

I tried this output with rst2html (from docutils), and
it interprets the initial double-backtick as the
start of a code literal.

I thought it might be an escaping issue and tried
separating the backticks with an escaped space,
but this didn't work.

I fear we may have run up against a docutils limitation.
They may not support links within superscript contexts.

If you can find out the proper RST markup for

Superscript (Link (content))

let me know.

**Comment by stvharman** [comment]
I did some research into this problem and found the info here:

http://docutils.sourceforge.net/FAQ.html#is-nested-inline-markup-possible

maybe a raw directive for the citation itself could be possible.

**Comment by qualiaa** [comment]
Just bumped into this in year of our lord 2021, and while the issue is totally different to the one above, it took me a while to work out how, so I thought I should post my solution here.

The key thing is [this section of the pandoc Org documentation](https://pandoc.org/org.html#directives-as-metadata) - **`#+k:v` lines are no longer added to metadata automatically**. The docs provide a Lua filter to mimic the old behaviour, but its key matching is a bit limited and `link-citations` isn't picked up.

In the end I adjusted the example filter to solve the problem:

```lua
-- Adapted from https://pandoc.org/org.html
-- intermediate store for variables and their values
local variables = {}

--- Convert keyword value to boolean if "t(rue)?", "f(alse)?"
function parse_value(value_string)
  lower = value_string:lower()
  if lower == "t" or lower == "true" then
    return true
  elseif lower == "f" or lower == "false" then
    return false
  end
  return value_string
end

--- Function called for each raw block element.
function RawBlock (raw)
  -- Don't do anything unless the block contains *org* markup.
  if raw.format ~= 'org' then return nil end

  -- Extract variable name and value
  -- Allow key comprising alphanumeric + "-_".
  -- Allow value with at least 1 non-space character
  -- Trim whitespace around value
  local name, value = raw.text:match '#%+(%w[%w_-]*):%s*(%g.-)%s*$'
  if name and value then
    -- Org keys are typically UPPER_CASE, but pandoc metadata keys are
    -- lowercase, so convert keys to lowercase
    variables[name:lower()] = parse_value(value)
  end
end

-- Add the extracted variables to the document's metadata.
function Meta (meta)
  for name, value in pairs(variables) do
    meta[name] = value
  end
  return meta
end
```
