### ISSUE TITLE
CSL JSON/YAML names should *not* be parsed for particles by default

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#164]
When using CSL JSON/YAML databases, pandoc-citeproc tries to parse particles from names.

This does not conform to the CSL specs and leads to incorrect results when a family name contains strings that look like, but in fact are not, particles.

pandoc-citeproc should stop trying to parse particles by default when using CSL JSON and CSL YAML databases – to conform to the CSL specs, and to ensure interoperability with other software that does.

Example:

~~~
cat > a3.json << EOT
[
	{
		"id": "id1",
		"type": "book",
		"title": "Test 1 - “van” is non-dropping-particle",
		"author": [
			{
				"family": "Author",
				"given": "Al",
				"non-dropping-particle": "van"
			}
		],
		"issued": { "date-parts": [[ "2014" ]] }
	},
	{
		"id": "id2",
		"type": "book",
		"title": "Test 2 - “van” is fixed part of family name",
		"author": [
			{
				"family": "van Author",
				"given": "Al"
			}
		],
		"issued": { "date-parts": [[ "2014" ]] }
	}
]
EOT

pandoc  -F pandoc-citeproc --biblio a3.json -t plain << EOT

---
csl: https://gist.githubusercontent.com/nickbart1980/245c0027350cfbc44b72/raw/ade2a724e125074e9e432d8b7da1c54283efb56c/chicago-author-date--demote-display-and-sort.csl
...

@id1; @id2

# References
EOT
~~~

Actual:

~~~
van Author (2014); van Author (2014)



REFERENCES


Author, Al van. 2014. _Test 1 - “van” Is Non-Dropping-Particle_.

Author, Al van. 2014. _Test 2 - “van” Is Fixed Part of Family Name_.
~~~

Expected:

~~~
van Author (2014); van Author (2014)



REFERENCES


Author, Al van. 2014. _Test 1 - “van” Is Non-Dropping-Particle_.

van Author, Al. 2014. _Test 2 - “van” Is Fixed Part of Family Name_.
~~~

Notes:

The custom csl style uses `demote-non-dropping-particle="display-and-sort"`, so that, to make the difference clear, whatever is parsed as non-dropping particle is shown *after* the first name.

Again, parsing of names is not part of the official CSL specs. If pandoc-citeproc wants to continue to offer it as an option, then when using CSL JSON/YAML databases it should only be activated when pandoc-citeproc is explicitly asked to do so, i.e., when the (citeproc-js, but not official CSL) per-entry flag `parse-names` is set, or via a command line switch. Note that if pandoc-citeproc *does* parse, it needs to exclude from parsing name fields that are enclosed in double quotes (see https://github.com/jgm/pandoc-citeproc/issues/151).

**Comment by jgm** [comment]
I've changed the parse-names default to False.

You can try the latest by pulling from the repository and
using 'stack test'.  (I suggest installing stack
https://github.com/commercialhaskell/stack/
rather than using cabal, though cabal should still work.)

issue77 test now fails.  I think the test may need some
adjusting in light of the changed default for parse-names.
Could you look at it?

+++ nickbart1980 [Sep 09 15 03:02 ]:

**Comment by nickbart1980** [comment]
Wait, this is not about parsing bibtex/biblatex databases at all, it’s only about CSL JSON and CSL YAML databases, which already contain fully parsed names. If you revert the changes to Bibtex.hs, does the issue77 test still fail?

**Comment by jgm** [comment]
It seemed to me that the changes to Bibtex.hs were
warranted.  The bibtex parser already has code to parse
names into prefixes and the like.  So, why should it
set parse-names to True?

+++ nickbart1980 [Sep 09 15 13:18 ]:

**Comment by nickbart1980** [comment]
Ok, that was a shot in the dark, sorry. It seems the names in the data used for issue77 (see https://github.com/jgm/pandoc-citeproc/issues/77) all contain a suffix in the given field and thus now all need to have `parse-names: true` added.

**Comment by jgm** [comment]
OK, this seems to be fixed by the latest commits!

**Comment by adunning** [comment]
I will also note that Zotero now appears to be correctly breaking out "Jr", "III", etc. into a separate 'suffix' field, so the original problem I noted shouldn't be an issue any longer. I haven't tested it with the most recent commits, but here's an example:

```json
{"id":"robertson:1946note","type":"article-journal","title":"A Note on the Classical Origin of \"Circumstances\" in the Medieval Confessional","container-title":"Studies in Philology","page":"6-14","volume":"43","issue":"1","source":"JSTOR","URL":"http://www.jstor.org/stable/4172741","journalAbbreviation":"Studies in Philology","author":[{"family":"Robertson","given":"D.W.","suffix":"Jr"}],"issued":{"date-parts":[["1946",1]]},"accessed":{"date-parts":[["2014",3,19]]}}
```
