### ISSUE TITLE
Citations in text only link to the bibliography section not the citation itself

### ISSUE THREAD

**Issue by hadim** [jgm/pandoc-citeproc#174]
All is in the title.

I don't know wether it is the excepted behaviour or a technical limitation (or a mistake from me...).

I tried both default and custom styles (`cell.csl`).

**Comment by jgm** [comment]
Please give:

- `pandoc --version`
- `pandoc-citeproc --version`
- input file(s) and command line you used
- (HTML) output you received

Note that you should set `link-citations: true` in your
YAML metadata if you want linked citations.

+++ Hadrien Mary [Sep 26 15 05:04 ]:

**Comment by hadim** [comment]
```
$ pandoc --version
pandoc 1.15.0.6
$ pandoc-citeproc --version
pandoc-citeproc 0.7.3.1
```

And I already set `link-citations: true` in the YAML header.

**Comment by jgm** [comment]
You did not provide a minimal example I can use to reproduce
what you're seeing, so I can't say more until you do.
You might try with pandoc-citeproc 0.7.4.  It works well for me.

+++ Hadrien Mary [Sep 26 15 10:28 ]:

**Comment by hadim** [comment]
`pandoc-citeproc 0.7.4` does not solve the issue. I will try to get a minimal example working in the next few days and I'll notify you.

Note that I generate latex and pdf files (and not HTML).

Thank you

**Comment by mclearc** [comment]
I have similar problems. I'm using `panic-citeproc 0.7.3` and `pandoc 1.15.0.6` from homebrew, but I have never gotten this to work properly. Here are some links to some working (or not working) examples.

https://www.dropbox.com/sh/c4w6jc1c6p6sr1v/AABnVisrr7wKafNE4BNg5d5ka?dl=0

**Comment by mclearc** [comment]
Also -- apologies for the long `default.latex` template. If you need a simpler example let me know.

**Comment by jgm** [comment]
@mclearc thanks for the sample.  I see what you mean; the hyperlink in the PDF just takes you to the section.  Inspecting the LaTeX, though, everything looks okay:  for the link we have

``` latex
Here's a test citation, Friedman (\hyperref[ref-friedman1985]{1985}).
```

and for the bib entry we have

``` latex
\hyperdef{}{ref-friedman1985}{\label{ref-friedman1985}}
Friedman, Michael. 1985. ``Kant's Theory of Geometry.'' \emph{The
Philosophical Review} 94 (4): 455--506.
```

We may need the advice of someone who is more knowledgeable than I am about exactly how hyperlinking works in LaTeX to see what is wrong with this.

**Comment by mclearc** [comment]
Thanks John. I wish I knew more about LaTeX to be able to help, but I haven't been able to get it working, neither with this template or more vanilla ones.

**Comment by MrLoh** [comment]
I had a look at the [hyperref package documentation](http://ctan.org/pkg/hyperref) and it seems like you are simply using the wrong syntax. You should be usind `hyperlink` and 'hypertarget` instead of `hyperref` and `hyperdef`. It's pretty straigt forward. You can turn the first Word or whatever you want into the link target. 

Hope this solve the issue and you can easily implement @jgm, I would send you a pull request, but you're probably much faster in adjusting this in the haskell. Thanks for your amazing package! Hope this helps to close the issue very soon. 

While at this hyperrref stuff. Is there anyway to use the `autoref` command via pandoc. It is really nice for automatically providing section numbers for a link. `\autoref{ref}` outputs `section 1` in the example below, so you don't have to keep track of section numbers in your text. I understand that this is a little complicated for interoperatability with HTML, but it would be a dope addition --- also in HTML ouput of course. 

```
\documentclass{book}
\usepackage{hyperref}
\begin{document}

test citation 1, Friedman (\hyperlink{ref-friedman1985}{1985}).

test citation 2, Davidson (\hyperlink{ref-davidson2000}{2000}).

It doesn't link to \autoref{ref} anymore, but to the citations themselves.


\newpage
\section{References}\label{ref}

\newpage
\hypertarget{ref-friedman1985}{Friedman}, Michael. 1985...
\newpage
\hypertarget{ref-davidson2000}{Davidson}, Donald. 2000...

\end{document}
```

**Comment by hadim** [comment]
Thank you @MrLoh !

**Comment by hadim** [comment]
@jgm any quick fix waiting for a PR merged in master I can apply myself ? (in fact I need to return my phd thesis in two days :-D)

**Comment by jgm** [comment]
The actual LaTeX is generated by pandoc's LaTeX writer, so any changes will need to be made there.

**Comment by MrLoh** [comment]
I could give it a try, the fixes in the [Latex Writer](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs) should be pretty straight forward, but while I know some haskell, I don't have any experience how to use libraries in haskell. Is there some compilation needed, or how can I envoke the local modified version of pandoc from the command line to test wether it works? The [Contribution guidelines](https://github.com/jgm/pandoc/blob/master/CONTRIBUTING.md) don't explain any of this.

**Comment by MrLoh** [comment]
So I tried a really trivial fix. I don't know nor have the time to test this properly, but this should be the only thing that needs to be changed. If someone could help with the testing, that would be awesome.

**Comment by hadim** [comment]
I'll test that tomorrow.

**Comment by jgm** [comment]
I've been working on a fix, should have it soon.

**Comment by MrLoh** [comment]
yeah, that's what I was tring to do, just better ;) Great stuff your dedication @jgm, I’ll have to learn how to properly use haskell libraries.
