### ISSUE TITLE
Add `note` field to default CSL

### ISSUE THREAD

**Issue by MrLoh** [jgm/pandoc-citeproc#180]
The default [chicago-author-date.csl](https://github.com/jgm/pandoc-citeproc/blob/master/chicago-author-date.csl) does not use the `note` field, which it probably should.

**Comment by MrLoh** [comment]
I would be happy to create a pull-request myself, if someone could point me into the right direction for how to add new fields from bibtex in a CSL file.

**Comment by nickbart1980** [comment]
pandoc-citeproc clones chicago-author-date.csl from the CSL style repository at https://github.com/citation-style-language/styles, and I would not want pandoc-citeproc to use a different, inofficial version.

If you want to patch your own copy, add `<text variable="note"  prefix=". "/>` right after `<text macro="access" prefix=". "/>`.

If you feel the official style file should be changed, bring this up on http://forums.zotero.org/11/.

**Comment by jgm** [comment]
+++ nickbart1980 [Oct 06 15 07:45 ]:
>   If you feel the official style file should be changed, bring this up on
>   [2]http://forums.zotero.org/11/.

Right.  I don't want to diverge from the official style, so
this issue can be closed here.

**Comment by MrLoh** [comment]
Great thanks
