### ISSUE TITLE
Issue with strip-periods

### ISSUE THREAD

**Issue by kit-lloyd** [jgm/pandoc-citeproc#185]
I am having a problem with csl working with pandoc-citeproc; specifically with **Ibid** and **above n** processing as required by the [Australian Guide to Legal Citation](http://www.law.unimelb.edu.au/mulr/aglc).

The command I am using is pandoc -s -S --latex-engine=xelatex --filter pandoc-citeproc -- -o test

.pdf test.md

The csl and bibliography are specified in the md documents YAML

[aglc.csl](https://www.zotero.org/styles/australian-guide-to-legal-citation) is from the Zotero style repository (modified to take out the bibliography and capitalise ibid)

The problem is that "Ibid" is output in the pdf and latex file as "Ibid.," rather than just "Ibid"

For some reason the "strip-periods" does not seem to work and also I do not know how to have the redundant "," removed.

Also I cannot seem to get 'Above n' working

CSL functions well everywhere else and Ibid and Above n work in other applications.

Any suggestions would be greatly appreciated.

This is the Ibid code:
``` xml
  <citation et-al-min="4" et-al-use-first="1">
      <layout suffix="." delimiter="; ">
        <choose>
          <if position="ibid-with-locator">
            <text term="ibid" strip-periods="true"
  text-case="capitalize-first"/>
            <group delimiter=" ">
              <text variable="locator" strip-periods="true"/>
            </group>
          </if>
          <else-if position="ibid">
            <text term="ibid" strip-periods="true"
  text-case="capitalize-first"/>
          </else-if>
          <else-if position="subsequent">
```
as for above n ... it does not get inserted (the rest of the processing work fine, such as stripping the authors name) ... but above n and the locator are omitted.

Here is the above n code ...
``` xml
  <else-if position="subsequent">
            <choose>
              <if type="legal_case bill legislation manuscript"
  match="any">
                <!--don't use short form and above note for legal
  citations -->
                <group delimiter=" ">
                  <group delimiter=", ">
                    <text macro="author-note"/>
                    <choose>
                      <if match="any" variable="title-short">
                        <text macro="title-short"/>
                      </if>
                      <else>
                        <text macro="title"/>
                      </else>
                    </choose>
                  </group>
                  <!-- we could work with title-short here-->
                  <group delimiter=" ">
                    <text macro="date-parenthesis"/>
                    <text macro="article-case-info"/>
                    <text macro="book-container"/>
                    <text macro="publisher"/>
                  </group>
                </group>
                <text macro="manuscript-catchall" prefix=", "/>
                <text macro="date-news" prefix=", "/>
                <group delimiter=", " prefix=" ">
                  <text macro="looseleaf"/>
                  <text macro="page-first"/>
                  <text variable="locator"/>
                </group>
              </if>
              <else>
                <group delimiter=", ">
                  <text macro="author-short"/>
                  <choose>
                    <if disambiguate="true">
                      <text macro="title-short"/>
                    </if>
                  </choose>
                  <text variable="first-reference-note-number"
  prefix="above n "/>
                  <text variable="locator"/>
                </group>
              </else>
            </choose>
```

**Comment by jgm** [comment]
Can you provide test.md so I can test?

**Comment by kit-lloyd** [comment]
Hi John,

Sorry I didn’t know how to upload to GitHub …. here they are:



Kit Lloyd

**Comment by jgm** [comment]
>  here they are:

Where?

**Comment by kit-lloyd** [comment]
[aglc.csl](https://www.dropbox.com/s/tg5pt768u6o6exi/aglc.csl?dl=0)

[pandocupdate.json](https://www.dropbox.com/s/t5sr7vx5jmnzmj7/pandocupdate.json?dl=0)

[test.md](https://www.dropbox.com/s/whe4q65gpcvxjhd/test.md?dl=0)

[test.pdf](https://www.dropbox.com/s/haimm7320iu4xbn/test.pdf?dl=0)

**Comment by jgm** [comment]
Note to self. I can confirm from trace output that we're getting
```
      , Output
          [ OStr "ibid." emptyFormatting { stripPeriods = True } ]
          emptyFormatting
```
at an intermediate step of processing (`citeproc:collapsed`).  But in `cits_map`, we just have
```
    , Formatted { unFormatted = [ Str "ibid." , Note [ Para [] ] ] }
```

**Comment by jgm** [comment]
For the first-reference-note issue, see #31.
