### ISSUE TITLE
Error running filter pandoc-citeproc

### ISSUE THREAD

**Issue by verwinv** [jgm/pandoc-citeproc#186]
Installed pandoc using Homebrew, I'm trying to configure the workflow davewpsmith describes here: https://davepwsmith.github.io/academic-scrivener-howto/

Upon calling the pandoc conversion, I receive the following error:

> pandoc-citeproc: key "t" not present
> pandoc: Error running filter pandoc-citeproc

Could you indicate what action I should undertake to resolve this? Advice much appreciated!

**Comment by jgm** [comment]
I'd ask davewpsmith about this, since it's his filter.

+++ Erwin Verbruggen [Oct 28 15 14:16 ]:

**Comment by davepwsmith** [comment]
Not a pandoc filter I'm afraid just a howto -- the command which I recommend is the following
```
pandoc -s -S --normalize --bibliography \
~/.pandoc/YOUR_BIBLIOGRAPHY.bib \
--csl ~/.csl/YOUR_CITATION_STYLE.csl \
-f markdown -t docx \
-o MYPROJECT.docx MYPROJECT.txt
```
If there is no typo in the command (that would be my first guess) then it's back to you I'm afraid John.

**Comment by jgm** [comment]
Okay, @verwinv, to get anywhere we'd need to know (a) your pandoc version, (b) the exact command line you use, (c) the filter you're using.

**Comment by verwinv** [comment]
Hi both, thanks for chiming in. I've tried David's command again without the line breaks without luck.
(a) pandoc version 1.12.0.2
(b) the command line I typed in:
```
pandoc -s -S --normalize --bibliography ~/_zotero/mylibrary.bib --csl ~/.csl/modern-language-association-with-url.csl -f markdown -t docx -o eusxl-d54_strategic-agenda-2.docx eusxl-d54_strategic-agenda-2.txt
```
(c) as far as I understand there's no filter used here, only the input file. do correct me if I'm wrong and where I could check this.

**Comment by jgm** [comment]
You're using a very old version of pandoc.  Because the json
serialization method changed, older versions of pandoc won't
work with newer versions of pandoc-citeproc.

I'd recommend using the binary packages we supply, which
include versions of pandoc and pandoc-citeproc that work well
together.

+++ Erwin Verbruggen [Oct 30 15 03:34 ]:

**Comment by verwinv** [comment]
Dear mr. MacFarlane, much thanks - turns out I had installed a second version with the Homebrew package, but the original installation had indeed not been updated in quite a while. I am now running up against the issue referred to here: https://groups.google.com/forum/#!msg/pandoc-discuss/P7QmLE0u2S8/IYZKVqhZU-wJ but will dig into it further and start a new issue should I not be able to resolve it. Kind regards.

**Comment by davepwsmith** [comment]
Sounds like you need to make sure you're running the most up to date versions of pandoc and pandoc-citeproc before you report any errors really!

On 1 November 2015 16:37:55 GMT+00:00, Erwin Verbruggen <notifications@github.com> wrote:
>Dear mr. MacFarlane, much thanks - turns out I had installed a second
>version with the Homebrew package, but the original installation had
>indeed not been updated in quite a while. I am now running up against
>the issue referred to here:
>https://groups.google.com/forum/#!msg/pandoc-discuss/P7QmLE0u2S8/IYZKVqhZU-wJ
>but will dig into it further and start a new issue should I not be able
>to resolve it. Kind regards.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jgm/pandoc-citeproc/issues/186#issuecomment-152842467

--
https://keybase.io/davidsmith
--
Sent from my phone. Please excuse my brevity.

**Comment by verwinv** [comment]
Dear Dave, I understand as much. I had checked and updated the Brew version of Pandoc I installed but wasn't aware of the original version that was still running on my machine. Apologies for any inconvenience caused. Will in the future make sure to ask for help on the pandoc-discuss list instead of posting them here.
