### ISSUE TITLE
Request for a binary release

### ISSUE THREAD

**Issue by anntzer** [jgm/pandoc-citeproc#193]
I would like to request a binary, standalone release, perhaps, like for pandoc itself, as a deb package.
Thanks in advance.

**Comment by jgm** [comment]
The pandoc deb installs both pandoc and pandoc-citeproc.

+++ Antony Lee [Nov 15 15 22:32 ]:

**Comment by anntzer** [comment]
My apologies, I got confused by the (Arch) Linux package I'm using.
