### ISSUE TITLE
warning "reference with no printed form" should include citation key

### ISSUE THREAD

**Issue by tolot27** [jgm/pandoc-citeproc#195]
The warning "pandoc-citeproc: reference with no printed form" should include the citation key for trace back. Otherwise, it is hardly possible to find the causing citation key.

Here I assume that the above warning means that a citation referenced in the document is not found in the bibliographic file.

**Comment by tolot27** [comment]
Okay, there is a pull request already availabe (#165) but fails to build. I'll try to create a minimal demo.

**Comment by tolot27** [comment]
A minimal example to reproduce the warning is using an empty bib file and any reference key.

```Markdown
# reference with no printed form

Cited by [@Nobody0001].
```

`pandoc -o out\noprintedform.pdf --bibliography=empty.bib --csl=binfo.csl noprintedform.md`

But in this case, "pandoc-citeproc: reference @Nobody0001 not found" should be reported and not "no printed form".

BTW: What is meant by "no printed form"?

**Comment by jgm** [comment]
Pandoc and pandoc-citeproc versions, please?

I just tried with the latest and got "pandoc-citeproc:
reference Nobody0001 not found".

+++ Mathias Walter [Nov 24 15 23:47 ]:

**Comment by jgm** [comment]
ah, it depends on the csl file used.  With the default csl, I get "reference Nobody0001 not found", but with the `references.csl` from [the #165 example](https://github.com/katrinleinweber/pandoc-citeproc-unprinted-reference-demo/commits/master) I get the "no printed form" warning.  The author of #165 says it was a bug in her csl file, which may be the case for you as well.  Still, it's an odd and unexpected message, so I should try to get to the bottom of this.

**Comment by jgm** [comment]
notes to self:  there are two places where this "no output error" is produced:
Text.CSL.Eval line 56
Text.CSL.Proc.Collapse line 89

**Comment by tolot27** [comment]
With pandoc 1.14 I get no warning at all. With the latest msi release (1.5.2) I get the "reference with no printed form" warning. I'm using the [BMC Bioinformatics](https://www.zotero.org/styles/bmc-bioinformatics) style. With [PLOS ONE](https://www.zotero.org/styles/plos-one) style I get the same warning and likely with many other CSLs.

**Comment by jgm** [comment]
Here's a small json file to test with:

195.json
```
[{"unMeta":{"references":{"t":"MetaList","c":[]},"csl":{"t":"MetaInlines","c":[{"t":"Str","c":"plos.csl"}]}}},[{"t":"Para","c":[{"t":"Cite","c":[[{"citationSuffix":[],"citationNoteNum":0,"citationMode":{"t":"NormalCitation","c":[]},"citationPrefix":[],"citationId":"unknown","citationHash":0}],[{"t":"Str","c":"[@unknown]"}]]}]}]]
```
To test, put plos.csl in working directory and:
```
pandoc -F pandoc-citeproc 195.json -t plain
```

**Comment by jgm** [comment]
Debug output for the case above:
```
=== citeproc:citG
[ CG
    []
    emptyFormatting { prefix = "[" , suffix = "]" }
    ","
    [ ( Cite
          { citeId = "unknown"
          , citePrefix = Formatted { unFormatted = [] }
          , citeSuffix = Formatted { unFormatted = [] }
          , citeLabel = ""
          , citeLocator = ""
          , citeNoteNumber = "0"
          , citePosition = "first"
          , nearNote = False
          , authorInText = False
          , suppressAuthor = False
          , citeHash = 1
          }
      , Output [ OErr NoOutput ] emptyFormatting
      )
    ]
]

=== citeproc:collapsed
[ CG
    []
    emptyFormatting { prefix = "[" , suffix = "]" }
    ","
    [ ( Cite
          { citeId = "unknown"
          , citePrefix = Formatted { unFormatted = [] }
          , citeSuffix = Formatted { unFormatted = [] }
          , citeLabel = ""
          , citeLocator = ""
          , citeNoteNumber = "0"
          , citePosition = "first"
          , nearNote = False
          , authorInText = False
          , suppressAuthor = False
          , citeHash = 1
          }
      , Output [ OErr NoOutput ] emptyFormatting
      )
    ]
]

=== cits_map
fromList
  [ ( [ Citation
          { citationId = "unknown"
          , citationPrefix = []
          , citationSuffix = []
          , citationMode = NormalCitation
          , citationNoteNum = 0
          , citationHash = 1
          }
      ]
    , Formatted
        { unFormatted =
            [ Str "["
            , Span
                ( "" , [ "citeproc-no-output" ] , [] ) [ Strong [ Str "???" ] ]
            , Str "]"
            ]
        }
    )
  ]

pandoc-citeproc: reference with no printed form
=== citeproc:after procBiblio
[]

[???]
```
