### ISSUE TITLE
Missing documentation on hackage

### ISSUE THREAD

**Issue by mpickering** [jgm/pandoc-citeproc#196]
There is currently no documentation for the package for the latest version on hackage.

https://hackage.haskell.org/package/pandoc-citeproc

**Comment by jgm** [comment]
+++ Matthew Pickering [Nov 26 15 12:30 ]:
>   There is currently no documentation for the package for the latest
>   version on hackage.
>
>   [1]https://hackage.haskell.org/package/pandoc-citeproc

Right, no API documentation anyway.

The build log should be revealing:
https://hackage.haskell.org/package/pandoc-citeproc-0.8.1.3/reports/1

But I'm not sure what to make of it.

**Comment by mpickering** [comment]
I usually use a script like this one to upload the docs if you want to do it manually.

https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh

**Comment by jgm** [comment]
Oh, nice.  Done.
