### ISSUE TITLE
First citation set by nocite

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#197]
The `nocite` variable appears to be understood as the first instance of a citation, meaning that it any items included here will be given a short note, and potentially referred to as 'ibid.', even though the reference does not appear earlier in the text.

For example (pandoc 1.15.2.1, pandoc-citeproc 0.8.1.1):

```shell
pandoc -F pandoc-citeproc << EOT

---
csl: chicago-fullnote-bibliography.csl
nocite: "@test"
references:
- publisher-place: Oxford
  id: test
  issued:
    date-parts:
    - - 1989
  title: Test
  type: book
  publisher: Clarendon Press
  editor:
  - family: Abelard
    given: Peter
...

This is a test [@test].

EOT
```

The result is as follows:

```html
<p>This is a test.<span class="citation"><a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></span></p>
<div id="refs" class="references">
<div id="ref-test">
<p>Abelard, Peter, ed. <em>Test 1</em>. Oxford: Clarendon Press, 1989.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Ibid. <a href="#fnref1">↩</a></p></li>
</ol>
</div>
```

**Comment by jgm** [comment]
Probably the solution is (in Text.CSL.Pandoc) to replace

```
      grps          = query getCitation $ Pandoc m3 b2
```

with several steps:  first run this on Pandoc m3' b2 where m3' is m3 minus the `nocites` and `nocites-wildcard` fields; then run it on just the contents of the `nocites` and `nocites-wildcard` fields, so that these come at the end.
