### ISSUE TITLE
link-citations can only be set through YAML metadata

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#198]
The `link-citations` variable appears to be set only if it is included in the document's YAML metadata, and is ignored if set through the terminal.

For example, this works (pandoc 1.15.2.1, pandoc-citeproc 0.8.1.1):

```shell
pandoc -F pandoc-citeproc << EOT

---
link-citations: true
references:
- id: test
  issued:
    date-parts:
    - - 1989
...

[@test].

EOT
```

Result:

```html
<p>This is a test <span class="citation">(<a href="#ref-test">1989</a>)</span>.</p>
<div id="refs" class="references">
<div id="ref-test">
<p>1989.</p>
</div>
</div>
```

But this does not:

```shell
pandoc -F pandoc-citeproc -V link-citations=true << EOT

---
references:
- id: test
  issued:
    date-parts:
    - - 1989
...

[@test].

EOT
```

Result:

```html
<p><span class="citation">(1989)</span>.</p>
<div id="refs" class="references">
<div id="ref-test">
<p>1989.</p>
</div>
</div>
```

**Comment by jgm** [comment]
Use --metadata link-citations=true

-V doesn't change the metadata; it just sets a variable,
which only affects template rendering.

So, not a bug, I think.

+++ Andrew Dunning [Nov 27 15 11:16 ]:

**Comment by adunning** [comment]
I did not know about that; thanks. Worth mentioning in the manpage?

**Comment by jgm** [comment]
Well, the man page already says "pandoc-citeproc will look
for the following *metadata fields* in the input..."

+++ Andrew Dunning [Nov 27 15 11:54 ]:
