### ISSUE TITLE
Parsing book subtitles

### ISSUE THREAD

**Issue by mendelkranz** [jgm/pandoc-citeproc#199]
Hi,

I'm having an issue with book subtitles. I'm not sure if the problem is in the way they are handled in the bibtex file I'm working in or with pandoc-citeproc itself. 

Basically, when I export my bibtex file from Papers (the citation manager I use), the title of the book appears in the field 'title,' and the subtitle appears in 'series' (example below). The problem is that when I convert everything using pandoc, the subtitle doesn't get italicized as part of the book name. So for example the book *Freud, Jews, and other Germans: Masters and Victims in Modernist Culture* appears only as _Freud, Jews, and other Germans:_ Masters and Victims in Modernist Culture. 

Is there anything I can do to prevent this? or to fix it?

Thanks!

Example of bibtex entry:

```
@book{Gay:1978tq,
author = {Gay, Peter},
title = {{Freud, Jews, and other Germans}},
publisher = {New York : Oxford University Press},
year = {1978},
series = {Masters and Victims in Modernist Culture}
}
```

**Comment by jgm** [comment]
What csl are you using?  The default is chicago-author-date.csl,
so that's what you're getting if you don't specify one.
You could try customizing it, changing

   <text variable="collection-title" text-case="title"/>

to

   <text variable="collection-title" text-case="title" font-style="italic"/>

both places where it occurs.

+++ Mendel Kranz [Dec 01 15 20:06 ]:

**Comment by mendelkranz** [comment]
I'm actually using chicago-full-note-bibliography but that seems to do the trick. (As an aside, I'm not sure I actually know the difference between the two.) 

Is this what everyone has to do to ensure subtitles of books are italicized? Or is my setup somehow different?
Also, I noticed I'm getting a dot (.) in between title and subtitle as well as right after the subtitle. Is there any reason for this?
For example, the above citation is rendered as:

Gay, Peter. _Freud, Jews, and other Germans. Masters and Victims in Modernist Culture._ New York: Oxford University Press, 1978.

**Comment by jgm** [comment]
+++ Mendel Kranz [Dec 01 15 20:38 ]:
>   I'm actually using chicago-full-note-bibliography but that seems to do
>   the trick. (As an aside, I'm not sure I actually know the difference
>   between the two.)
>
>   Is this what everyone has to do to ensure subtitles of books are
>   italicized? Or is my setup somehow different?

It seems to me that Papers is doing something pretty strange
in mapping subtitle to series.  Not all subtitles are series
titles (some are).  BibLaTeX has a 'subtitle' field, why
doesn't Papers use that?

>   Also, I noticed I'm getting a dot (.) in between title and subtitle as
>   well as right after the subtitle. Is there any reason for this?
>   For example, the above citation is rendered as:
>
>   Gay, Peter. Freud, Jews, and other Germans. Masters and Victims in
>   Modernist Culture. New York: Oxford University Press, 1978.

See above.  This is appropriate for series.
Not so much for subtitle.

**Comment by mendelkranz** [comment]
> It seems to me that Papers is doing something pretty strange
in mapping subtitle to series.  Not all subtitles are series
titles (some are).  BibLaTeX has a 'subtitle' field, why
doesn't Papers use that?

Weird. I've submitted a support request with them, hopefully they'll have an answer for me.
Thanks for the help.
