### ISSUE TITLE
problems finding locales after last update

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc-citeproc#200]
My pandoc-citeproc is version 0.8.1.3, pandoc is version 1.15.2.1. I am seeing a new issue:

~~~~
+./topdf-fb06.sh:12> pandoc --bibliography citace.yaml --csl iso690-numeric-cs.csl --toc --smart --self-contained -V 'lang=czech' -f markdown -t html5 --mathml -o fb06.html fb06.md
pandoc-citeproc: /home/wilx/.cabal/share/x86_64-linux-ghc-7.8.4/pandoc-citeproc-0.8.1.3/locales/locales-cz.xml: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
~~~~

As you can see, it looks for `locales-cz.xml`. I took a look at the directory and it contains `locales-cs-CZ.xml` instead. I think this started after I updated `pandoc` from 1.15 and `pandoc-citeproc` at the same time.

The top the `fb06.md` starts with this YAML:

~~~~{.yaml}
---
title: Odpověď na FB post 06
author: Václav Haisman
lang: czech
geometry:
    - a4paper
    - margin=2cm
header: Odpověď na FB post 06
...
~~~~

The rest is just normal Markdown with `[@foo]` citations.

My `locale` shows the following. I have a mixed English and Czech locale:

~~~~{.sh}
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=cs_CZ.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_ALL=
~~~~

**Comment by jgm** [comment]
Try

lang: cs-CZ

in your YAML metadata.  We switched over to consistent
identifiers for languages in recent versions (see pandoc
changelog).

**Comment by wilx** [comment]
Thank you. I did not notice. Closing this.
