### ISSUE TITLE
Is it possible to get ConTeXt support?

### ISSUE THREAD

**Issue by Denubis** [jgm/pandoc-citeproc#202]
running pandoc --natbib (etc..) with -t ConTeXt produces nonTeXified output.
Running the above with -t LaTeX produces TeXified output.

The patterns are basically the same (as specified in: http://wiki.contextgarden.net/Bibliography_mkiv)

If you can point out where in the code these patterns are specified (I, unfortunately, don't code in haskell), I'm happy to do replacing and creation of appropriate unit tests.

**Comment by jgm** [comment]
So, are you asking for something like the --natbib or
--biblatex options for pandoc, but specific to ConTeXt?  This
would be a change in pandoc, not pandoc-citeproc.
(With these options, pandoc just avoids using
pandoc-citeproc altogether.)

See the functions citationsToNatbib and citationsToBiblatex
in src/Text/Pandoc/Writers/LaTeX.hs in pandoc.  We'd need
something similar in the ConTeXt writer.

https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs#L981

+++ Brian Ballsun-Stanton [Dec 11 15 22:09 ]:

**Comment by Denubis** [comment]
Ah, I wasn't aware that those flags... fought. No, I quite like the pandoc-citedoc filter. It does exactly what I expect it to do. (enable citation detection and allow me to replace with ConTeXt versions)

In any event, I've started sketching my own solution in (sorry) python. Happy to elaborate for all conditions you'd want it to cover such that all you need to do is integrate in.

https://github.com/Denubis/MarkdownContextTests (specifically: https://github.com/Denubis/MarkdownContextTests/blob/master/contextBibliography.py and https://github.com/Denubis/MarkdownContextTests/blob/master/env_unittest.tex#L125-L146 )

Let me know if there are various test documents that I should match to hit all of the various permutations.

**Comment by jgm** [comment]
+++ Brian Ballsun-Stanton [Dec 14 15 18:09 ]:
>   Ah, I wasn't aware that those flags... fought. No, I quite like the
>   pandoc-citedoc filter. It does exactly what I expect it to do. (enable
>   citation detection and allow me to replace with ConTeXt versions)

Then I'm confused -- can you say exactly what you think is wrong
with the current pandoc + pandoc-citeproc output in ConTeXt?

**Comment by Denubis** [comment]
The current pandoc-citedoc output doesn't support the ConText bibliographic module (I think.). It just does raw output with normal text. (Which means all the extras of the bibliographic module don't work.) ... (I think? I might have been misusing it. If you assert that the same \cite, \completepublications[criterium=text] stuff appears, I'll retest.)

**Comment by jgm** [comment]
pandoc-citeproc doesn't output ConTeXt (or LaTeX) commands
like \cite, because these interact with ConTeXt's (or
LaTeX's) own system for generating citations.
pandoc-citeproc is generating the citations on its own,
so we definitely don't want to use these.

See the README on the --natbib and --biblatex options, which
allow you to bypass pandoc-citeproc when you're using LaTeX,
and use the native natbib or biblatex citation commands
instead.

If you want something similar for ConTeXt, that would be
an enhancement request for pandoc -- since in that case you
wouldn't use pandoc-citeproc at all.


+++ Brian Ballsun-Stanton [Dec 14 15 19:03 ]:
