### ISSUE TITLE
Support m./mm. locator to cite measure numbers from musical scores

### ISSUE THREAD

**Issue by hftf** [jgm/pandoc-citeproc#203]
Self explanatory.

Rehearsal marks/letters/numbers could be useful as well.

**Comment by jgm** [comment]
This isn't one of the officially defined locators in CSL:
https://github.com/citation-style-language/documentation/blob/master/specification.txt#L2392

Perhaps you should make your request to the people who
maintain the CSL spec?  We try to follow that.

+++ Ophir Lifshitz [Dec 17 15 09:41 ]:

**Comment by jgm** [comment]
I'll close this for now. If a change is made in CSL, open a new issue here and we'll support it.
