### ISSUE TITLE
'openBinaryFile does not exist' on OSX 10.11.2 with biblatex

### ISSUE THREAD

**Issue by zkamvar** [jgm/pandoc-citeproc#204]
Hi, I just updated pandoc and noticed that my documents with biblatex were failing with this error:

```
pandoc-citeproc: /Users/jgm/src/pandoc/.stack-work/install/x86_64-osx/lts-3.20/7.10.2/share/x86_64-osx-ghc-7.10.2/pandoc-citeproc-0.9/chicago-author-date.csl: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

I've created a minimum working example for this error here: https://gist.github.com/zkamvar/717566dc405088564faa

My pandoc version:

```
pandoc 1.16
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
```

**Comment by jgm** [comment]
Try the new OS X package I put up this morning - there was a problem with the old one.

**Comment by zkamvar** [comment]
This worked. 
Thanks!
