### ISSUE TITLE
Request: case-insensitive citation abbreviations

### ISSUE THREAD

**Issue by mickley** [jgm/pandoc-citeproc#206]
For example, if my abbreviations.json file contains

```
"American Journal of Botany":"Amer. J. Bot.",
```

then American Journal Of Botany or american journal of botany will not be matched and abbreviated.

I think it makes sense to use a case-insensitive match here.  No journal title is differentiated by case, and there are many scenarios or errors where the correct case might not be used in both the abbreviations file and the references file.

**Comment by jgm** [comment]
I agree, this makes sense.
