### ISSUE TITLE
Allow bibliography to follow heading with id of "refs"

### ISSUE THREAD

**Issue by Jmuccigr** [jgm/pandoc-citeproc#210]
(Follow-up to conversation [in the group](https://groups.google.com/d/msg/pandoc-discuss/wDKDpOKYEjU/uaDN2gLVAAAJ).)

Currently the bibliography can be moved from its default location at the end of a file, to somewhere else by the inclusion of a div with an id element of `refs`.

Since it's possible to give an id to a heading and since bibs are often introduced by headings, expand the insertion rule to include any heading with such an id element. This would avoid the use of raw html inside a markdown document and also leverage pandoc's ability to insert such id elements into headings.

So, this markdown heading would have a bibliography inserted after it:

`# List of Readings {#refs}`

EDIT: To be super clear, the heading level wouldn't matter; so even, e.g., H2 or H3 could signal the start of the bibliography.

**Comment by Jmuccigr** [comment]
Thoughts on this?

**Comment by jgm** [comment]
I like the idea, I just haven't had time to work on it.

**Comment by Jmuccigr** [comment]
Great.  Thanks for responding.

**Comment by stfl** [comment]
any progress on that?
I am trying to make pandoc-citeproc work with a complex latex template from my institute.. So an option like that would be highly appreciated...

**Comment by oli-obk** [comment]
ping @jgm 

could you post some info that could guide a motivated user towards implementing this?

**Comment by jgm** [comment]
You'd want to look at insertRefs in src/Text/CSL/Pandoc.hs.
The changes needed aren't completely straightforward; let me
know if you get stuck.

+++ Oliver Schneider [Jul 20 17 08:20 ]:
