### ISSUE TITLE
Author field rendering as "---------"

### ISSUE THREAD

**Issue by willwhitney** [jgm/pandoc-citeproc#211]
I have a bibtex entry:

```latex
@article{zaremba2015reinforcement,
  title={Reinforcement Learning Neural Turing Machines},
  author={Zaremba, Wojciech and Sutskever, Ilya},
  journal={arXiv preprint arXiv:1505.00521},
  year={2015}
}
```

and it is currently being rendered to

```latex
\hypertarget{ref-zaremba2015reinforcement}{}
---------. 2015. ``Reinforcement Learning Neural Turing Machines.''
\emph{ArXiv Preprint ArXiv:1505.00521}.
```

Other bibtex entries (from the same .bib file) are rendering correctly, e.g. 

```latex
@article{zaremba2014learning,
  title={Learning to execute},
  author={Zaremba, Wojciech and Sutskever, Ilya},
  journal={arXiv preprint arXiv:1410.4615},
  year={2014}
}
```

renders to 

```latex
\hypertarget{ref-zaremba2014learning}{}
Zaremba, Wojciech, and Ilya Sutskever. 2014. ``Learning to Execute.''
\emph{ArXiv Preprint ArXiv:1410.4615}.
```

**Comment by jgm** [comment]
That's what the default style (chicago-author-date.csl)
says to do when there are repeated authors.  You can use
a different csl style or modify that one to change this
behavior.

+++ Will Whitney [Jan 25 16 21:59 ]:

**Comment by willwhitney** [comment]
Oh wow, good catch! I had no idea that was the default — exactly repeated sets of authors come up rarely for me.

Thanks for the help!
