### ISSUE TITLE
Tags no longer parsed

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#212]
This seems to be a regression, but not sure when it happened. With pandoc-citeproc 0.9 and pandoc 1.16.0.2, tags in the citation data are not parsed:

```markdown
pandoc -F pandoc-citeproc -t latex << EOT
---
references:
- id: 'test'
  title: "A <i>test</i> <sc>title</sc>"
...

@test

EOT
```

Output:

```latex
(``A Test Title,'' n.d.)

\hypertarget{refs}{}
\hypertarget{ref-test}{}
``A Test Title.'' n.d.
```

**Comment by nickbart1980** [comment]
When using a CSL *YAML* database, pandoc-citeproc only parses pandoc Markdown.

From <http://pandoc.org/README.html>:

> In-field markup: In BibTeX and BibLaTeX databases, pandoc-citeproc parses a subset of LaTeX markup; in CSL YAML databases, pandoc Markdown; and in CSL JSON databases, an HTML-like markup [specs: <http://docs.citationstyles.org/en/1.0/release-notes.html#rich-text-markup-within-fields>]

pandoc-citeproc does however parse, in pandoc Markdown, `<span style="font-variant:small-caps;">`…`</span>`.

**Comment by jgm** [comment]
@nickbart1980 is correct.

**Comment by adunning** [comment]
That explains it; I had switched from the CSL JSON to the YAML option in Zotero BetterBibTeX, which doesn't presently convert the tags. Thank you!
