### ISSUE TITLE
pandoc-citeproc -y / -j output: ‘motion-picture’ rather than ‘motion_picture’

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#214]
$ cat video.bib 
    @video{x1,title={blah}}
    @movie{x2,title={blah}}

    $ pandoc-citeproc -y video.bib 
    ---
    references:
    - id: x1
      type: motion-picture
      title: Blah
    
    - id: x2
      type: motion-picture
      title: Blah
    ...
    
    $ pandoc-citeproc -j video.bib 
    [
      {
        "id": "x1",
        "title": "Blah",
        "type": "motion-picture"
      },
      {
        "id": "x2",
        "title": "Blah",
        "type": "motion-picture"
      }
    ]

`motion-picture` is not a valid CSL entry type, and the resulting JSON cannot be imported into Zotero.

Interestingly enough, `echo @x1 | pandoc -F pandoc-citeproc --biblio video.bib` renders a citation, as expected. I also remember that we did have a problem with the hyphen in ‘motion-picture’ before; I thought it had been fixed, but apparently that fix did not cover `pandoc-citeproc -y` / `-j` output …

**Comment by jgm** [comment]
See
https://github.com/jgm/pandoc-citeproc/blob/master/src/Text/CSL/Reference.hs#L258

I guess we never did "clean up this mess."
