### ISSUE TITLE
Won't install in sandbox

### ISSUE THREAD

**Issue by eamsden** [jgm/pandoc-citeproc#216]
This package fails to find dependencies already discovered by the solver and installed. This happens both when trying to install the package directly and as a dependency of hakyll.

    $ uname -a
    Linux <hostname> 4.2.0-30-generic #35-Ubuntu SMP Fri Feb 19 13:52:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.10.3
    $ cabal --version
    cabal-install version 1.23.0.0
    compiled using version 1.23.1.0 of the Cabal library
    $ cabal sandbox init
    $ cabal install pandoc-citeproc
    Configuring pandoc-citeproc-0.9...
    setup: At least the following dependencies are missing:
    process -any, temporary >=1.1
    $ cabal sandbox hc-pkg list process
    process-1.2.3.0
    $ cabal sandbox hc-pkg list temporary
    temporary-1.2.0.4

**Comment by jgm** [comment]
Strange.  Just tried it with cabal 1.22.6.0 in a fresh
sandbox, no problems.  Perhaps a cabal issue?
(You seem to be using an unrelesed version of cabal.)

+++ Edward Amsden [Feb 28 16 20:17 ]:
>   This package fails to find dependencies already discovered by the
>   solver and installed. This happens both when trying to install the
>   package directly and as a dependency of hakyll.
i

**Comment by eamsden** [comment]
It seems I had installed the git-tracking version of the cabal package from the Ubuntu PPA. Trying it with cabal 1.22.6.0 also works for me. Closing and will file as a regression in cabal-install's HEAD.
