### ISSUE TITLE
Custom concatenation separator for title and subtitle

### ISSUE THREAD

**Issue by scoavoux** [jgm/pandoc-citeproc#217]
If I understand correctly, when reading a bibtex/biblatex file, the concatenation of the title and subtitle fields is done by citeproc.

With biblatex, there is a way to change the separator:

``` latex
\renewcommand{\subtitlepunct}{\adddot\addspace}
```

I don't know much of haskell, but it looks like this line of https://github.com/jgm/pandoc-citeproc/blob/master/src/Text/CSL/Input/Bibtex.hs is responsible for the concatenation:

``` haskell
 , title = concatWith '.' [
                concatWith ':' [title', subtitle']
              , titleaddon' ]
```

Would it be possible and suitable to change the `':'` with a variable that we could set in the yaml front matter? It would be good for languages other than English. In French, titles and subtitles are usually separated by a dot.

**Comment by jgm** [comment]
It looks as if this has been discussed in the CSL forum:
https://forums.zotero.org/discussion/8077/separate-fields-for-title-and-subtitle
If CSL had a separate `subtitle` field, then all of this could be handled at the style level.

**Comment by demai** [comment]
Yes, it's been discussed there, and the best solution would be if CSL had a subtitle field. But, honestly, I doubt that we will have this any time soon. In the meantime, making title subtitle concatenation customizable would be incredibly useful. (In German, titles and subtitles are also usually separated by a period.)

**Comment by denismaier** [comment]
There's been some progress. @fbennett added support for this in citeproc-js. See  https://discourse.citationstyles.org/t/handling-main-sub-title-splits-citeproc-js/1563

It still not in the specs though.
