### ISSUE TITLE
Bibliography/References automatic heading option

### ISSUE THREAD

**Issue by stevebarratt123** [jgm/pandoc-citeproc#218]
As many users would probably like to include a heading before their references section eg "Bibliography" or "References", it would be very useful if this was available as an automatic addition controlled by a flagged option at the time of build/conversion.

If I wish to work on a document in markdown and have a bibliography section heading when I make occasional preview builds, I must to work on my document the whole time with an empty line and my `# Bibliography` line below the region in my text editor where I am doing the actual text entry.

PS. Thanks for the fabulous work!

**Comment by Jmuccigr** [comment]
One difficulty here is that there will be a variety of desired text (Bibligoraphy, References, Works Cited, etc), language, and format (#, ##, other).

**Comment by jgm** [comment]
+++ stevebarratt123 [Mar 09 16 03:51 ]:
>   As many users would probably like to include a heading before their
>   references section eg "Bibliography" or "References", it would be very
>   useful if this was available as an automatic addition controlled by a
>   flagged option at the time of build/conversion.

It is available.

See the man page under `reference-section-title` (which you
can put in metadata).

**Comment by jgm** [comment]
Well, you can  specify the exact text you want using the
metadata field I mentioned.

If you want more control (e.g. over the exact header style),
then just do it manually.  Put the header in your document,
and use the specially marked div to position your
bibliography where you want it.  This gives you all the
flexibility you hould need.

+++ John Muccigrosso [Mar 09 16 06:35 ]:

**Comment by stevebarratt123** [comment]
I thought that I had checked through the man entries - clearly not. Apologies!

**Comment by Jmuccigr** [comment]
@jgm, yes, I had forgotten that field.

In this context, I am reminded also of my request to allow the designation to belong to any header, instead of just a special div: #210.
