### ISSUE TITLE
Generate better error message if .csl file is invalid

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#219]
It would be helpful if pandoc-citeproc could check whether .csl files are valid, and return a more meaningful error message if they are not.

Users might not be aware that certain files with a `.csl` extension are not valid .csl files.

https://github.com/citation-style-language/styles/blob/master/*.csl files, e.g., are in fact .html (= github landing pages) rather than valid .csl files.

See discussion at https://groups.google.com/forum/#!topic/pandoc-discuss/IBf4wGbbFhk.

**Comment by jgm** [comment]
Solution here is to use parseLBS instead of parseLBS_ from xml-conduit.
This will generate an Either value and will allow us to better handle errors.
This requires some API changes.  I think it's worth it though.
