### ISSUE TITLE
Dependency conflict when installing with cabal

### ISSUE THREAD

**Issue by jjatria** [jgm/pandoc-citeproc#221]
I've had no problems installing pandoc with cabal, to be able to use the Perl modules for writing filters (which have been [updated to match the changes in pandoc 1.16](https://github.com/nichtich/Pandoc-Elements/issues/11)). However, when trying to use `pandoc-citeproc` I run into the same problem that has been [reported in the mailing list](http://comments.gmane.org/gmane.text.pandoc/14161) with `SoftBreak`.

When I try to install the latest version of `pandoc-citeproc` (0.9.1.1) or the version recommended in that email post (0.9), cabal refuses on the ground of dependency conflicts:

    user@linux:~$ cabal install pandoc-citeproc
    Resolving dependencies...
    cabal: Could not resolve dependencies:
    trying: pandoc-citeproc-0.9.1.1 (user goal)
    trying: temporary-1.2.0.4/installed-8ee... (dependency of
    pandoc-citeproc-0.9.1.1)
    trying: yaml-0.8.16/installed-c1d... (dependency of pandoc-citeproc-0.9.1.1)
    next goal: xml-conduit (dependency of pandoc-citeproc-0.9.1.1)
    rejecting: xml-conduit-1.3.4, 1.3.3.1, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.6,
    1.2.5.1, 1.2.5, 1.2.4, 1.2.3.3, 1.2.3.2, 1.2.3.1, 1.2.3, 1.2.2, 1.2.1.1
    (conflict: temporary => transformers==0.5.2.0/installed-00b..., xml-conduit =>
    transformers>=0.2 && <0.5)
    rejecting: xml-conduit-1.2.1, 1.2.0.3, 1.2.0.2, 1.2.0.1 (conflict: yaml =>
    conduit==1.2.6.4/installed-0ec..., xml-conduit => conduit>=1.0 && <1.2)
    rejecting: xml-conduit-1.2.0 (conflict: yaml =>
    conduit==1.2.6.4/installed-0ec..., xml-conduit => conduit>=1.0 && <1.1)
    rejecting: xml-conduit-1.1.0.9, 1.1.0.8, 1.1.0.7, 1.1.0.6, 1.1.0.5, 1.1.0.4,
    1.1.0.3, 1.1.0.2, 1.1.0.1, 1.1.0, 1.0.3.3, 1.0.3.2, 1.0.3.1, 1.0.3, 1.0.2.1,
    1.0.2, 1.0.1.1, 1.0.1, 1.0.0, 0.7.0.3, 0.7.0.2, 0.7.0.1, 0.7.0, 0.6.1, 0.6.0,
    0.5.4, 0.5.3.1, 0.5.3, 0.5.2, 0.5.1.2, 0.5.1.1, 0.5.1, 0.5.0.1, 0.5.0
    (conflict: pandoc-citeproc => xml-conduit>=1.2 && <1.4)
    Backjump limit reached (change with --max-backjumps).
    user@linux:~$

It is entirely possible that this is due to some error in my part, since I have a very tenuous understanding of how cabal and Haskell packages work, but how do I install 0.9.11?

**Comment by jgm** [comment]
This is known as "cabal hell."  You might try using stack
instead, but if you want to use cabal, it often works to
delete/backup your ~/.ghc directory (assuming you've got a
local installation) and start again.



+++ José Joaquín Atria [Mar 30 16 05:09 ]:

**Comment by jjatria** [comment]
Somehow just installing stack from apt was not good: it complained that GHC was 7.10.2 and it expected 7.10.3, and I found no way to install the correct version.

After a day or so of compiling (slow computer here), I managed to build GHC 7.10.3 from source. After that, stack worked well and I managed to install everything just fine.

Thanks!
