### ISSUE TITLE
Invalid UTF-8 character when lang is set to fr-FR

### ISSUE THREAD

**Issue by Phyks** [jgm/pandoc-citeproc#223]
Hi,

I am writing a document in French using Pandoc to convert my markdown document to PDF.

As I am writing in French, I am using `lang: fr-FR` in the YAML header to have `\usepackage[francais]{babel}` in my rendered file.

However, it fails with the bibliography generated by pandoc-citeproc.

Indeed, in my bibliography, I have lines such as
```
	pages = {1169--1174},
```
(dash is standard ASCII dash)

and the dashes get somehow converted to UTF-8 dashes (U+2011), which gives the following error when compiling:
```
! Package inputenc Error: Unicode char ‑ (U+2011)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1048 ... for the Advancement of Science: 1169‑

Try running pandoc with --latex-engine=xelatex.
pandoc: Error producing PDF
```

Thanks

**Comment by jgm** [comment]
pandoc-citeproc is cross-platform; it produces output that
should work with any format.  Keeping the `--` as it
is would only work with LaTeX.

I suppose we could have the LaTeX writer escape the en-dash
as `--`, and similarly with quotes and em-dashes, but I'm
not sure everyone would want this behavior.  Why not just
use --latex-engine=xelatex as suggested?

+++ Lucas Verney [Apr 22 16 07:23 ]:

**Comment by Phyks** [comment]
Ok for the reason, still I think it would be better if `pandoc-citeproc` could be used with LaTeX directly, without having to switch to xelatex.

Concerning the suggestion about xelatex, I am using:
```
header-includes:
    - \usepackage{mathtools}
```

in the header of my markdown file, which gives:
```
! Package mathspec Error: `amsmath' must be loaded earlier than `mathspec'.

See the mathspec package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.116 \RequirePackage{amsmath}
```
When running Pandoc using xelatex on the file.

I removed the header line, and still got another issue later:
```
! Improper alphabetic constant.
<to be read again> 
                   \varphi 
l.971 ...ta \varphi_X^2 + \varphi_Y^2 + C" \varphi
```

I have no issues compiling the file if I use standard LaTeX engine and disable the pandoc-citeproc filter.

P.S.: My issues with xelatex may not be pandoc-related, but rather xelatex-specific. But this option is not as straightforward as the warning message might say in my case.

**Comment by jgm** [comment]
Pandoc doesn't normally use unicode curly quotes for Quoted
inlines.  The issue is that pandoc-citeproc does localization.  The
quotation mark style is affected by the locale.  Many of the
quote mark styles don't even have LaTeX ligatures defined,
so we really need to use unicode characters rather than
Quoted inlines.

I suppose one could change the pandoc Quoted type to take
a more fine grained parameter than SingleQuoted or
DoubleQuoted, with the specific open and close quote
characters given.  This might be helpful for other reasons,
too.  And then the LaTeX writer could produce ascii
ligatures when possible.

However, this would be a big change, since it affects
pandoc-types and requires changes in virtually every
module in the pandoc ecosystem.  As I say, it might be
worth making for other reasons (allowing localization
of quote styles, see #2620).  Perhaps another issue
should be opened about this.

+++ Lucas Verney [Apr 26 16 08:32 ]:

**Comment by Phyks** [comment]
@jgm Ah, you mean the issue with xelatex is due to the `C"` text which is converted to `C“` when using pandoc-citeproc, and which gives the issue because `“` is not a valid constant name?

Is there an easy way to workaround at the moment?
Thanks!

**Comment by jgm** [comment]
No, you can see from the xelatex error message that the `"` is not made curly in the LaTeX source (pandoc wouldn't mess with quotes in math mode).  I wasn't giving you a solution to the xelatex issue, but see the last comment in http://tex.stackexchange.com/questions/64900/improper-alphabetic-constant which may help diagnose that.

**Comment by Phyks** [comment]
Ok, thanks. I got it working with `xelatex`, after removing my `mathtools` include, this does not seem to be Pandoc-related.

I am not sure whether this issue should stay open as it would be better if we could compile such texts using the plain LaTeX engine. At least it is non blocking if switching to xelatex. Feel free to close if you think it should not be fixed. :)

**Comment by Phyks** [comment]
By the way, I am just thinking about it, is there a specific reason for pandoc not to switch to xelatex engine automatically if available? I am tempted to do it in my own wrapper on top of pandoc, but fear to miss some major downside.

**Comment by jgm** [comment]
The main reason is that it's better (more efficient) for
people to find about the need to use xelatex and change
their build command, rather than having pandoc
unsuccessfully try pdflatex  every time they build
the document...

+++ Lucas Verney [May 01 16 11:50 ]:

**Comment by Phyks** [comment]
OK, thanks! :)
