### ISSUE TITLE
No way to hide referenced title in addition to author 

### ISSUE THREAD

**Issue by JonathanReeve** [jgm/pandoc-citeproc#225]
If I don't mention the author specifically in the text, I'll cite them like this: 

```
Some critics argue that foo is bar [@brown1999 23]. 
Output: Some critics argue that foo is bar (Brown 23). 
```

If I mention the author's name, I can add a - to the citation: 

```
Some critics, like Brown, argue that foo is bar [-@brown1999 23]. 
Output: Some critics, like Brown, argue that foo is bar (23). 
```

Great. But what if the author has more than one publication? Since I use the MLA CSL, this CSL will include the title of the work in order to disambiguate: 

```
Some critics argue that foo is bar [@brown1999 23]. 
Output: Some critics argue that foo is bar (Brown, "The Fooiness of Bar," 23). 

Some critics, like Brown, in "The Fooiness of Bar," argue that foo is bar [-@brown1999 23]. 
Output: Some critics, like Brown, in "The Fooiness of Bar," argue that foo is bar ("The Fooiness of Bar," 23). 
```

In the last example, the title of the work is repeated unnecessarily. Is there a way to remove both the author's name _and_ the title of the work, leaving only the page number? Something like this: 

```
Some critics, like Brown, in "The Fooiness of Bar," argue that foo is bar [--@brown1999 23].   
Output: Some critics, like Brown, in "The Fooiness of Bar," argue that foo is bar (23). 
```

**Comment by iansampson** [comment]
I know this is a couple years old now, but I’d love to see this feature too. It’s a common problem for humanists (I’m in English, and also using MLA): an essay about James Joyce’s *Ulysses*, for example, is almost certainly going to cite other texts by Joyce while making clear, in the body of the essay, when it’s talking about *Ulysses*. Including the title of the work in every in-line reference is redundant at that point.

I’d be happy to help code a solution for this if there were an agreed-upon syntax. I like Jonathan’s proposal above [--@joyce1922]. (Although it does exclude the possibility of suppressing the title *without* suppressing the author, which is probably quite rare in practice.)

**Comment by JonathanReeve** [comment]
Great. That would really help. I can't think of another solution to this. And at the moment, I have to do some serious gymnastics to get bibliographic entries to work without verbose in-text citations. @jgm, what do you think of the `--@` syntax?
