### ISSUE TITLE
Synchronize short words list with citeproc.js

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#226]
Pandoc-citeproc does not capitalize titles in quite the same way as citeproc.js; it seems this comes down to having a slightly different list of skip words/stop words/short words (or whatever we're calling them). The pandoc list is at <https://github.com/jgm/pandoc-citeproc/blob/2a01b0e09a6188587c887df8b3fa941b17d1a14c/src/Text/CSL/Util.hs#L226>; citeproc.js, <https://bitbucket.org/fbennett/citeproc-js/src/2b552c68ca2a891d3869ebdfa5167115cc5e546f/citeproc.js?fileviewer=file-view-default#citeproc.js-376>. I note the latter includes some phrases as well as single words; can pandoc-citeproc handle these?

**Comment by adunning** [comment]
I think the phrases are an attempt to handle some of the Chicago rules (8.157, Principles of headline-style capitalization):

> The conventions of headline style are governed mainly by emphasis and grammar. The following rules, though occasionally arbitrary, are intended primarily to facilitate the consistent styling of titles mentioned or cited in text and notes:
> 
> 1. Capitalize the first and last words in titles and subtitles (but see rule 7), and capitalize all other major words (nouns, pronouns, verbs, adjectives, adverbs, and some conjunctions—but see rule 4).
> Lowercase the articles the, a, and an.
> 2. Lowercase prepositions, regardless of length, except when they are used adverbially or adjectivally (up in Look Up, down in Turn Down, on in The On Button, to in Come To, etc.) or when they compose part of a Latin expression used adjectivally or adverbially (De Facto, In Vitro, etc.).
> 3. Lowercase the conjunctions and, but, for, or, and nor.
> 4. Lowercase to not only as a preposition (rule 3) but also as part of an infinitive (to Run, to Hide, etc.), and lowercase as in any grammatical function.
> 5. Lowercase the part of a proper name that would be lowercased in text, such as de or von.
> 6. Lowercase the second part of a species name, such as fulvescens in Acipenser fulvescens, even if it is the last word in a title or subtitle.

**Comment by jgm** [comment]
The citeproc-js skip-words seems too inclusive. It isn't correct to leave "because" uncapitalized in (American English) titles, is it?  That would be news to me.
I believe I got my list of short words from the CSL spec:
http://docs.citationstyles.org/en/stable/specification.html#title-case-conversion
Pandoc conforms to this, I think!

**Comment by adunning** [comment]
Ah, hadn't noticed it was in the spec. The inclusion of 'because' seems incorrect; but certainly 'through', being a preposition, should be there. I will open a CSL issue to sort this out.
