### ISSUE TITLE
Autocomplete not working with @collection, @thesis and @online

### ISSUE THREAD

**Issue by ppalazzo** [jgm/pandoc-citeproc#227]
Autocomplete is unable to locate any references of type "collection" (i.e. whole edited books), "thesis," and "online." These are also the content types that are not correctly highlighted in vim.

For example, this doesn't work with pandoc-citeproc autocomplete:

~~~~~
@collection{quatremeredequincy:1825architecture,
  location = {{Paris}},
  timestamp = {2013-09-16T04:06:44Z},
  title = {Architecture},
  publisher = {{Panckouke}},
  author = {Quatremère de Quincy, Antoine Chrysosthome},
  editor = {Diderot, Denis and d’ Alembert, Jean le Rond and Quatremère de Quincy, A.C.},
  date = {1825},
  options = {useprefix=true}
}
~~~~~

But this does work as expected:

~~~~~
@incollection{quatremeredequincy:1825type,
  location = {{Paris}},
  title = {Type},
  timestamp = {2013-09-16T04:06:44Z},
  booktitle = {Architecture},
  publisher = {{Panckouke}},
  author = {Quatremère de Quincy, Antoine Chrysosthome},
  editor = {Diderot, Denis and d’ Alembert, Jean le Rond and Quatremère de Quincy, A.C.},
  date = {1825},
  pages = {543--545},
  options = {useprefix=true}
}
~~~~~

**Comment by jgm** [comment]
I'm not sure what you're talking about.  pandoc-citeproc
doesn't itself have an autocomplete feature.  Perhaps
you're using some kind of editor plugin?  But if so, you
need to talk to the person who maintains that.

+++ Pedro P. Palazzo [May 15 16 09:19 ]:

**Comment by ppalazzo** [comment]
Thanks for the information, I have now realized it is a feature of 
vim-pandoc, not pandoc-citeproc. Sorry!

-- 
Pedro Paulo Palazzo
Coordenador de Museus e Patrimônio Cultural
Secretaria de Cultura do Distrito Federal
+55 61 3325 6269



John MacFarlane escreveu:
