### ISSUE TITLE
Incorrect case conversion MODS → YAML

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#231]
From `example.mods` from #228:

~~~
<mods ID="Aad2015">
    <titleInfo>
        <title>Combined Measurement of the Higgs Boson Mass in pp Collisions at
               root s=7 and 8 TeV with the ATLAS and CMS Experiments</title>
    </titleInfo>
</mods>
~~~

~~~
pandoc-citeproc -y example2.mods 
~~~

(pandoc-citeproc 0.9.1.1, installed with homebrew)

Output:

~~~
  title: Combined measurement of the higgs boson mass in pp collisions at root s=7
    and 8 teV with the aTLAS and cMS experiments
~~~

Expected:

~~~
  title: Combined Measurement of the Higgs Boson Mass in pp Collisions at root s=7
    and 8 TeV with the ATLAS and CMS Experiments
~~~

Note `teV`, `aTLAS`, and `cMS`.

It seems pandoc-citeproc is trying to convert the title from title case to sentence case – but this kind of conversion should be strictly limited to bibtex and biblatex data.

**Comment by nickbart1980** [comment]
BTW, conversion from bibtex and biblatex to JSON and YAML shows the same effect (“teV”, “aTLAS”, and “cMS”), too. This seems less problematic since in well-kept bibtex and biblatex data such strings should be protected, i.e., wrapped in braces anyway; still, both bibtex and biblatex (the programs) convert all unprotected strings to all-lowercase forms (“tev”, “atlas”, and “cms”), and for consistency, it wouldn’t be bad if pandoc-citeproc did the same.

**Comment by jgm** [comment]
+++ nickbart1980 [May 23 16 08:33 ]:
>   BTW, conversion from bibtex and biblatex to JSON and YAML shows the
>   same effect (“teV”, “aTLAS”, and “cMS”), too. This seems less
>   problematic since in well-kept bibtex and biblatex data such strings
>   should be protected, i.e., wrapped in braces anyway; still, both bibtex
>   and biblatex (the programs) convert all unprotected strings to
>   all-lowercase forms (“tev”, “atlas”, and “cms”), and for consistency,
>   it wouldn’t be bad if pandoc-citeproc did the same.

OK, that would make sense.  Want to open a separate issue
for this (concerning just bibtex parsing)?
