### ISSUE TITLE
Author suppression in annotated citations

### ISSUE THREAD

**Issue by garrettdashnelson** [jgm/pandoc-citeproc#237]
For reference systems that use page footnotes, it is common practice in disciplines like history to include a descriptive explanation along with the source. Pandoc normally handles these fine; however, using the minus sign to suppress an author does not seem to work inside of a complex footnote. 

```
Here is a body sentence with a complicated citation.[See, for example, @Baxter:1889um. A similar argument is made by the British writer H. G. Wells in -@Wells:1903wh.]

Author suppression works correctly with a simple citation.[-@Wells:1906tc]
```

When processing this to a .docx using the `chicago-fullnote-bibliography` CSL, the simple citation correctly suppresses the author, while the complex citation fails to recognize the minus operator.

Just a minor bug—don't know how I'd live without pandoc and citeproc!

**Comment by nickbart1980** [comment]
This does not completely resolve your issue, but a workaround is to do what pandoc expects, which is to separate individual parts of a multi-part citation with semicolons, as in the example below.

Also note that best practice suggests to move the sentence-ending punctuation sign *after* the citation, and *not* to end the citation inside the square brackets with a full stop; pandoc will take care of both, and you can switch between author-date and footnote styles without changing the text at all.

~~~
pandoc -s -F pandoc-citeproc -t markdown-citations-markdown_in_html_blocks << EOT

Here is a body sentence with a complicated citation [See, for example, @doe; 
a similar argument is made by the British writer H. G. Roe in -@roe].

Foo [-@roe].

---
reference-section-title: References
csl: chicago-fullnote-bibliography.csl

references:

- author:
  - family: Doe
    given: D.
  id: doe
  issued:
    - - 1999
  title: Title
  type: book

- author:
  - family: Roe
    given: R.
  id: roe
  issued:
    - - 2000
  title: Title
  type: book

...
EOT
~~~

Output:

~~~
Here is a body sentence with a complicated citation.[^1]

Foo.[^2]

References
==========

Doe, D. *Title*, 1999.

Roe, R. *Title*, 2000.

[^1]: See, for example, D. Doe, *Title*, 1999; a similar argument is
    made by the British writer H. G. Roe in *Title*, 2000.

[^2]: *Title*.
~~~

**Comment by garrettdashnelson** [comment]
Great; that does work in cases where the annotation can be rewritten using a semicolon. Still, there are certainly some cases where a footnote might include a lengthy discussion that would be in appropriate to format using a chain of semicolon-separated clauses. Not sure that this is a high enough priority to fix in a future release, but something to be aware of.
