### ISSUE TITLE
Position logic not in line with CSL spec.?

### ISSUE THREAD

**Issue by jackweinbender** [jgm/pandoc-citeproc#241]
I don't know Haskell. However, I've been reading the CSL spec and I've encountered what I think may be incorrect behavior within citeproc. In practical terms, given two repeated, identical citations with identical locators, the resulting position value should be _solely_ "Ibid", and not "ibid-with-locator".

So:

```
Lorem [@cross1973, p. 125] ipsum [@cross1973, p. 125].
```

should yield:

```
Lorem (Cross, Canaanite Myth, 125) ipsum (ibid.).
```

but, instead, we get 

```
Lorem (Cross, Canaanite Myth, 125) ipsum (ibid., 125).
```

The relevant portion of the spec is [HERE](http://docs.citationstyles.org/en/stable/specification.html?highlight=ibid#choose) (under "position").

The issue comes at the very last stipulation:

> **Preceding cite does have a locator:** if the current cite has the _same_ locator, the position of the current cite is “ibid”. If the locator differs the position is “ibid-with-locator”. If the current cite lacks a locator its only position is “subsequent”. 

As far as I can tell, this library only tests to see if a locator is supplied rather than if it matches the previous locator value. Thus, even if the current citation is identical to the previous one, the result is "ibid-with-locator" because, indeed, a locator is supplied.

I copied the CSL sheet that I was using and imported it into Zotero to see if the JS implementation worked as expected and, indeed, it did.

**Comment by jgm** [comment]
Thanks for the report.  I assume this is not style-dependent
behavior, but should be the way ibid and ibid-with-locator
always work?

+++ Jack Weinbender [Jun 28 16 18:44 ]:

**Comment by jackweinbender** [comment]
Yes, I should have been more clear. The "ibid" and "ibid-with-locator" are the position values, not style macros (or the like), so this is not style-dependent.
