### ISSUE TITLE
pandoc-citeproc does not capitalize the names of months

### ISSUE THREAD

**Issue by samueldodson** [jgm/pandoc-citeproc#251]
Hi, @jgm. The latest version of pandoc-citeproc (0.10.1) does not capitalize the names of months. For example, entries in my bibliography use "january" rather than "January". Do you know how I can capitalize the names of months? I am using pandoc (version 1.17.2) and the [APA CSL file](https://github.com/citation-style-language/styles/blob/master/apa.csl).

Input Markdown file:
~~~
@doe1999

# Bibliography
~~~

Input BibTeX file:
~~~
@misc{doe1999,
    title = Title,
    author = {Doe, John},
    month = January,
    year = 1999
}
~~~

Output:
~~~
<p><span class="citation">Doe (1999)</span></p>
<h1 id="bibliography" class="unnumbered">Bibliography</h1>
<div id="refs" class="references">
<div id="ref-doe1999">
<p>Doe, J. (1999, january). Title.</p>
</div>
</div>
~~~

Thanks.

**Comment by jgm** [comment]
Either use the official biblatex month abbreviations
(`jan`) or protect the string using `{January}`.

+++ Samuel Dodson [Jul 22 16 19:17 ]:

**Comment by samueldodson** [comment]
Thanks, @jgm.
