### ISSUE TITLE
Multilingual bibliography: item-dependent term localization

### ISSUE THREAD

**Issue by lierdakil** [jgm/pandoc-citeproc#252]
Yes, I know CSL doesn't have multilingual stuff standardized, but there's one key feature that's missing from pandoc-citeproc when compared to, e.g. biblatex: item-dependent term localization (e.g. `autolang=other` biblatex option)

Some bibliography formats (notably, russian GOST) require terms (like `vols.`, `pages`, etc) to be localized to language of original publication. Which is currently impossible to achieve if bibliography contains items in several languages; and even when it contains items in only one language, but text itself is in another, this becomes a problem.
#### What I propose

It should be possible to substitute style terms based on current item `language` value. Granted, since `language` doesn't always correspond to actual xml language identifier, it might be a good idea to add a dedicated field that could override `language` setting as well, for example, `langid`.

We could use a metadata flag `autolang` (bool or array -- see below) to enable or disable this behavior. That would hopefully answer some concerns about backwards-compatibility.

So, to summarize, one additional bibliography metadata variable is proposed, namely `langid` (or similar). A special meaning is assigned to `language` bibliography metadata variable. An additional Pandoc metadata variable is proposed, namely, `autolang`. `autolang` could be a `bool` to enable/disable this feature, or a list of language identifiers for possible localizations (see below).
#### What needs to be done (I think)

I took a quick look at sources and, while it's honestly looks somewhat like a spaghetti factory explosion, I believe most rendering-related work is done in `Text.CSL.Proc.citeproc`.

So, for one, we'd have to consolidate all styling, or at least term-related stuff there (or possibly in `procRefs`/`procBiblio`).

Secondly, we'd have to somehow break away from IO monad w.r.t. locale loading, otherwise most of `citeproc` stack will have to be `IO` (which we don't want). One option is making `autolang` a list of languages that might be used for term localization and preloading those. Another is to rely solely on `EMBED_DATA_FILES`.

Thirdly, we'd need to run `localizeCSL` or equivalent for each single one of references/citations. I'm afraid this would require changes to lots of internal logic, but there might be a way around that. Not entirely sure.
#### Current status

I've run a couple tests (hacking into `citeproc` and `procBiblio` using `unsafePerformIO`) and the approach itself seems to be sound (i.e. it works with some hiccups). However, using `unsafePerformIO` is just asking for trouble, and a proper implementation isn't something that could be done in an afternoon.
#### Conclusion

I might give implementation a shot, but I wanted to a) confirm that this is something that could be accepted b) ask for some pointers on where to start hacking and what to be wary of.

**Comment by jgm** [comment]
I think this is a reasonable suggestion (though I'd like to
get @nickbart's feedback too).  I would actually love to
have someone else working on the pandoc-citeproc code.  Most
of it is inherited from citeproc-hs, and I myself find the
code really mysterious.  I've tried to simplify things as
I've worked on the code, but much more could be done, and
I'd welcome changes like moving the locale processing
out of IO.

**Comment by nickbart1980** [comment]
> … CSL doesn't have multilingual stuff standardized …

CSL itself is a clearly defined standard (<http://citationstyles.org/downloads/specification.html>).

The only multilingual extension I am aware of, variously called “Extended CSL” or “CSL-M” has been created for “Multilingual Zotero (MLZ)” (<http://citationstylist.org/>), by Frank Bennett, the citeproc-js author – complete with various styles, mostly legal ones, but also Chicago.

For any CSL extensions we might be contemplating for pandoc, I’d recommend analysing “CSL-M” first, and, if possible at all, following this standard or a subset thereof.

**Comment by lierdakil** [comment]
> … CSL doesn't have multilingual stuff standardized …
>
> CSL itself is a clearly defined standard (http://citationstyles.org/downloads/specification.html).

It's not like standards are set in stone and don't ever change. I think it's reasonable to expect that at some point there could be CSL 1.1 etc which could add specification for multilingual stuff.

> The only multilingual extension I am aware of, variously called “Extended CSL” or “CSL-M” has been created for “Multilingual Zotero (MLZ)” (http://citationstylist.org/), by Frank Bennett, the citeproc-js author – complete with various styles, mostly legal ones, but also Chicago.
>
> For any CSL extensions we might be contemplating for pandoc, I’d recommend analysing “CSL-M” first, and, if possible at all, following this standard or a subset thereof.

Problem with CSL-M is it's rather intrusive, i.e. one would have to change CSL style to make use of its extensions, and unless I implement all of CSL-M in pandoc-citeproc (something I'm not very keen on doing right now), using CSL styles provided by MLZ is not really an option. While I personally don't have a problem with that, since I'm reasonably familiar with CSL, users in general probably won't like this very much.

My proposal, on the other hand, is entirely non-intrusive, although, admittedly, considerably more restrictive.

I believe it's possible to adapt what I had in mind to also respect `<cs:layout locale=...>` CSL-M selector if you're adamant that we should. But I strongly believe that making it the only option would be a mistake.

**Comment by nickbart1980** [comment]
> It's not like standards are set in stone …

True, but up to now pandoc-citeproc has adhered strictly to the CSL standards, and I for one would prefer to keep it that way – or either, as I said, to opt for supporting CSL-M, too. I’d certainly want to avoid creating another kind of multilingual extension to CSL, incompatible with CSL-M.

> … non-intrusive …

Well, a new metadata flag (`autolang`) certainly isn’t, but I’m skeptical about introducing new variables (`langid`).

In particular, I’m not sure why `langid`, in addition to `language`, would be required for your proposal at all. Any standards-conforming CSL JSON/CSL YAML databases should be using BCP 47 language tags (`en-US`, `en-GB`, `fr-FR`, …) in the `language` variable in the first place, also pandoc-citeproc’s biblatex-to-CSL-JSON/CSL-YAML converter does a very good job converting the content of biblatex `langid` fields to appropriate BCP 47 language tags. Anyone using a non-standards-conforming CSL JSON database would merely have to curate the `language` fields, or add some kind of preprocessing step (something like `s/english/en-US/` in both cases).

**Comment by lierdakil** [comment]
> I’m skeptical about introducing new variables (langid).

Understandable.

> pandoc-citeproc’s biblatex-to-CSL-JSON/CSL-YAML converter does a very good job converting the content of biblatex langid fields to appropriate BCP 47 language tags.

Yep, I missed this fact when writing this up. Well, that's why I filed this issue in the first place.

I can still think of a couple reasons for having two variables relating to language, but those are sufficiently weak to be ignored.

So yeah, we can drop `langid`. Would that be agreeable?

**Comment by nickbart1980** [comment]
> I can still think of a couple reasons for having two variables relating to language …

Indeed. biblatex’s distinction between `langid` (=[main] language of metadata record) and `language` (=language or languages used in the document) makes perfect sense. It’s a pity CSL does not have an equivalent of biblatex’s `language` field.

> So yeah, we can drop `langid`. Would that be agreeable?

Certainly.

**Comment by kugelblitz** [comment]
Hello,
It has been a while.

I am wondering: has pandoc-citeproc moved towards per-citation localized terms for end user?

**Comment by fbennett** [comment]
I must have toggled watch on this thread last year. Looking through the posts, I should note that most of the multilingual referencing with CSL-M does not depend on modifications to the styles -- it's done with configuration settings in the processor. It's still a lot of work to get there in the coding, but it's doable for most purposes without touching CSL code.

**Comment by kugelblitz** [comment]
There has been a discusson in issue #294, too, and some workarounds were proposed, though they are not completely functional.

**Comment by lierdakil** [comment]
Yeah, sorry, I didn't find time to implement it properly and later just had a lot of other things to occupy me, so it never got off the ground really. I might give it a shot eventually.

As for CSL-M, I base my inference that it needs CSL modification based on [this](http://citeproc-js.readthedocs.io/en/latest/csl-m/#simple-style-example), which seems to unambiguously require `cs:layout locale=...` to make use of multilingual features.

**Comment by fbennett** [comment]
@lierdakil Yes, it does read that way. I should edit that passage for clarity. In `citeproc-js`, multiple layouts are possible, but they are only necessary when the formatting of citations differs radically between languages (as in the English/Japanese example), and both are to be cited natively. That is true for Japanese scholarly publications aimed at a Japanese audience (because most scholars interested in the content will read both languages); but references are not cited natively in scholarly publications that draw on Japanese sources but are aimed at an English-speaking audience (because most readers will not be readers of Japanese). In the latter case, the insertion of translations or transliterations can be automated (but very carefully...) against a vanilla style.
