### ISSUE TITLE
Bibliography on a single line?

### ISSUE THREAD

**Issue by mdekauwe** [jgm/pandoc-citeproc#255]
Is it possible to wrap a bibliography so that all the entries are continuous rather than separated by a newline?

e.g. instead of:
1. Blah et al. (2013) some journal 19, 1759–1779.
2. Blah. et al. (2014) some journal 203, 883–900.

It would read:
1. Blah et al (2013) some journal. 2. Blah et al (1990) some journal. 3. Blah et al (2017) some journal. etc.

The latex style solutions (http://tex.stackexchange.com/questions/165000/condense-non-numbered-bibliography-into-one-line) don't appear to work for me, presumably as they are overiden.

**Comment by jgm** [comment]
I don't know of a way to do this.

But the thing to do is to take the LaTeX output
pandoc/pandoc-citeproc generates, and ask a TeX
expert if there's any way to make it behave as
you want.

+++ Martin De Kauwe [Aug 30 16 05:02 ]:
