### ISSUE TITLE
Markdown to beamer with biblatex: reference slide not created correctly

### ISSUE THREAD

**Issue by joostkremers** [jgm/pandoc-citeproc#258]
When converting from Markdown to a beamer `.tex` file, the reference slide isn't created correctly. If the Markdown file ends with:

    # References {.allowframebreaks}

the resulting `.tex` file ends with:

```
\begin{frame}[allowframebreaks]{References}

\end{frame}

\begin{frame}[allowframebreaks]{}
\bibliographytrue
\printbibliography[heading=none]
\end{frame}
```

That is, there is a frame that has the title "References" but is otherwise empty, and the references appear on an untitled frame.

Conversion command used:

    pandoc -t beamer <source.md> -o <target.tex> --bibliography=<somebib.bib> --biblatex --standalone

See the `pandoc-discuss` mailing list, message <https://groups.google.com/d/msg/pandoc-discuss/sIKX47zqhp4/KLvSzSJvAgAJ> for the original report.

**Comment by jgm** [comment]
I should have said this on pandoc-discuss, but it wasn't
clear to me until I saw the tex output.  Now I think that this
isn't a bug at all.

The style of ending your document with a `# References` heading
is for pandoc-citeproc.  If you use `--biblatex`, you're
bypassing pandoc-citeproc altogether.  biblatex will add its
own title, so even if we didn't create a new slide, you'd
end up with a redundant title.

**Comment by joostkremers** [comment]
But if I leave out the `# References` header, the slide with references doesn't get a title.

Oh wait, I just checked the `beamer` template and noticed that the variable `biblio-title` is provided to take care of that. (BTW, this variable isn't documented in the User's Guide, but perhaps it's not your policy to document all variables in all templates).

Anyway, sorry for the noise, I'll close this issue to get rid of it.

**Comment by jgm** [comment]
I see, biblatex produces a title for your references, but
you want a title on the slide itself as well?

See the man page for pandoc-citeproc, not the pandoc manual,
for its documentation.

+++ Joost Kremers [Oct 06 16 06:08 ]:

**Comment by joostkremers** [comment]
> I see, biblatex produces a title for your references, but you want a title on the slide itself as well?

I'm not sure what you mean, TBH. I tend to finish my beamer presentations with the following frame:

```
\begin{frame}[allowframebreaks]{References}
\bibliographytrue
\printbibliography[heading=none]
\end{frame}
```

This produces one or more slides with the title "References" followed by a Roman number (I, II, III, etc.) By "title" I mean the title that is displayed at the top of the slide. So I'm not sure what you mean when you say "biblatex produces a title for your references", since I don't know of any other title than the one displayed at the top of the slide.

But yes, I do want a title "References" at the top of the slide, and by setting `biblio-title` this works fine. I was just wondering why this variable wasn't listed [here](http://pandoc.org/MANUAL.html#variables-for-latex) or [here](http://pandoc.org/MANUAL.html#variables-for-slides).

> See the man page for pandoc-citeproc, not the pandoc manual, for its documentation.

Can't find it there, either. (I'm looking [here](https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md)).
