### ISSUE TITLE
Add support for BibLaTeX extended name format

### ISSUE THREAD

**Issue by dbobak** [jgm/pandoc-citeproc#266]
Biblatex (or rather biber) supoprts extended names format (page 38 of the [Biber manual](https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/documentation/biber.pdf/download))

Would it be possible to add support for it to pandoc-citeproc?

**Comment by jgm** [comment]
From the manual:

Here is an example:
```
AUTHOR = {Hans Harman and Simon de Beumont}
AUTHOR = {given=Hans, family=Harman and given=Simon, prefix=de, family=Beumont}
```
These two name speci cations are equivalent but the extended format explicitly names the parts. The supported parts are those speci ed by the Biblatex data mode constant nameparts, the default value of which is:
```
\DeclareDatamodelConstant[type=list]{nameparts}{prefix,family,suffix,given}
```
As with traditional BibTeX name parsing, initials are automatically generated but it is also possible to specify these explicitly:
```
AUTHOR = {given=Jean, prefix=de la, prefix-i=d, family=Rousse}
AUTHOR = {given={Jean Pierre Simon}, given-i=JPS}
```
Initials are speci ed by adding the su x -i to the namepart name. Compound parts may be protected with braces:
```
AUTHOR = {given={Jean Pierre}}
```
If a namepart contains a comma, the whole namepart should be protected with quotes:
```
AUTHOR = {"family={Robert and Sons, Inc.}"}
```
Traditional BibTeX name formats and the extended form may be used together:
```
AUTHOR = {Hans Harman and given=Simon, prefix=de, family=Beumont}
```
Per-namelist and per-name options may be speci ed in the extended name format:
```
AUTHOR = {namelistopt=true and Hans Harman and
          given=Simon, family=Beumont, nameopt=true}
```

**Comment by nickbart1980** [comment]
The main advantage is that it’s now possible to set `useprefix` on a per-name rather than a per-entry basis, so multiple authors where some have dropping and others non-dropping particles can be formatted correctly:

~~~
@article{H+L,
  AUTHOR = {given=Alexander, prefix=von, family=Humboldt, useprefix=false 
            and given=Antonie, prefix=van, family=Leeuwenhoek, useprefix=true}
}
~~~

~~~
---
references:
- id: H+L
  type: article-journal
  author:
  - family: Humboldt
    given: Alexander
    dropping-particle: von
  - family: Leeuwenhoek
    given: Antonie
    non-dropping-particle: van
...
~~~

pandoc-citeproc should also continue to support `juniorcomma` (used by biblatex-chicago), but now as a per-name option, too.

Explicitly specified initials, however, is not something CSL can handle.

**Comment by Frank-Zappa** [comment]
I am not sure whether or not this is related, but I think it is: Where ever the extended name format is used in my BiLaTeX file I get messy results converting a markdown file to ODT. The result would look like: 
`family=Goethe, prefix=von, given=Johann Wolfgang: Faust, hrsg. v. Albrecht Schöne, Frankfurt am Main 2005.`

The source looks like: 
`@book{goethe2005,
  langid = {german},
  location = {{Frankfurt am Main}},
  title = {Faust},
  isbn = {978-3-618-68001-7},
  publisher = {{Deutscher-Klassiker-Verl}},
  date = {2005},
  author = {family=Goethe, given=Johann Wolfgang, prefix=von, useprefix=false},
  editor = {Schöne, Albrecht}
}`

As the BibLaTeX file is created programmatically by Zotero, I can't really efficiently edit it. Is there a workaround for this, or are there any plans to support BibLaTeX extended name format in future releases?

 ps: I use pandoc 2.1.1.

**Comment by jgm** [comment]
Frank-Zappa <notifications@github.com> writes:

> As the BibLaTeX file is created programmatically by Zotero, I can't really efficiently edit it. Is there a workaround for this, or are there any plans to support BibLaTeX extended name format in future releases?

We should support it.
