### ISSUE TITLE
Journal issue: “Nos. 1” instead of “No. 1”

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#267]
With CSL styles that are set up to insert “No.” before a journal issue, pandoc-citeproc outputs “Nos.”, even when `issue` contains just a single number.

Relevant bits from `journal-of-common-market-studies.csl`:

~~~
<label variable="issue" form="short" text-case="capitalize-first"/>
<text variable="issue"/>
~~~

MWE:

~~~
pandoc -s -F pandoc-citeproc -t plain << EOT

Foo [@k].

# References {-}

---
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/journal-of-common-market-studies.csl
references:
- id: k
  type: article-journal
  author:
  - family: Koshland
    given: D. E.
  issued:
  - year: '1988'
  title: Random samples
  container-title: Science
  page: '1261'
  volume: '240'
  issue: '4857'
  language: en-US
...
EOT
~~~

Actual output:

~~~
Koshland, D. E. (1988) ‘Random Samples’. _Science_, Vol. 240, Nos. 4857,
p. 1261.
~~~

Expected output:

~~~
Koshland, D. E. (1988) ‘Random Samples’. _Science_, Vol. 240, No. 4857,
p. 1261.
~~~

Zotero/citeproc-js renders the same entry as expected, i.e., with “No. 4857”.

Note that “Vol.” is correct, and the single page in this example is correctly prefixed by “p.” (not ”pp.”), too – so apparently not all `single` terms are replaced by a `multiple` form.

**Comment by jgm** [comment]
I've chased this down to l. 119 of Text/CSL/Eval.hs:
```
    | Label    s f fm _     <- el = formatLabel f fm True s -- FIXME !!
```
Note the FIXME!  The parameter for "plural" was just set to True here.  The parameter of Label marked '_' can take the values Always, Never, or Contextual.  I assume that Contextual means that it should depend on what comes after the label, and it may be that this is impossible to determine at this place in the code.  So some architectural changes may be necessary to get this to work properly.

**Comment by jgm** [comment]
But I still don't understand why the same thing doesn't happen with "volume"...

**Comment by jgm** [comment]
OK, fixed it -- easy.
