### ISSUE TITLE
Adding option to link/color the entire citation, not only the year?

### ISSUE THREAD

**Issue by joelostblom** [jgm/pandoc-citeproc#268]
I am a fan of the how the journal Cell handles citation formatting. The entire citation is clickable and colored, as seen in the screenshots below from [this open access article](http://www.cell.com/cell/pdf/S0092-8674(15)00007-0.pdf). I think their approach facilitates quick scanning of the article content, which is more difficult when the citations are in the same color as the main text.

I enjoy the year-only linking and coloring options already present in pandoc, but it is not as quick to skip a section of multiple references when they contain both link-colored and black characters. Therefore, I think the possibility to color the entire citation would make a good addition to the current features, preferably as an option in the YAML-header, but I am also interested in if it is possible to currently achieve this behavior with a custom filter.

Cell article screenshot:
![image](https://cloud.githubusercontent.com/assets/4560057/20249419/9aee19d2-a9c6-11e6-9a97-19eac7aa7f66.png)

**Comment by jgm** [comment]
The reason we only color/link the year is that a single
citation may contain references to multiple articles, e.g.

    (see Jones 2003; 2004; 2008, pp. 51-3; Smith 2008).

That only has to do with linking, though.  It's possible,
using a filter, to ensure that the entire citation is
colored.  The filter would just need to match on "Cite"
inlines and add some raw latex around them to set
the color, assuming you're targeting latex/pdf.

If you're targeting HTML, pandoc already puts the
citation in a span with class "citation" -- you can
just use CSS to color this as you like.

**Comment by samueldodson** [comment]
I am guessing that @joelostblom is more interested in linking the whole citation than colouring it, so colouring the whole citation without expanding the link is a poor solution. Would it be possible to expand the link if and only if the citation contains one reference? This approach is used in pandoc-crossref, see [lierdakil/pandoc-crossref/issues/109](https://github.com/lierdakil/pandoc-crossref/issues/109).

**Comment by faroit** [comment]
+1

**Comment by mi-lad** [comment]
+1

**Comment by khalid-hussain** [comment]
+1

**Comment by AndreyAkinshin** [comment]
+1

**Comment by CxRes** [comment]
Looking at the discussion above, imho the nice solution will be to link the year when there are multiple citations for the same author. In single citation per author cases, it just seems nicer to place the link on author and date together. (Or simpler still but little inconsistent, which is what you would have sought to avoid if I am guessing correctly: the first link is `Jones 2003`, the next link is `2004`)

Coloring citations would be nice too, but that as @samueldodson indicates as well, this is not what we (at least I) intend (That could be handled with latex/css also).
