### ISSUE TITLE
Failed to process chinese characters in Endnote bibliography file.

### ISSUE THREAD

**Issue by amitbha** [jgm/pandoc-citeproc#270]
**$ pandoc-citeproc CNKI.enl -y**                                   
pandoc-citeproc: Error reading /tmp/citeproc.0/bibutils-tmp.biblio
"stdin" (line 1, column 10):
unexpected "\a"
expecting white space or ","

[The endnote file: CNKI.zip](https://github.com/jgm/pandoc-citeproc/files/618041/CNKI.zip)

**Comment by jgm** [comment]
Worked fine for me with pandoc-citeproc 0.10.2.1.
What version of pandoc-citeproc are you using?
And how did you get/install it?

+++ amitbha [Nov 28 16 19:29 ]:

**Comment by amitbha** [comment]
$ pandoc-citeproc -V
pandoc-citeproc 0.9.1.1

It's in the ubuntu 16.10 repository.

**Comment by jgm** [comment]
This is likely a problem with the bibutils library rather
than pandoc.  (Pandoc uses bibutils for Chinese character
conversion.)

However, if you want us to test, please send a sample
endnote bibliography that causes the problem for you.

+++ amitbha [Dec 02 16 01:31 ]:

**Comment by amitbha** [comment]
I update the pandoc to latest 1.19, and it's ok now.
Thanks for your reply.
