### ISSUE TITLE
Semicolons don't work in citations

### ISSUE THREAD

**Issue by mickley** [jgm/pandoc-citeproc#271]
I would like to write a citation where a semicolon is included in extraneous wording.  For example:
`[@Grant:1959; @Huether:1969; Huether unpublished]`
`[see @Grant:1959; @Huether:1969; this is not supported by @Smith:2015]`

Perhaps unsurprisingly, this does not work.  the last semicolon breaks the citation, presumably because citeproc expects another reference.  Is there or could there be a way to escape semicolons so that they can be included in hand-written words within the citation?  

Not an uncommon situation, and could be covered similarly to how Papers and other reference managers handle this:
http://support.mekentosj.com/kb/cite-write-your-manuscripts-and-essays-with-citations/citations-modifiers-prefix-suffix-page-number-authoryear-suppression-in-papers-for-mac

**Comment by jgm** [comment]
You can simply backslash-escape the semicolon.

+++ James Mickley [Jan 03 17 09:01 ]:

**Comment by mickley** [comment]
@jgm Thanks for that tip.  Is that documented somewhere?

**Comment by jgm** [comment]
It's documented in the manual that you can backslash-escape
any special punctuation characters that have a special
meaning in pandoc markdown's syntax.

+++ James Mickley [Jan 14 17 14:12 ]:
