### ISSUE TITLE
et-al term is not being appended to the author list in the bibliography

### ISSUE THREAD

**Issue by fwmm** [jgm/pandoc-citeproc#274]
Despite pandoc-citeproc correctly detecting the conditions for either using or not the et-al abbreviation, the et-al term is not being appended to the author list. If I set the et-al-min attribute to an empty string it correctly prints the whole list of authors. On the other hand, if I set it to like 3 (the related bibtex entry has more than 10 authors), it correctly trunks the list to the first author but adds no "et al" term to the end. Files attached.

[et-al.zip](https://github.com/jgm/pandoc-citeproc/files/736037/et-al.zip)

**Comment by fwmm** [comment]
Oh! My environment:
- macOS Sierra
- pandoc 1.18
- pandoc-citeproc 0.10.2.1

**Comment by jgm** [comment]
This seems to depend on the style.  When I tried with pandoc's default style, I got an 'et al'.

I note that if you remove the line

    <et-al term="and others" font-style="italic"/>

from your ieee.csl, it works -- you get 'et al.'

So, assuming this style is correct, it seems that pandoc-citeproc is not properly handling the `et-al` element with a custom term.

**Comment by fwmm** [comment]
I get the same result (no 'et al') with or without the 'term' attribute being used.

This is the command line I'm using:

pandoc -o test.docx -f markdown -t docx --filter /usr/local/bin/pandoc-citeproc --csl ~/ieee.csl --bibliography=/Users/fabiomaia/Dropbox/sci/biblio.bib test.md

**Comment by jgm** [comment]
Fixed now.  I get

    [1] H. Abelson <em>and others</em>, “Keys Under Doormats...

**Comment by fwmm** [comment]
Cool. Thanks, man!
