### ISSUE TITLE
Specific volumes cannot be cited outside references data

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#275]
There is no way at the moment to refer to a specific volume of a work with locators. Right now, the only way to have volume information show up correctly is by adding it to the references data:

```shell
pandoc -F pandoc-citeproc << EOT
---
references:
- id: test
  type: book
  volume: 1
---

This is a test [@test, p. 1].

EOT
```

The resulting citation will be 'n.d., 1:1', as expected. This is not feasible most of the time, however, and impossible if one needs to cite pages from more than one volume in the same document.

I wonder whether it would be possible to achieve this by combining adjacent locators for volume and page. The same output could be then achieved with something along the following lines:

```shell
pandoc -F pandoc-citeproc << EOT
---
references:
- id: test
  type: book
---

This is a test [@test, vol. 1, p. 1].

EOT
```

**Comment by njbart** [comment]
Have you checked whether the CSL specs allow multiple locators?

**Comment by adunning** [comment]
It's not really specified, as far as I can tell.

**Comment by jgm** [comment]
I think this is out of scope. CSL only provides for a single
labeled locator, as far as I can see.  You might take this
up with CSL spec designers.

>   feasible most of the time, however, and impossible if one needs to cite
>   pages from more than one volume in the same document.

Note:  you can of course have multiple references for different
volumes of the same book. So it's possible to cite pages
from more than one volume; you just can't do it in a single
locator.

**Comment by adunning** [comment]
That's quite true, but it's fairly rare that it's desirable to have two volumes of the same work listed separately in the bibliography.

Another approach might be to parse Chicago-style volume references from the locator, e.g. `[@test, pp. 1:123–154]`. Right now, of course, one can write it that way, but it will just come through verbatim: the numbers won't be abbreviated, and the format of the volume number won't be changed for different reference styles.

(I agree that it would be nice to have this in the spec, but it hasn't been updated since May 2010, and it doesn't appear that there isn't much hope of revision in the near future.)

**Comment by jgm** [comment]
+++ Andrew Dunning [Jan 30 17 06:44 ]:
>   That's quite true, but it's fairly rare that it's desirable to have two
>   volumes of the same work listed separately in the bibliography.
>
>   Another approach might be to parse Chicago-style volume references from
>   the locator, e.g. [@test, pp. 1:123–154]. Right now, of course, one can
>   write it that way, but it will just come through verbatim: the numbers
>   won't be abbreviated, and the format of the volume number won't be
>   changed for different reference styles.
>
>   (I agree that it would be nice to have this in the spec, but it hasn't
>   been updated since May 2010, and it doesn't appear that there isn't
>   much hope of revision in the near future.)

Even if we worked outside the spec, this would require
revisions to the basic data types -- so, not an easy change.
I do see the motivation for it, though.

**Comment by adunning** [comment]
I was afraid of that. Thanks for your consideration, in any case!

**Comment by njbart** [comment]
What seems so intriguing about this problem is that the required information plus style-specific formatting instructions are all available (as to the latter, cf., e.g., the instructions concerning the volume variable inside the `<citation>` element in `chicago-author-date.csl`); it's only that pandoc-citeproc is currently unable to combine them.

(And as to the CSL specs, I'd agree there is little hope of seeing them revised any time soon …)

But possibly there's a workaround, maybe along the following lines:

As the OP describes, results are as expected if the CSL variable `volume` is set.

Couldn't pandoc-citeproc just set the `volume` variable *temporarily, i.e., only while formatting the in-text citation*, to the volume information that can be parsed from a suffix, e.g., `This is a test [@test, vol. 1, p. 1].`?

**Comment by jgm** [comment]
+++ Nick Bart [Jan 31 17 07:16 ]:
>   Couldn't pandoc-citeproc just set the volume variable temporarily,
>   i.e., only while formatting the in-text citation, to the volume
>   information that can be parsed from a suffix, e.g., This is a test
>   [@test, vol. 1, p. 1].?

Interesting idea.  I can look into it at some point; it's not obvious
to me now whether this can be done easily.

**Comment by jgm** [comment]
@nbart What would we do with something like

    [@item1, 2:3-5, 4:220-223]

Here you can't simply set the volume for the whole citation.

**Comment by njbart** [comment]
Indeed. And actually, I'm developing more doubts about my earlier proposal myself: I'm not even sure `chicago-author-date.csl` has got it right when including a volume number taken from the metadata into an in-text citation:

I think volume information in an in-text citation is *only* needed when the author-date shorthand refers to a multi-volume work as a whole. 

However, if a given author-date combo refers to one specific volume only, I don't see the point in including the volume info in the in-text citation – and I can't find anything in the Manual arguing in favour of including it in such cases either. Moreover, other styles, e.g. `apa.csl` do not add volume info to in-text citations at all.

Still, it'd be great if examples like "(Barnes 1998, 2:354-55, 3:29)" (this one is from CMoS 16e, 15.22) could be formatted correctly by pandoc-citeproc. A simple approach might be to just accept "number-colon" as a kind of prefix to page numbers, while continuing to format the page numbers as usual (including page range abbreviation, as in the "Barnes" example).

**Comment by jgm** [comment]
+++ Nick Bart [Feb 01 17 15:34 ]:
>   Still, it'd be great if examples like "(Barnes 1998, 2:354-55, 3:29)"
>   (this one is from CMoS 16e, 15.22) could be formatted correctly by
>   pandoc-citeproc. A simple approach might be to just accept
>   "number-colon" as a kind of prefix to page numbers, while continuing to
>   format the page numbers as usual (including page range abbreviation, as
>   in the "Barnes" example).

I agree. I'll try to make it do this.
