### ISSUE TITLE
Wrong rendering of conference paper without proceedings title?

### ISSUE THREAD

**Issue by julianaus** [jgm/pandoc-citeproc#277]
Hi, 

I am trying to locate an error that occurs with the normal APA style using the [Scrivener/Zotero/Pandoc/Marked 2 setup](http://davepwsmith.github.io/academic-scrivener-howto/). When I cite a conference paper that does not have a proceedings title, it still prints "In" after the title of the paper. Also, the conference title is reproduced in sentence case. See this example (bold by me): 

Cox, M. (2000). The development of computer-assisted reporting. **In.** Presented at the **Conference of the newspaper division, aejmc**, Chapel Hill, NC. 
 
In other setups using the same csl-file, for instance with Zotero/Microsoft Word, it works fine. 
Any idea, what could cause this? 

Best,
Julian

**Comment by jgm** [comment]
It would help to know your pandoc and pandoc-citeproc
versions.

Can you also give a small example we could use
to reproduce this, with all needed files?

**Comment by julianaus** [comment]
Thanks for the reply. I use 

pandoc 1.19.2.1
pandoc-citeproc 0.10.4

The files are below. I just found a similar error. With the item type "unpublished" (= conference presentation) the meeting name (= the "note" field) is also omitted. I included this example in the files. This is how my current setup prints it*: 

> Garrison, B. (1996, September 19). _Computer-assisted reporting: A national use update_. Washington, D.C. 

These would be correct references for the two examples: 

> Cox, M. (2000). The development of computer-assisted reporting. Presented at the Conference of the Newspaper Division, Association for Education in Journalism and Mass Communication (AEJMC), Chapel Hill, NC.

> Garrison, B. (1996, September). _Computer-assisted reporting: A national use update_. Presented at the National Society of Professional Journalists, Washington, D.C. 

[examplefiles.zip](https://github.com/jgm/pandoc-citeproc/files/754608/examplefiles.zip)

*The URLs were removed manually.

**Comment by njbart** [comment]
pandoc-citeproc use the presence or absence of the `eventtitle` field to figure out whether `unpublished` is supposed to be a manuscript or a presentation. From the pandoc-citeproc man page:

> For an unpublished manuscript, use the biblatex entry type `unpublished` without an `eventtitle` field (this entry type will be mapped to CSL `manuscript`).
For a talk, an unpublished conference paper, or a poster presentation, use the biblatex entry type `unpublished` with an `eventtitle` field (this entry type will be mapped to CSL speech). Use the biblatex `type` field to indicate the type, e.g. "Paper", or "Poster".

**Comment by julianaus** [comment]
Thanks for the hint. That made it a lot clearer. The problem seems to be that Zotero doesn't print an `eventtitle` field for the "presentation" entry type (= `unpublished`). Zotero does this only for `inproceedings`. Instead, it uses the `note` field (= "meeting name" in the Zotero interface). 

Would it be possible for you to include this in a future update of pandoc-citeproc, so that it will use the biblatex ´note´ field, if no biblatex ´eventtitle´ field is given?

**Comment by njbart** [comment]
> Would it be possible for you to include this in a future update of pandoc-citeproc, so that it will use the biblatex `note` field, if no biblatex `eventtitle` field is given?

No, I don't see how this could work. Better try and get this fixed on the BBT side – exporting "meeting name" to `note` might make sense for bibtex, but for biblatex, it should be exported to `eventtitle`.
