### ISSUE TITLE
Can't wrap references in LaTeX environment

### ISSUE THREAD

**Issue by fmoralesc** [jgm/pandoc-citeproc#278]
Since pandoc-citeproc seems not to support hangind indent's, I'm trying to wrap the references list in a `hangparas` environment. While this is possible manually, I would prefer to have some way to do it automatically, and I can't find a solution for it. 

Is it possible, for example, to have the references be inserted into the document at some call of a LaTeX command, instead of just a div with id `refs`. So, instead of the following (which doesn't work)
```
\begin{hangparas}{1em}{1}
<div id="refs"></div>
\end{hangparas}
```
something like this?
```
\begin{hangparas}{1em}{1}
\pandocciteprocrefs
\endg{hangparas}
```

EDIT: The "magic" command could even be biblatex's `\printbibliography`.

**Comment by njbart** [comment]
For my own solution, see https://github.com/jgm/pandoc/issues/3255#issuecomment-262950028.

For a general discussion and proposals how this could be implemented in pandoc(-citeproc), see https://github.com/jgm/pandoc-citeproc/issues/85 (and also https://github.com/jgm/pandoc-citeproc/issues/261 and https://github.com/jgm/pandoc/issues/3255).

**Comment by fmoralesc** [comment]
Thanks for the references, @njbart.

**Comment by jgm** [comment]
You can also now do this:
````
```{=latex}
\begin{hangparas}{1em}{1}
```

<div id="refs"></div>

```{=latex}
\end{hangparas}
```
````
