### ISSUE TITLE
Create bibliography from file (without citations in text)

### ISSUE THREAD

**Issue by mendelkranz** [jgm/pandoc-citeproc#282]
I'm wondering if there's a way to generate the bibliography simply using all the references from the bib file? And moreover, would it be possible to do this using two different bib files?

For instance, I'm thinking of a CV where one might want to include all their articles/conference papers/books and to just maintain separate bib files for these and then have pandoc automatically generate bibliographies without needing to go ahead and cite each instance specifically.

**Comment by jgm** [comment]
See the pandoc manual:

It is possible to create a bibliography with all the citations,
whether or not they appear in the document, by using a wildcard:

    ---
    nocite: |
      @*
    ...

+++ Mendel Kranz [Mar 07 17 18:18 ]:

**Comment by mendelkranz** [comment]
Thanks I do see that now. One quick questions in response: Is there a way to do that using multiple bibliographies?

**Comment by jgm** [comment]
No, we don't really support multiple bibliographies.

+++ Mendel Kranz [Mar 11 17 15:44 ]:
>   Thanks I do see that now. One quick questions in response: Is there a
>   way to do that using multiple bibliographies?
