### ISSUE TITLE
Cannot find CSL files specified with a soft link

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc-citeproc#283]
I have a CSL file that is soft linked:

```
$  ls -al /Users/ian/.pandoc/apa.csl
lrwxr-xr-x  1 ian  staff    24B  6 Mar 15:23 /Users/ian/.pandoc/apa.csl@ -> .dotfiles/pandoc/apa.csl
```

If I use this simple pandoc:

```
---  
citation-style: /Users/ian/.pandoc/apa.csl  
---  

# Summary #
The background question is sound, and of substantial importance for systems neuroscience.
```

I get an error:

```
$ pandoc --filter pandoc-citeproc  in.md -o out.docx
pandoc-citeproc: Error parsing XML file /Users/ian/.pandoc/apa.csl: /Users/ian/.pandoc/apa.csl: openBinaryFile: does not exist (No such file or directory)
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

I also get an error if I use `--csl /Users/ian/.pandoc/apa.csl` directly with no YAML header. If I specify the original link location `/Users/ian/.dotfiles/pandoc/apa.csl` then compilation works fine.

Yet I can use a soft link for the bibliography file without problems:
```
$ ls -al /Users/ian/.pandoc/core.bib
lrwxr-xr-x  1 ian  staff    36B 16 Mar 14:50 /Users/ian/.pandoc/core.bib@ -> /Users/ian/.dotfiles/pandoc/core.bib
```
```
---  
bibliography: /Users/ian/.pandoc/core.bib  
citation-style: /Users/ian/.dotfiles/pandoc/apa.csl  
---  

# Summary #
The background question is sound, and of substantial importance for system neuroscience.
```
...this compiles fine...

Versions:
```
$ echo "macOS $(sw_vers -productVersion)"
macOS 10.12.3

$ pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
Default user data directory: /Users/ian/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

$ pandoc-citeproc -V
pandoc-citeproc 0.10.4.1
```

**Comment by jgm** [comment]
When I tried to reproduce this, I found that there were
problems with the symlinks for both citation-style and
bibliography.  And I really can't see any reason (from
the code) why they'd behave differently.

> for "bibliography" we used `findFile ["."] fname`
> to get the path, then `readBiblioFile path`.
>
> for "citation-style" we use `readCSLFile` from
> Text.CSL.Parser.  This uses `findFile [".", USERDATADIR] fname`.
> to get the path, then `fetchItem` to fetch it.
>
> So I'm guessing the relevant difference is the difference
> between `readBiblioFile` (which seems to handle symlinks)
> and `fetchItem` (which seems not to).
>
> `readBiblioFile` calls `readBibtex` for .bib files like
> yours, and `readBibtex` reads the file using
> `Text.Pandoc.UTF8.readFile`.  Under the covers
> this uses `openFile` and `Data.ByteString.hGetContents`.
>
> `fetchItem` uses `Data.ByteString.readFile`.

Another odd thing:  symlinks worked fine when they were
to files in the working directory, but problematic
when in another directory.

I was able to reproduce all of this using basic Haskell
file functions, without anything pandoc-specific:

```
% ls -l /Users/jgm/.pandoc/b.bib
lrwxr-xr-x  1 jgm  staff  10 Mar 16 21:03 /Users/jgm/.pandoc/b.bib -> biblio.bib
% ls -l b.bib
lrwxr-xr-x  1 jgm  staff  10 Mar 16 21:00 b.bib -> biblio.bib

Now with ghci:
Prelude System.IO System.Directory> doesFileExist "/Users/jgm/tmp/.pandoc/b.bib"False
Prelude System.IO System.Directory> doesFileExist "./b.bib"
True

Prelude Data.ByteString System.IO> h <- openFile "/Users/jgm/.pandoc/b.bib" ReadMode
*** Exception: /Users/jgm/.pandoc/b.bib: openFile: does not exist (No such file or directory)
Prelude System.IO System.Directory> h <- openFile "./b.bib" ReadMode
Prelude System.IO System.Directory>
```

So, the upshot seems to be that System.IO.openFile doesn't
like symbolic links unless they're in the same directory.
I haven't been able to find anything more about this, but
it's a start towards diagnosing the problem.

**Comment by iandol** [comment]
Would these posix related functions help (I'm not a haskell programmer...)? 

https://github.com/haskell/unix

And though not essential, but for portability it would also be nice to support ~/ posix tilde home expansion.

**Comment by jgm** [comment]
I discovered something interesting.

If you create the symlink thus
```
ln -s biblio.bib ~/tmp/b1.bib
```
then `doesFileExist "b1.bib"` returns `False`.

But if you create the symlink with an absolute path,
```
ln -s `pwd`/biblio.bib ~/tmp/b2.bib
```
then `doesFileExist "b2.bib"` returns `True`.

Hence I suspect things might work for you if you specify an absolute rather than a relative path when creating your symlink. Can you try that?

**Comment by iandol** [comment]
Hi John, yes that seems to work!  Not specific to Haskell then so I suppose this can be closed.

Thanks!
