### ISSUE TITLE
All reference fields must be composed of inlines

### ISSUE THREAD

**Issue by gilgamec** [jgm/pandoc-citeproc#287]
After parsing, the fields of a reference are represented as lists of pandoc ```Inline```s.  This has the problem that some fields (abstract or review, for example) can be formed of multiple paragraphs.  These fields are used in some styles (such as apa-annotated-bibliography) and render poorly.  (They are also usually rendered with attribute "block", which pandoc-citeproc apparently also ignores.)  However, the rendering is even worse than a single paragraph would be, because the conversion (in Text.CSL.Input.Bibtex.hs, function blocksToFormatted) makes a special case for a single paragraph.  Multiple paragraphs are just concatenated together, without even whitespace between them.

**Comment by jgm** [comment]
Currently all bibliography entries are rendered as Paragraphs.  So until that changes (and yes, it should eventually), we need to make sure the fields have Inline contents.
