### ISSUE TITLE
Pandoc-citeproc fails compilatino with "Request time-out"

### ISSUE THREAD

**Issue by tomchor** [jgm/pandoc-citeproc#295]
I am using `pandoc-citeproc` to deal with the refences in pandoc and sometimes Pandoc compilation fails because `pandoc-citeproc` compilation fails.

I cannot make a MWE because this happens only occasionally (about 1 every 10 compilations) and I haven't been able to localize the problem. If I try to recompile with the same command then it works, so I believe this is a bug.

The precise error I get is

```
pandoc-citeproc: StatusCodeException (Status {statusCode = 408, statusMessage = "Request Time-out"}) [("Cache-Control","no-cache"),("Connection","close"),("Content-Type","text/html"),("X-Response-Bo
dy-Start","<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"),("X-Request-URL","GET http://www.zotero.org:80/styles/elsevier-harvard"
)] (CJ {expose = []})
pandoc: Error running filter pandoc-citeproc
```

I'm compiling with the following options

```
PANDOC_OPTIONS=--smart --standalone --columns=80 --verbose
PANDOC_PDF_OPTIONS=--latex-engine=pdflatex --listings --template=article.latex --filter pandoc-citeproc --csl=/home/tomas/.pandoc/agricultural-and-forest-meteorology.csl
```

But the same issue happens when I compile for `tex` (with the same options) and using the default template.

Version information:
pandoc 1.16.0.2
Compiled with texmath 0.8.4.1, highlighting-kate 0.6.1.
pandoc-citeproc 0.9

Running on Linux Mint 18.1. I tried downloading and installing the newest version of `pandoc-citeproc` but couldn't figure out how to compile it.

**Comment by jgm** [comment]
This is probably a network issue on your end; it's trying to fetch the style from zotero and timing out.
I don't think there's a pandoc bug.
