### ISSUE TITLE
Insert bibliography entry cited in full length in the text

### ISSUE THREAD

**Issue by nim65s** [jgm/pandoc-citeproc#296]
Hi,

I'd like to get the full length of an entry directly in the text. Is this possible ?
The `\bibentry` command from the bibentry package does it for bibtex, but I'm usign pandoc-citeproc & pandoc-crossref.

Thanks !

**Comment by samueldodson** [comment]
I would also like to add full citations in the text. While we wait to hear from @jgm, you may want to review [this](https://github.com/jgm/pandoc/issues/2335) similar feature request for implementing the `\fullcite` `biblatex` command.

**Comment by nim65s** [comment]
Oh, I had missed it, thanks !
