### ISSUE TITLE
Diacritic letters generate undefined control sequence

### ISSUE THREAD

**Issue by pa0** [jgm/pandoc-citeproc#299]
pandoc-citeproc 0.10.1 with csl=apa.csl from my.bib file with author "Bedyńska i Książek" return "Bedyńska i Ks\każek" which gives xelatex error:
`
! Undefined control sequence.
`
How I can handle with diacritic letters in pandoc-citeproc?

**Comment by jgm** [comment]
I just tried this (with both 0.10.3 and 0.11) and got:

Książek, B. i.

You could try with a more recent version, and if you still
get the problem, give us exact instructions for reproducing
the problem, including the input file, bib file, and full
command line.

+++ pAo [Aug 31 17 07:25 ]:

**Comment by pa0** [comment]
Hello John,

Your mail inspired me to look into bib file. I found record:

@book{Bedynska12a,
	Author = {Bedy{\'n}ska, Sylwia and Ksi{\k a}{\.z}ek, Monika},
	Date-Modified = {2017-09-05 07:23:32 +0000},
	Title = {Statystyczny drogowskaz. Praktyczny przewodnik wykorzystania modeli regresji oraz r{\'o}wna{\'n} strukturalnych},
	Volume = {3},
	Year = {2012}}

but with UTF-8 authors are "Bedyńska, Sylwia and Książek, Monika".

I don't know why BibDesk replaces "ą" -> "{\k a}" but it is source of my problem.

Sorry for bothering You

Regards
Paweł

**Comment by jgm** [comment]
Looks like we need to add support for `\k a` in pandoc.

+++ pAo [Sep 05 17 00:32 ]:

**Comment by pa0** [comment]
> Wiadomość napisana przez John MacFarlane <notifications@github.com> w dniu 05.09.2017, o godz. 18:48:
> 
> Looks like we need to add support for `\k a` in pandoc.
it will be nice :-)

Here all polish diacritic letters:

żółćęśąźń

{\.z}{\'o}{\l}{\'c}{\k e}{\'s}{\k a}{\'z}{\'n}
{\.Z}{\'O}{\L}{\'C}{\k E}{\'S}{\k A}{\'Z}{\'N}


Regards
Pawe{\l} ;-)

**Comment by jgm** [comment]
Great, I'll add support for all these.

+++ pAo [Sep 05 17 19:25 ]:
