### ISSUE TITLE
Uppercase letters lowercased following punctuation

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#301]
The commit at <https://github.com/jgm/pandoc-citeproc/commit/c086acdb6f51639ab5ff79ba5409b4a3254103cc> or one of the related changes seems to be causing letters that are uppercase in the source to be lowercased. Below are an example of initials, a word following a bracket, and a word following a tag (pandoc-citeproc 0.10.5.1):

```shell
pandoc -F pandoc-citeproc -t plain << EOT

---
references:
- id: test
  title: "Essays presented to N.R. Ker (On Art)"
- id: test2
  title: "<i>Test:</i> An experiment: An abridgement"
---

@test; @test2

EOT
```

Result:

```markdown
(“Essays Presented to N.r. Ker (on Art),” n.d.); (“Test: an Experiment:
An Abridgement,” n.d.)

“Essays Presented to N.r. Ker (on Art).” n.d.

“Test: an Experiment: An Abridgement.” n.d.
```

**Comment by jgm** [comment]
I fixed the N.R. Kerr issue.

The other issues, if I understand right, are:

1)  You'd like the capitalization of "On" preserved after the open parenthesis
2)  The colon after "Test" isn't recognized when it's inside emphasis

As for 1), it's tricky to see how to deal with this.  We could treat an open-paren as, in effect, starting a new sentence, which would make the opening word capitalized even if it's a small word.  But not all parens should be treated that way:  sometimes you just parenthesize a word or two.  And I don't know how to distinguish between the two cases.  This might be a case where you need to manually mark the "On" to preserve its case.

**Comment by adunning** [comment]
Many thanks for taking care of that. I obviously misidentified the problem for the other two cases.

For the case of a word being lowercased after the opening bracket, an instance I have on file of the same citation from a year and a half ago is formatted correctly, and the same citation is processed correctly in Zotero/citeproc-js: I think it simply doesn't lowercase anything that the user has capitalized. Is the feature of lowercasing words itself new?

**Comment by njbart** [comment]
> Zotero/citeproc-js: I think it simply doesn't lowercase anything that the user has capitalized.

Indeed. I don”t feel pandoc should handle this any differently (if the biblio source is in CSL JSON or CSL YAML, that is).

**Comment by jgm** [comment]
+++ Nick Bart [Sep 10 17 00:35 ]:
>     Zotero/citeproc-js: I think it simply doesn't lowercase anything
>     that the user has capitalized.
>
>   Indeed. I don”t feel pandoc should handle this any differently (if the
>   biblio source is in CSL JSON or CSL YAML, that is).

OK, I can look into changing this, but I need to make sure
we don't break the treatment of bibtex bibliographies.

**Comment by jgm** [comment]
+++ Nick Bart [Sep 10 17 00:35 ]:
>     Zotero/citeproc-js: I think it simply doesn't lowercase anything
>     that the user has capitalized.
>
>   Indeed. I don”t feel pandoc should handle this any differently (if the
>   biblio source is in CSL JSON or CSL YAML, that is).

I have the following comment in the source code, which (it
says) is taken straight from CSL docs (I've added some
emphasis):

> "Title case conversion (with text-case set to “title”) for English-language
> items is performed by:
>
> For uppercase strings, the first character of each word remains capitalized.
> **All other letters are lowercased.**
> For lower or mixed case strings, the first character of each lowercase word
> is capitalized. The case of words in mixed or uppercase stays the same.
> In both cases, **stop words are lowercased,** unless they are the first or last
> word in the string, or follow a colon. The stop words are “a”, “an”, “and”,
> “as”, “at”, “but”, “by”, “down”, “for”, “from”, “in”, “into”, “nor”, “of”,
> “on”, “onto”, “or”, “over”, “so”, “the”, “till”, “to”, “up”, “via”, “with”,
> and “yet”.

So, as you see, the CSL spec *does* call for lowercasing
letters that are uppercase in the original.  If citeproc-js
doesn't do it, it may be a bug in citeproc-js?

**Comment by njbart** [comment]
Sorry, forgot about the stop words. citeproc-js does indeed lowercase these (as does pandoc-citeproc), and that’s correct.

The passage “For uppercase strings, the first character of each word remains capitalized. All other letters are lowercased.” seems to refer to all-uppercase titles. Neiter citeproc-js not pandoc-citeproc have implemented this so far (on pandoc-citeproc, see the discussion [here](https://github.com/jgm/pandoc-citeproc/issues/273)).

On parentheses, brackets, quotes, and html-like tags, the consensus on the xbiblio mailing list seems to be that none of these should affect title-casing (see [here](https://sourceforge.net/p/xbiblio/mailman/xbiblio-devel/thread/CAJgpGgAGORo22rX8wRoV2Gd1fmX3iuzbXzwm829sRQ-9i%3DMcmg%40mail.gmail.com/#msg34605413)).

**Comment by jgm** [comment]
OK, so if I understand correctly, we should leave uppercase letters as they are, except (a) in stop words, which are all lowercased, and (b) in ALLCAPS words, which should have all but the first letter lowercased.  (I really don't understand the motivation for (b) and I'd be tempted to leave it unimplemented if the other processors have.  Most common uses of ALLCAPS will be for acronyms, etc., which you'd want to leave uppercase.)

If stop words are to be lowercased, and parentheses don't affect title-casing, then in

    Essays Presented to N.R. Ker (On Art),

the "On" should turn into "on".  Is that correct behavior?

As for colons, currently a colon resets the state so that we treat the next word as the beginning of a new sentence.  I think that's generally what is wanted, right?  Certainly, though, it would be good to treat the following cases the same, however we treat them:

    <i>Test:</i> An experiment
    Test: An experiment

**Comment by njbart** [comment]
> […] and (b) in ALLCAPS words, which should have all but the first letter lowercased.

No. As far as I can tell, the passage “For uppercase strings, the first character of each word remains capitalized. All other letters are lowercased.” is meant to refer to all-uppercase titles, like, “TEST: AN EXPERIMENT”. However, citeproc-js renders this string as is, so  I do see any need for pandoc to implement this for the time being.

> […] the "On" should turn into "on". Is that correct behavior?

According to the discussion on the xbiblio list: yes.

> As for colons, currently a colon resets the state so that we treat the next word as the beginning of a new sentence. I think that's generally what is wanted, right? 

The rules from the [CSL specs](http://docs.citationstyles.org/en/stable/specification.html#title-case-conversion) [I removed the passages on all-uppercase strings for clarity] are:

> **Title Case Conversion**
> Title case conversion (with text-case set to “title”) for English-language items is performed by:
> […] the first character of each lowercase word is capitalized. The case of words in mixed or uppercase stays the same.
> […] stop words are lowercased, unless they are the first or last word in the string, or follow a colon. The stop words are “a”, “an”, “and”, “as”, “at”, “but”, “by”, “down”, “for”, “from”, “in”, “into”, “nor”, “of”, “on”, “onto”, “or”, “over”, “so”, “the”, “till”, “to”, “up”, “via”, “with”, and “yet”.

… which seems to lead to the same results as your rule – so: fine.

If a user wants to protect “On” from being lowercased by the title caser, the word should probably be wrapped in `<span class="nocase">`…`</span>`. This would also apply if an acronym happened to contain the same letters as one of the stop words, say, an organization called DOWN or OVER.

> Certainly, though, it would be good to treat the following cases the same, however we treat them:
> `<i>Test:</i> An experiment`
> `Test: An experiment`

Yes.

**Comment by jgm** [comment]
Actually, we can't do much about the `<i>test:</i>`, since the `</i>` is just parsed as raw inline HTML.

The proper way to represent this in a pandoc YAML block is:

```
---
references:
- id: test2
  title: "*Test:* An experiment: An abridgement"
---

@test2
```

But with this form, too, we get lowercase "an." That should be fixed.
