### ISSUE TITLE
Error running filter

### ISSUE THREAD

**Issue by cryptic0** [jgm/pandoc-citeproc#303]
``MacOSX 10.11.6``  
``pandoc version: 1.19.2.4``  
``pandoc-citeproc version: 0.11.1.1``  

## bib record
```bash
@ARTICLE{Wright1965a,
  author = {Wright, Sewall},
  title = {The interpretation of population structure by F-statistics with special
	regard to systems of mating},
  journal = {Evolution},
  year = {1965},
  volume = {19},
  pages = {395--420}
}
```

## test.md

Population structure analysis was carried out following [@Wright1965a].

## The commandline
```bash
pandoc test.md -o test.html --bibliography ~/library.bib --filter pandoc-citeproc

pandoc-citeproc: error running filter.
ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 42:3}
pandoc: Error running filter pandoc-citeproc
Filter returned error status 1
```

Instead, if I run as follows, there are no error messages.  But the result is not what you would expect.  The citation is inserted in text as [@Wright1965a] and there is no reference printed.

```bash
pandoc test.md -o test.html 
```

**Comment by jgm** [comment]
I wasn't able to reproduce this with either the released
or the development versions of the software...

So probably it has to do with something else in library.bib
besides the record you quote here.  If you post the whole
library.bib, I could have a look.

+++ Vikram Chhatre [Oct 29 17 16:12 ]:

**Comment by cryptic0** [comment]
@jgm Thanks for your swift response.  I had the same doubt. So I checked the encoding.  It is not utf8. Then I extracted out that single reference and put it in its own file and checked encoding again with ``tr``.  Now it's utf8 (file attached here).  But still the same error.  

If it matters, I installed both pandoc and pandoc-citeproc with homebrew.

[test.bib.zip](https://github.com/jgm/pandoc-citeproc/files/1425408/test.bib.zip)

**Comment by jgm** [comment]
With your test.bib, pandoc works fine (dev versions of pandoc and pandoc-citeproc).
```
% echo "@Wright1965a" | pandoc --bibliography test.bib
<p><span class="citation" data-cites="Wright1965a">Wright (1965)</span></p>
<div id="refs" class="references">
<div id="ref-Wright1965a">
<p>Wright, Sewall. 1965. “The Interpretation of Population Structure by F-Statistics with Special Regard to Systems of Mating.” <em>Evolution</em> 19: 395–420.</p>
</div>
</div>
```
It also works fine with the released version.  Do you get a different result using just the command above?

**Comment by cryptic0** [comment]
On my end, the output of that command looks slightly different.  The data-cites field is missing:

```bash
<p><span class="citation">Wright (1965)</span></p>
<div id="refs" class="references">
<div id="ref-Wright1965a">
<p>Wright, Sewall. 1965. “The Interpretation of Population Structure by F-Statistics with Special Regard to Systems of Mating.” <em>Evolution</em> 19: 395–420.</p>
</div>
</div>


```

**Comment by jgm** [comment]
The important thing is that you didn't get the error.  So,
you haven't yet given me precise instructions that allow me (or you)
to reproduce the error you were getting.  I can't help until
you do.

+++ Vikram Chhatre [Oct 29 17 21:54 ]:

**Comment by cryptic0** [comment]
I just wrote another MWE by writing all the same files from scratch and things seem to work.  No errors.  Quite puzzling.  I will mark this as resolved.  Thanks for your help.
