### ISSUE TITLE
Bump xml-conduit to 1.7.0?

### ISSUE THREAD

**Issue by unixpipecentipede** [jgm/pandoc-citeproc#304]
Can the accepted xml-conduit version be increased to 1.7.0?

Currently the pandoc-citeproc version in Stackage is stuck in 0.10.5.1
because of this. pandoc is already up to date (2.0.1).

https://www.stackage.org/package/pandoc
https://www.stackage.org/package/pandoc-citeproc

**Comment by jgm** [comment]
Done.  This can be closed.

+++ Vicente Vera [Nov 02 17 13:35 ]:
