### ISSUE TITLE
Update chicago-author-date.csl?

### ISSUE THREAD

**Issue by twsh** [jgm/pandoc-citeproc#305]
The citation-style-language repo has updated its chicago-author-date.csl to 17th edition: https://github.com/citation-style-language/styles/blob/master/chicago-author-date.csl Should pandoc-citeproc do the same? If so, I can make a PR.

**Comment by jgm** [comment]
Sure!  But note that some of the test results may need to
change.

+++ Thomas Hodgson [Nov 03 17 18:51 ]:
