### ISSUE TITLE
Bibtex parser failing on some comments

### ISSUE THREAD

**Issue by vtcarlino** [jgm/pandoc-citeproc#306]
Hi,

I freshly installed pandoc & pandoc-citeproc on my mac using Homebrew and I always get that error message: 
>$ pandoc --filter pandoc-citeproc --bibliography biblio.bib -s intro.md -o intro.pdf
     pandoc-citeproc: error running filter.
"stdin" (line 8813, column 23):
unexpected "\\"
expecting letter, white space or "{"
CallStack (from HasCallStack):
  error, called at src/Text/CSL/Input/Bibtex.hs:121:32 in pandoc-citeproc-0.11.1.3-H5BEGFTT3MoA89hux6ES4G:Text.CSL.Input.Bibtex
Error running filter pandoc-citeproc:
Filter returned error status 1

I use macOS Sierra 10.12.6. I tried to reinstall via the .pkg but the error remains. Any solutions ?

Thanks,

Vincent

**Comment by jgm** [comment]
This error is generated by pandoc-citeproc in trying to
parse your bibtex bibliography.

Try looking around line 8813 of this file, and you may be
able to narrow down the problem.  Note: the error messages
don't always give the most useful locations; the real
problem may occur earlier.

It would be most helpful if you could create a minimal
example -- smallest possible bibtex file that causes the
problem.  (You can also test using `pandoc-citeproc -y
biblio.bib`, which just converts it to YAML and will raise
the same error.)

**Comment by vtcarlino** [comment]
My .bib file is automaticly updated by Zotero thanks to BetterBibTeX.

This is the part of the file which causes the error:
`@comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:@Inbox\;0\;;
}`

Apparently, this is a list of all the folders and subfolders of my collection. Works fine when I remove it. Do you know how to force BBT to remove it when updating `.bib` file?

**Comment by jgm** [comment]
I don't know anything about BBT.  However, we should try to improve the parser so that it doesn't have problems with this comment.
