### ISSUE TITLE
Cannot find .bib files outside working directory

### ISSUE THREAD

**Issue by sjkiss** [jgm/pandoc-citeproc#310]
Hi: I'm a total noob; trying my best to describe the situation here. 
I have test.bib at ~/Desktop/test.bib and in ~/Documents/test/test.bib

Running

`pandoc --filter pandoc-citeproc --bibliography=~/Desktop/test.bib -o test.docx test.tex`

returns

`Could not find bibliography file: ~/Desktop/test.bib`

But running 
``pandoc --filter pandoc-citeproc --bibliography=test.bib -o test.docx test.tex``

in the working directory works beautifully. 

Is there a way to read the file from a different location?

**Comment by jgm** [comment]
https://unix.stackexchange.com/questions/146671/does-always-equal-home/146697#146697

Try $HOME instead of ~.

+++ sjkiss [Nov 30 17 16:07 ]:
