### ISSUE TITLE
Citations in footnotes use brackets, not parentheses

### ISSUE THREAD

**Issue by samueldodson** [jgm/pandoc-citeproc#315]
Hi, @jgm. My citations in footnotes are wrapped in brackets rather than parentheses --- i.e., "[Doe (n.d.)]" rather than "(Doe (n.d.))." My references in footnotes, however, are correctly wrapped in parentheses. I am using pandoc 2.1 and pandoc-citeproc 0.13. Do you know how to fix this?

Here is an example:

Input:
```{.md}

---
references:
- id: doe
  author:
    family: Doe
  title: Title
...

A sentence.^[A footnote [@doe] and @doe.]
```

Output:
```
A sentence.[1]

Doe. n.d. “Title.”

[1] A footnote [Doe (n.d.)] and Doe (n.d.).
```

**Comment by jgm** [comment]
That looks like a bug to me.  (And probably a regression --
it would be good to test with earlier versions to see where
this came in.)

+++ Samuel Dodson [Jan 14 18 08:28 ]:

**Comment by jgm** [comment]
OK.  Looks like an issue with inline footnotes in pandoc, rather than an issue in pandoc-citeproc.
```
% pandoc -t native
foo^[bar [@doe]]
[Para [Str "foo",Note [Para [Str "bar",Space,Str "[",Cite [Citation {citationId = "doe", citationPrefix = [], citationSuffix = [], citationMode = AuthorInText, citationNoteNum = 0, citationHash = 0}] [Str "@doe"],Str "]"]]]]
```
(And there may be a reason for this that I can't remember.)  IF you use a regular footnote, it will work properly.
