### ISSUE TITLE
Link Citations Without Dates When Using CSL

### ISSUE THREAD

**Issue by samueldodson** [jgm/pandoc-citeproc#317]
Hi @jgm. `pandoc-citeproc` does not link citations to bibliography entries without dates when I use the [APA Style CSL](https://github.com/citation-style-language/styles/blob/master/apa.csl). I am using pandoc 2.1.1 and `pandoc-citeproc` 0.14.

For example, try this input...

```{md}
---
references:
- id: doe
  author:
    family: Doe
  title: Title
...

A sentence [@doe].
```

...and this command: `pandoc input.md -f markdown -t native --csl https://raw.githubusercontent.com/citation-style-language/styles/41dc429393dd8405948d660bf74f16403324bd76/apa.csl --metadata link-citations=true --filter pandoc-citeproc`

My apologies if this is an issue with the CSL I am using rather than `pandoc-citeproc`. Thanks!

**Comment by jgm** [comment]
I got it to work with terms like 'n.d.' but not with
real titles.  You can open a new issue with this case.

+++ Samuel Dodson [Jan 19 18 21:15 ]:
