### ISSUE TITLE
Malformed dates from bib2json convert mode

### ISSUE THREAD

**Issue by gely** [jgm/pandoc-citeproc#321]
Previous versions of bib2json convert mode represented dates as:
  
    "issued": {"date-parts": [[2006]]}

Pandoc-citeproc 0.14 changed to:

    "issued": [{"date-parts": [2006]}]

This seem to be incorrect as dates are now missing from bibliographies generated by filter mode with the default style.

**Comment by njbart** [comment]
I’ve started seeing this, too. `pandoc-citeproc -j` converts this:

```
@article{x,
  date={2018-02-01/2018-02-02}
}
```

to this:

```
[
  {
    "id": "x",
    "issued": [
      {
        "date-parts": [
          2018,
          2,
          1
        ]
      },
      {
        "date-parts": [
          2018,
          2,
          2
        ]
      }
    ],
    "type": "article-journal"
  }
]
```

Now, two `date-parts` within the `issued` element looks very wrong …

**Comment by jgm** [comment]
Should be fixed in the latest release.  Sorry about that.

+++ Nick Bart [Feb 01 18 19:42 ]:

**Comment by gely** [comment]
Works for me. Thanks for the quick fix.
