### ISSUE TITLE
inverse pandoc-citeproc to get back to markdown citations

### ISSUE THREAD

**Issue by mbroedl** [jgm/pandoc-citeproc#323]
As people who are not friends of markdown usually also don't appreciate [@xyz2018] citation keys, but might make changes to documents (especially track changes in word, for example), for me there would be a case for converting pandoc-citeproc compiled citations back into markdown-style citations.

For example:
`(cf. Pizza et al. [2015](#ref-pizza2015))` to `[cf. @pizza2015]`
or `Peter ([2007](#ref-peter2007), p. 17)` to `[@peter2007, p.17]`

Is there such filter/addition?

Many thanks!

**Comment by jgm** [comment]
There just isn't enough information in the Word docx output
to recover even the citation key.

**Comment by mbroedl** [comment]
It seems as if the "link-citations" option actually keeps the citation key!
But I understand if it'd be too much effort. Just wondered whether such tool existed, or anyone was aware of it.

Original file:

> This is an inline reference @**adams1992mostly** and this is bracketed [@**verne1870twenty**].`

`pandoc test.md --bibliography=./library.bib -o test.docx -M link-citations=true`

Docx:

![image](https://user-images.githubusercontent.com/19365355/36945559-4e329998-1fa8-11e8-8f0b-0f9cbc7eeb93.png)

`pandoc test.docx -o test2.md --wrap=none`

Target file:

> This is an inline reference Adams (\[1992\]\(#ref-**adams1992mostly**\)) and this is bracketed (Verne \[1870\]\(#ref-**verne1870twenty**\)).
>
> Adams, Douglas. 1992. \*Mostly Harmless\*. Vol. 5. The Hitchhiker's Guide to the Galaxy. William Heinemann, UK.
> 
> Verne, Jules. 1870. \*Twenty Thousand Leagues Under the Seas: An Underwater Tour of the World\*. Pierre-Jules Hetzel.

**Comment by tstenner** [comment]
This is also something I'd be glad to have.

Mendeley inserts both the citation string as well as the data needed to recover it as a field into the document. The openxml data looks like this:

<pre><code>&lt;w:r&gt;
  &lt;w:fldChar w:fldCharType="begin"/&gt;
&lt;/w:r&gt;
&lt;w:r w:rsidRPr="00F07FBD"&gt;
  &lt;w:rPr&gt;
    &lt;w:lang w:val="en-US"/&gt;
  &lt;/w:rPr&gt;
  &lt;w:instrText&gt;<b>ADDIN CSL_CITATION { [the whole JSON-formatted bibliography data] }</b>&lt;/w:instrText&gt;
&lt;/w:r&gt;
&lt;w:r&gt; &lt;w:fldChar w:fldCharType="separate"/&gt; &lt;/w:r&gt;
&lt;w:bookmarkStart w:id="18" w:name="__Fieldmark__148_3508006993"/&gt;
&lt;w:r&gt;
  &lt;w:rPr&gt;
    &lt;w:bCs/&gt;
    &lt;w:color w:val="00000A"/&gt;
    &lt;w:lang w:val="en-US"/&gt;
  &lt;/w:rPr&gt;
  &lt;w:t&gt;(&lt;/w:t&gt;
&lt;/w:r&gt;
&lt;w:bookmarkStart w:id="19" w:name="__Fieldmark__113_3358341831"/&gt;
&lt;w:r&gt;
  &lt;w:rPr&gt;
    &lt;w:bCs/&gt;
    &lt;w:color w:val="00000A"/&gt;
    &lt;w:lang w:val="en-US"/&gt;
  &lt;/w:rPr&gt;
  &lt;w:t&gt;    <b>what's actually shown in the document</b>    &lt;/w:t&gt;
&lt;/w:r&gt;
&lt;w:r&gt;
  &lt;w:fldChar w:fldCharType="end"/&gt;
&lt;/w:r&gt;
&lt;w:bookmarkEnd w:id="18"/&gt;
&lt;w:bookmarkEnd w:id="19"/&gt;</code></pre>

The `html5` writer already does something similiar with <pre><code>&lt;span class="citation" data-cites="<b>citation-key</b>"&gt;<b>Citation: Author (Year)</b>&lt;/span&gt;</code></pre>

**Comment by jgm** [comment]
It should be possible for us to insert this instrText element, too.

**Comment by Fnorxblohon** [comment]
I am trying to reconstruct the citations that Citavi puts in.  Its instrText is a base64-encoded XML document which contains the entire bibliography data, too.  The location of the citation is a CDATA section in some element, the citation key another element.  Looks like if I get that down, Word's own markup or Mendeley's shouldn't be too hard.

**Comment by Chrismarsh** [comment]
I too would really like this. Is there any progress on this? 

My specific use case is md -> docx -> md, so the above mentioned link field method would work.

I've written a filter that finds the correct links and successfully undoes the citation, but the formatted text is posing to be a problem. If more than just the year was in the link, i.e., the entire citation, it would be trivial to replace with the markdown syntax going from docx -> md. Unfortunately I have no experience with Haskell and I have no idea where to being to change it so-as to include the authors' names in the link. Any suggestions? This would be a good short term fix for me until something for official was done.

**Comment by Chrismarsh** [comment]
@mbroedl Sorry for the slow reply, I don't seem to be getting github notifications despite being enabled.

Thanks for the detailed reply. Sounds like the direction I've been going. I had been trying to match on the first author in the text and matching against the reference, e.g., `Marsh et al. [2018](@Marsh2018) ` And match on Marsh...Marsh, and pull it apart that way. It works well until you have authors with diacritics in their names, and despite using word bounds (\b) I kept hitting partial matches, especially when using 'e.g.' in the text. Just ended up being a mess without a clear way forward.

I have a colleague who "solves" this with LaTeX in a different way. He creates a citation -> formatted lookup table, and does a search/replace in the document using that. It does assume you know the bib and csl while doing the conversion. 

>became this (errors in bold):

I don't see anything in bold?

>What kind of destroyed my motivation [...]

I've started to use Scrivener to partially get around this. I produce my manuscript in md and do md->docx to my co-authors. Then, when I receive the document back, I ensure the changes they made are ok and import the docx into Scrivener. It auto-accepts the changes, but importantly, includes the comments as comments in scrivener which I can then deal with as required. It's not ideal, but it's the best I've found. If I could inverse the citations, I could then just copy-paste into the main part of my document thus incorporating co-author changes seamlessly.

The line-break diff issue is one I've run into with latex and co-authors and I've never found a good way of dealing with it. The pandoc `--wrap=none` option when doing docx->md does help though as it ensures you're comparing just text and not line breaks. 

I assume you're thinking of highlighting the diff w/ a different color, etc within the markdown text?

>I'm happy to share my code with you if you are interested.

Sure, I would be interested in this. As all my citations are author-date without footnotes, I can likely make this work for me (diacritics not withstanding!). Is it on your github?

>Maybe one could add a preprocessor to pandoc-citeproc and save the necessary information in span classes and attributes? Are they maintained in the docx-writer?

The problem with all this being in Haskell is I struggle with the code. Coming from C++  & python, this is pretty wild stuff.

I use author-date (e.g., Marsh et al. (2018)  / (Marsh et al., 2018) ) style, so I'm thinking of modifying my cls to put the citation as emph or similar, which makes the whole thing easily targetable. I.e., I think you could have a filter iterate over the emph sections, and then check if it's a link, and if so, just replace the entire emph section withe @citation as per above. Have you tried this at all?

**Comment by mbroedl** [comment]
@Chrismarsh I'm at reply times between 10 minutes and 10 days, so don't worry about that. ;)
Sorry, I removed the 'bold' after I realised I could not make anything bold in code, but then I forgot to remove it.
Errors in my example arise mostly in inline references and when it's only the year, but these should both be bugs possible to fix.

If I may summarise the issues arising:

1. diacritics in the name
2. pre-text and post-text
3. and then there would be different citation styles
4. another one is the automatic sorting by alphabet if there is more than one author and no pre- or post-text (which hinders diff-ability)

I like the solutions of a lookup table (unless you use fuzzy matching there might not be a secure way around this).
But neither this nor marking citations as emph will ultimately help you to write some regex or text parsing which is able to strip the pre- and post-text. In the post-text, most CSLs contract keywords, such as page numbers. Without knowledge of the CSL, this is irreversible.
With the emph-method I would be worried that manual emph-wraps would screw the system over.
I thought of using some invisible characters to achieve the same as you do with the emph, but it seems that most of them are stripped in either of the writers.


Thanks for elaborating your workflow!
Until now I usually implement all changes by hand, but ideally I could diff the received file (all changes accepted) with my existing file to see all changes and merge those that I like and don't do that with those I don't like. Highlighting is not as important at the current stage, but I dream of a system where I can diff two markdown files (e.g. from github commits) and create a track changed word file from there, because sometimes my colleagues like that stuff... :/

Either in the same, or in a second step, I would then merge over comments, which I managed to transfer to footnotes or paste in the next line as HTML comments, but that sometimes causes issues with overlapping comments. I like to keep everything plain md as I work in atom.

RE: linebreaks, my current approach is to re-wrap the generated md and split lines at all non-abbreviation or bracketed semicolons. Works well enough, when I adjust my writing to it. ;)

> The problem with all this being in Haskell is I struggle with the code. Coming from C++ & python, this is pretty wild stuff.

Actually, I use python as well, it's not a big issue.
What I tend to do is to either write panflute filters that can directly feed into the pandoc toolchain, or pipe the md output through a python script before saving to disk.

I just put the code into a repo for your convenience. Please find it here: https://github.com/mbroedl/invert-pandoc-docx
You particularly want to look at [this regex](https://github.com/mbroedl/invert-pandoc-docx/blob/master/postprocessor.py#L158) (I should have used more structure when writing it) and then [this callback](https://github.com/mbroedl/invert-pandoc-docx/blob/master/postprocessor.py#L45) function on a regex match to recreate the citation.
[This](https://github.com/mbroedl/invert-pandoc-docx/blob/master/tests/test.md) is the current state of usability. You're welcome to improve the regex and the callback function, if you like!

**Comment by Chrismarsh** [comment]
@mbroedl Ok, thanks for the details! I believe I have made significant progress on this, given a few caveats.

I work in hydrology and lots of authors have diacritics in their names. I decided that having support for this is a must. This unfortunately makes the regex approach a non-starter as we've discussed.

Using your tests as a guide, I wrote a solution using the Emph approach I discussed above. I save all the meta data into a separate file which I can use to lookup the prefix and suffix, as well as citation type (e.g., SupressAuthor). This removes the need for any brittle regex and allows for diacritics in the name. It also isolates from CSL specifics.

The Emph sectioning is non-ideal, but I can't figure out a better approach. I will just tell my co-authors that the final draft won't have italic citations. I played around with `<span id="test">` and it gets saved into the docx file as a bookmark tag. However, it doesn't make it back during docx->md conversion.

This approach passes all the tests in your test case. Although citations could be reordered during md->docx, the order that they are saved in might not be the order they come out of in the docx. However, I *think* my approach should be robust against this. But if it is going to break, it'll be here
https://github.com/Chrismarsh/undo-pandoc-citeproc/blob/master/undo_citations.py#L54
where I look for the next match of the reference.

Anyway, if you have a moment I would love your thoughts on this approach
https://github.com/Chrismarsh/undo-pandoc-citeproc

I'm not sure what to do with the reference section, but can deal with that later.

The docx->md file is here
https://github.com/Chrismarsh/undo-pandoc-citeproc/blob/master/out.md

**Comment by Chrismarsh** [comment]
@mbroedl 
>Apart from an indentation error i
oh? Where? Fine on my end.

>EDIT: and also, there is some weird spacing after each list-hyphen.
Ya, that appears to be a pandoc thing -- running without the filters produces the same effect. I have no idea what causes it...

>If any of your co-authors decides to change any of the references (e.g. change e.g. to see) this won't be picked up on in your approach.

True. I was thinking more on this last night and it seems to me that combining these approaches may be the most robust approach. The support for accents via regex is just such a pain though. I will have to think about this more.

The suffix/prefix text , I think,  will be a problem if the meta data insertion approach via citeproc is done, as suggested in this thread. With author-year formatting it can be faked, e.g., `( see @myref2018)`. But not ideal. 

I almost never use the see, e.g., in the citations so _for me_ this is unlikely to be an issue, but having a reasonably robust approach would be best. I'm going to try integrating some of your regex.  

There is also the problem of a  coauthor adding an entirely new reference, and having a regex detect this and flag it will be important.

>Or you simply flag them as something in your CLI output that you need to take care of manually?!
It might be.

**Comment by mbroedl** [comment]
@Chrismarsh 

Had to check out again to reproduce it:

>   File "undo_citations.py", line 95
>    ref.append(link)
> TabError: inconsistent use of tabs and spaces in indentation

> The support for accents via regex is just such a pain though. I will have to think about this more.

I would suggest to take the compiled author string (e.g. from isolate_citations, remove brackets and the prefix, until there is a link for the year). Then you have the name of all authors, but particularly also the first author for matching.
Then you could construct a regex with that name, so you get around implementing accents.
Of course, your collaborators could remove or add accents, which would be annoying. For that you could also try fuzzy search? But that might be overkill.
Once you have that author string isolated (and the year because it's in the link), it should be easy to identify prefix and postfix and compare them with the compiled and cached version.

Not sure if you would still need my complicated regex then? Maybe you could just remove everything between first word of author match and year-link; then everything before would be comparable even to the raw markdown, and everything after should be comparable to at least the compiled version?!

> With author-year formatting it can be faked, e.g., ( see @myref2018).

Wouldn't that result in `(see My and Ref (2018))`?

> There is also the problem of a coauthor adding an entirely new reference, and having a regex detect this and flag it will be important.

Oh, true. That won't work with your approach so far, I guess... :/

**Comment by Chrismarsh** [comment]
@mbroedl 

>Had to check out again to reproduce it:

wild -- I just checked out from github and it runs perfectly. I'm not sure what to do?

>Wouldn't that result in (see My and Ref (2018))?

Perhaps I'm misunderstanding, but isn't that what you'd get from [see @myref2018]? At least with the author-date citation style.

> I dream of a system where I can diff two markdown files (e.g. from github commits) and create a track changed word file from there

If a track-changes docx based off `wdiff` output is acceptable, then send me an email (see my profile for it) and I can show you how. Bit OT for this thread I think.

>Once you have that author string isolated[...]

Good point, I'll play around with this and see.

>That won't work with your approach so far, I guess... :/

I think for the moment I'm going to flag it (via regex -- perhaps yours?) and I can deal with it manually. But I suspect devils in the details with this.

**Comment by mbroedl** [comment]
RE indentation: I assume you intended the filter for python 2 (guessing from the print import)? I just found out, that [python 3 does not allow a mix of tabs and spaces](https://legacy.python.org/dev/peps/pep-0008/#tabs-or-spaces) anymore, which seems to be the case there. Happy to do a PR, but some 'beautify code' or whatever should also do the job. Or re-indenting these two lines (bc they seem indented by tab + tab + space).

> Perhaps I'm misunderstanding, but isn't that what you'd get from [see @myref2018]? At least with the author-date citation style.

My APA-type csl converts `[see @adams1992mostly]` to `(see Adams, 1992)` and `(see @adams1992mostly)` to `(see Adams (1992))`.

I just found this [(ruby-based) citation parser](https://github.com/inukshuk/anystyle-cli) which uses machine learning techniques. Might be a nice alternative to writing a regex for a variety of citations and possible wrong citations? It seems to be able to give you the bibliographic data as well, if added.

**Comment by Chrismarsh** [comment]
@mbroedl  ah of course! Thanks. I've been slowing moving to py3, but this keeps tripping me up. Reformated in PyCharm, hopefully that does the trick

That ruby code looks interesting, perhaps something can taken from it. Doing some writting and I realized being unable to do figure and table links is also required. So I will need to add that, but it is seemingly a much easier task than this.

**Comment by pilmus** [comment]
@mbroedl is it correct that your inverse-citeproc repo is no long online? It seems to be just about what I need...

**Comment by mbroedl** [comment]
@pilmus Sorry, you are right, I must have cleaned up or something. I have put it in a gist now:

https://gist.github.com/mbroedl/63ab97f6b88432954670d4158854ad15

It used to work much better under pandoc1, but is still alright with pandoc2. (Although composite last names such as 'van der' do not work anymore.) Good luck, hope it helps you! (It does work well for my purposes, but a little manual editing is needed afterwards.)

**Comment by pilmus** [comment]
Thanks so much! I'll see if I can get it to work for my project. :)
