### ISSUE TITLE
Author-date citations with page references not separated by a semicolon

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#324]
Pandoc correctly separates multiple references to the same author with a comma. When there are also page references, they should go back to being separated with a semicolon (without adding the duplicate author name), and this is not happening.

The [Chicago Manual of Style gives the following examples](http://www.chicagomanualofstyle.org/book/ed17/part3/ch15/psec030.html):

> (Whittaker 1967, 1975; Wiens 1989a, 1989b)
> (Wong 1999, 328; 2000, 475; García 1998, 67)

With pandoc-citeproc 0.14.1.5:

```shell
pandoc -F pandoc-citeproc -t plain << EOT
---
references:
- id: 'test1'
  author:
    - family: Shakespeare
      given: William
  issued:
    - year: 1615

- id: 'test2'
  author:
    - family: Shakespeare
      given: William
  issued:
    - year: 1616

- id: 'test3'
  author:
    - family: Donne
      given: John
  issued:
    - year: 1629
---

[@test1; @test2; @test3]

[@test1, pp. 1875; @test2, pp. 110–130; @test3, pp. 10–16]

EOT
```

Result:

```
(Shakespeare 1615, 1616; Donne 1629)

(Shakespeare 1615, 1875, 1616, 110–30; Donne 1629, 10–16)
```

**Comment by jgm** [comment]
Can we determine whether this is a problem with the csl
style or a problem with pandoc-citeproc?

**Comment by adunning** [comment]
I do not think that the CSL spec even considers this problem; there's nothing about it under [Cite Collapsing](http://docs.citationstyles.org/en/stable/specification.html#cite-collapsing).

**Comment by njbart** [comment]
This has been discussed before on the Zotero forums (https://forums.zotero.org/discussion/38027/style-error-chicago-authordate-collapse/, and also https://forums.zotero.org/discussion/47396/citation-delimiters). The “collapse” bit mentioned in the first thread was a CSL style issue, and has been addressed.

Concerning the “separate by commas, except where page numbers are required” issue, @rmzelle suggested two possible fixes:

> One option would be to fall back from using any custom delimiter to the delimiter set on cs:layout whenever two neighboring years or year-suffixes are separated by additional content (like a locator). This could be a configurable toggle.

> Or we could introduce another delimiter, like after-locator-delimiter. 

The first one seems to involve tweaking the CSL processors (which does not seem to have been tried for citeproc-js so far – but I don’t see why pandoc-citeproc couldn’t), while the second would require a change in the CSL schema (which definitely has not happened yet).

**Comment by adunning** [comment]
Glad to know I'm not the first to notice it, at least. Given that (in Chicago) this can produce unreadable references, that fallback option seems ideal.

**Comment by njbart** [comment]
@fbennett has come up with a fix for citeproc-js (see [here](https://forums.zotero.org/discussion/comment/303177/#Comment_303177)). It involves tweaking the processor (note that some test cases have been added or modified) and adjusting chicago-author-date.csl as indicated [here](https://forums.zotero.org/discussion/comment/303231/#Comment_303231). (For now, I have uploaded a copy of the adjusted style [here](https://gist.github.com/njbart/077ef337c3d2f0bd82233763c2378cc2). Using this, I get the expected results with Zotero+propachi-vanilla-v1.1.120-fx.xpi and LibreOffice.)

**Comment by njbart** [comment]
Somewhat belatedly, chicago-author-date.csl (incl. de, fr, basque) have been “adjusted” in the official CSL style repository, so this issue is now fully resolved for Zotero/LO users. It’d be great if pandoc-citeproc could follow suit. As always, I’m happy to test anything that is sent my way.
