### ISSUE TITLE
Generate missing citation-label properties

### ISSUE THREAD

**Issue by coldacid** [jgm/pandoc-citeproc#326]
Some generated bibliography files (e.g. Zotero exports) don't include `citation-label` / BibTeX `key` properties, which leads to failed citations. Where a citation style makes use of `citation-label` pandoc-citeproc should generate a value for this property if one is not already available for the cited material.

**Comment by jgm** [comment]
This is one of the documented "CSL limitations" (https://citationstyles.org/authors/):

> Limited support for so-called “trigraph” or “label” styles. These styles use in-text labels, based on the author names and publishing date, to link in-text citations to bibliographic entries. An example is “[FH93]” to refer to a 1993 article by Fellner and Helmberg. While CSL has a “citation-label” variable for this purpose, CSL styles currently can’t define the rules to construct these labels. As a result, the labels have to be externally provided, outside of CSL.

I don't think pandoc-citeproc should generate these, if that's not specified by CSL or done by other CSL processors.

**Comment by coldacid** [comment]
I'll have to re-examine the project that this issue came up on to see if it's still an issue but it sounds like the solution is probably some kind of rules engine either in a pre-processor for bib files or in citeproc itself, at least until CSL styles can include such rules.

**Comment by coldacid** [comment]
On review, it looks like I was able to use Better BibTeX for Zotero and a helper script to generate the `citation-label`/`key` values I want and have them exported into the bib file consumed by pandoc-citeproc. So we're all good here.

Just in case anyone else comes across this for the same reason, here's the script (goes in the "postscript" sub-tab under "Advanced" for Better BibTeX):

```js
if (Translator.BetterCSL || Translator.BetterCSLJSON || Translator.BetterCSLYAML) {
    reference['citation-label'] = item.citekey;
} else if (Translator.BetterBibLaTeX || Translator.BetterBibTeX) {
    if (item.citekey) {
        this.add({name: 'key', replace: true, value: item.citekey});
    }
}
```

**Comment by Renader** [comment]
@jgm could you point out a possible way to approach this? 

I came along this issue when trying to use DIN 1505-2 (alphanumeric, German) which led to empty [] references in the text. I tried to work around that issue by adding a label or citation-label to the .bib files definitions, but no luck. 

My second attempt was to switch the reference in the csl file to citation-key, and assign the key to the desired short notation, didn't work either.

So custom fields wont be passed from the .bib file to the csl file, is that correct?

**Comment by jgm** [comment]
Correct.
