### ISSUE TITLE
Non-breaking spaces from CSL styles not converted to .tex

### ISSUE THREAD

**Issue by scarwire** [jgm/pandoc-citeproc#328]
Hi there!

I'm using the [Tapuscrit CSL style](https://www.zotero.org/styles/le-tapuscrit-note), which uses small non-breaking spaces (unicode character U+202F) as delimiters, for example between "p." and a page number.

When converting from markdown to LaTeX, these small U+202F spaces are correctly rendered as `\,`, and U+00A0 spaces are rendered as `~`. Pandoc does this just fine when these unicode characters appear in the body of a markdown document.

However, when these characters appear in a CSL style, pandoc-citeproc seems to render them as normal spaces. Here's a minimal working example:

```
$ pandoc -f markdown+smart -t latex --filter=pandoc-citeproc << EOT
> Foo[@item1]. Let's test a U+202F non-breaking space in the body: p. 123-145.
> 
> ---
> references:
> - id: item1
>   type: article-journal
>   author:
>   - family: Theauthor
>     given: A. B.
>   issued:
>     year: 1985
>     season: 3
>   title: The title
>   container-title: The Journal
>   page: 123-145
>   volume: 77
>   language: fr-FR
> csl: le-tapuscrit-note.csl
> ...
> EOT
``` 

This gives:

```
Foo\footnote{A. B. Theauthor, «~The title~», \emph{The Journal}, automne
  1985, vol. 77, p. 123‑145.}. Let's test a U+202F non-breaking space in the
body: p.\,123-145.

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-item1}{}%
\textsc{Theauthor} A. B., «~The title~», \emph{The Journal}, automne
1985, vol. 77, p. 123‑145.
```

As you can see: non-breaking spaces from body text are converted fine, but the ones coming from the CSL style are rendered as normal spaces. I also tried messing with the CSL style to see if the conversion would work with full non-breaking spaces (U+00A0) but they were converted to ordinary spaces, too.

I'm using pandoc 2.1.3 and pandoc-citeproc 0.14.2 on linux x64.

**Comment by jgm** [comment]
Can you give the output you expected?  (I wasn't sure exactly where the thin non-breaking spaces were expected to appear.  As you can see, you are getting regular nonbreaking spaces in the title--these are coming from pandoc-citeproc, and not from the body text.  But not in the locator.  Is it just the locator that is the problem?)

**Comment by scarwire** [comment]
Oops, looks like a false alarm. Looks like the problem was with my CSL style. Pandoc-citeproc takes U+202F in CSL and correctly renders `\,` in LaTeX.

Sorry about that! Closing the issue.
