### ISSUE TITLE
Wrong contributors suffix in inline citations

### ISSUE THREAD

**Issue by gunwald** [jgm/pandoc-citeproc#329]
In my markdown document I use two different kind of footnotes: a) If the footnote only exists of one or more references, then I use the following syntax:

> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.[See @aristoteles1983, 23; @aristoteles1984, 44 f.]

b) But some times my footnotes are more complex, that they can't be parsed by citeproc anymore as they do not consist on simple references separated by a semicolon etc. Then I use the following syntax:

> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
^[Lorem ipsum dolor sit amet, consetetur sadipscing elitr; sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua (@aristoteles1983, 23). Se also @aristoteles1984, 44 f.]

Generally this works great. I guess citeproc parses the second references as inline citations (right?). But here comes the strange thing: **Whenever I make use of method b) the delimiter between author and title, the which ought to be an ":" becomes an ",".** But only for the short citation style which is used, whenever something is being referenced to twice or more times. 

**To give an example for method a):**
*First citation:*
> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.[See Aristoteles: Nikomachische Ethik, hrsg. v. Ernst Grumach und Hellmut Flashar, übers. v. Franz Dirlmeier, (Werke in deutscher Übersetzung, Bd. 6), 8.  Aufl., Berlin 1983, S. 23.]

*Second citation:*
> Lorem ipsum dolor sit amet, consetetur.[See Aristoteles: Nikomachische Ethik., S. 23.]

This is as it should be according to my CSL. (By the way, I am using my own style but with https://www.zotero.org/styles/geistes-und-kulturwissenschaften-heilmann I get the same behavior.)

**But with method b):**
*Second citation:*
> Lorem ipsum dolor sit amet, consetetur.^[Aristoteles, Nikomachische Ethik., S. 23.]

So the ":" after Aristoteles became a ",". 

I think, this must be a bug in `citeproc` filter, as this does not happen if I am using the same CSL in LibreOffice with Zotero.
I would be glad, to help tracking it down, if someone hints me in the right direction.

**Comment by jgm** [comment]
The difference is that when you use the form `@aristoteles1983, S. 23`, the `, S. 23` is parsed as literal text, whereas in `[@aristoteles1983, S. 23]` it is parsed as a suffix from which a locator can be extracted by the filter.

What you want is rather: `@aristoteles1983 [S. 23]` which will give you an author-in-text citation with a proper suffix and locator.  I suspect this will work -- can you confirm?

**Comment by gunwald** [comment]
Thanks for the comment. I did some further testing on that issue. It is not related to the locator, at all, as I can reproduce the same behavior even with out any locator. **The problem is that citeproc uses the wrong  delimiter between author and title in some cases. It ignores the delimiter set in the style and uses always a ",".**

This problem, however, occurs only if due to complex footnotes I have to use multiple sources in one footnote, but can't separate them by a ";". I use a workaround for this scenario generating footnotes with 

`^[ … ]` and not like `[@some_reference]`. Here is a full example:

`Lorem ipsum dolor sit amet, [This is a simple footnote, with a preffix @aristoteles1983, pp 213-214; @aristoteles1984, pp 11, and a suffix.] sed diam.^[Here we have a complex footnote, as often used in humanities, here we can't use semicolons to seperate the references to the sources See @aristoteles1983, pp 213-214. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. @aristoteles1984]`

The output of the first footnote is correct:

> This is a simple footnote, with a preffix Aristoteles: _Nikomachische Ethik,_ 8 Aufl., Berlin 1983, pp 213-214; Aristoteles: _Meterologie,_ 3 Aufl., Berlin, Boston 1984, pp 11, and a suffix.

But the second is wrong:

> Here we have a complex footnote, as often used in humanities, here we can’t use semicolons to seperate the references to the sources See Aristoteles, _Politik - Buch I. Über die Hausverwaltung und die Herrschaft des Herrn über Sklaven,_, 3 Aufl., Berlin, Boston 1991, pp 213-214. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. Aristoteles, _Meterologie_.↩

As you can see, the delimiter between author and title in the first example is a ":" as expected, but became a "," in the second, which is wrong.

I understand, that I am using citeproc in a non recommended way, but I still think, it is a bug.
 
The problem is related to this issue: https://github.com/jgm/pandoc-citeproc/issues/237

**Comment by jgm** [comment]
Can you please provide a full and minimal example that displays the problem, so I can test?
(All necessary inputs and pandoc command line.)

**Comment by gunwald** [comment]
Thanks a lot for the fast reply! I set up a[ little git repository, containing all the necessary minimal files for testing:](https://github.com/gunwald/pandoc-citeproc-test)

- a markdown example: Test.md
- a biblatex file: bibliography.bib
- a CSL file which defines a ":" as delimiter: Novanimus.csl
- a bash script containing the pandoc command: pandoc.sh
- and a file representing the result of the above pandoc command: Test.odt

So the following should work:

    git clone https://github.com/gunwald/pandoc-citeproc-test.git
    cd pandoc-citeproc-test/
    ./pandoc.sh

Here is the pandoc command, if you prefer not to execute the scrip:

`pandoc --csl=./Novanimus.csl --bibliography=./bibliography.bib --number-sections --filter pandoc-citeproc -s Test.md -o Test.odt`

Please let me know if I can be of any further help traking this issue down.
