### ISSUE TITLE
'accessed' date field from bibtex not supported?

### ISSUE THREAD

**Issue by damiendr** [jgm/pandoc-citeproc#330]
I have references in bibtex format and I'm trying to use them together with this CSL file for PLoS: https://github.com/citation-style-language/styles/blob/master/plos.csl

Normally this CSL file should generate a "Cited on *date*" or "Accessed: *date*" mention for entries with a URL. But so far nothing seems to work. If I convert the references with `pandoc-citeproc -j refs.bib`, I also notice that the `accessed = {2018-05-08T11:06:30GMT}` field from bibtex is not copied over into the JSON output.

Am I doing something wrong, or does pandoc-citeproc currently not support this field?

**Comment by jgm** [comment]
Is "accessed" a valid biblatex or bibtex key?  I can't find it
documented anywhere in the biblatex documentation, or in various
bibtex cheat sheets.

**Comment by damiendr** [comment]
I don't know — I've tried 'accessed' because that was in the CSL file. My reference manager produces 'date-added' and I've seen other people use 'urldate'.

**Comment by jgm** [comment]
urldate is supported (for certain kinds of documents).
accessed is not an official biblatex field, as ar as I can see.
You could try storing your bibliography in a format that does
have an 'accessed' field, like CSL JSON or YAML.

**Comment by jeanlego** [comment]
sorry to revive this, but every internet search points back to this.
if you want to have the accessed CSL field populated for websites use 
```bib
@online{some-key,
	title = {Awesome Title},
	url = {https://www.my.url/},
	urldate = {1970-01-01}
}
```

once converted to pdf it looks like this in ACM

```
[1] Awesome Title. Retrieved January 01, 1970 from https://www.my.url/
```
