### ISSUE TITLE
Using more than one punctuation char in BibTeX key

### ISSUE THREAD

**Issue by skurzinz** [jgm/pandoc-citeproc#335]
Similar to [issue 308](https://github.com/jgm/pandoc-citeproc/issues/308) on using URLs as cite keys: 
I have a rather large (3mb) .bib file containing autogenerated keys in a format that joins e.g. `@Author-Title.-Subtitle-subtitle-words.-2017` for BibTeX keys, retaining punctuation found in the respective BibTeX fields and legitimate from a BibTeX point of view. Removing the [\.-:#$%&-+?!<>~/]+ from keys in the whole file would result in losing backward compatibility to previous .tex and other sources using that .bib, so I'd like to avoid it. 
pandoc-citeproc stops at the first punctuation character (which is of course documented behaviour: "An "internal" punctuation character is one followed by an alphanumeric.") and gobbles the rest of the key, resulting in `pandoc-citeproc: reference Author-Title not found`. 
Are there any counter-indications against allowing multiple punctuation chars in cite keys (apart from at their end, of course)? 
Thank you for your consideration (and for the time and effort that went into making this possible at all)!

**Comment by jgm** [comment]
Docs say that "internal punctuation characters" are
allowed, but they don't specify how it is determined
whether a character is "internal."  The simple
heuristic we use now is that a punctuation character
is "internal" if it is followed immediately by an
alphanumeric or underscore character.

We could probably improve this heuristic, but we need
to allow for things like

inline @citation---followed by dash.

**Comment by skurzinz** [comment]
Thanks---in fact I did not think of this particular case; I'll fork my bibliography instead.
