### ISSUE TITLE
Telling "number" from "issue" in bibtex entries

### ISSUE THREAD

**Issue by kugelblitz** [jgm/pandoc-citeproc#337]
Hello,

I have a problem with a piece of pandoc-citeproc logic that is I believe encoded in this fragment of `Bibtex.hs`:

```haskell
  (number', collectionNumber', issue') <-
     (getField "number" <|> return mempty) >>= \x ->
       if et `elem` ["book","collection","proceedings","reference",
                     "mvbook","mvcollection","mvproceedings", "mvreference",
                     "bookinbook","inbook", "incollection","inproceedings",
                     "inreference", "suppbook","suppcollection"]
       then return (mempty,x,mempty)
       else if isArticle
            then (getField "issue" >>= \y ->
                                    return (mempty,mempty,concatWith ',' [x,y]))
               <|> return (mempty,mempty,x)
else return (x,mempty,mempty)
```

The problem is, for certain bibliography styles, it is needed to have different rules for article in "journal issue" and article in "journal number". Pandoc-citeproc silently converts "number" to "issue", and if both are present, it silently merges them together with a comma separator. I believe that kind of logic can be easily done in a CSL file, if needed, while its presence in pando-citeproc damages flexibility.

**Comment by jgm** [comment]
At http://docs.citationstyles.org/en/stable/specification.html#appendix-ii-terms
I see `issue` as a locator, but not `number`.  So I'm really not sure how CSL is supposed to distinguish between journal number and journal issue.  (Nor am I clear, myself, what the distinction is supposed to be.)  Note that CSL does distinguish between the *volume* number of the journal and the *issue* number -- and pandoc does too.

**Comment by kugelblitz** [comment]
> I see `issue` as a locator, but not `number`

There is a `number` variable, though:

> **number**
> number identifying the item (e.g. a report number)

For instance, there is a `note` variable that is being taken from Bibtex `note` field. Is there a possibility to do the same with `number`?

> Nor am I clear, myself, what the distinction is supposed to be

It is just that some journals (in Russia, at least) have "numbers" (in addition to "volumes"), while some others have "issues". And one should not cite "numbers" as "issues" or vice versa. It is merely a language thing. As I said, all the logic can be implemented in the CSL is Pandoc does not discard the Bibtex data.
