### ISSUE TITLE
Problem with citing chapters of online documentation

### ISSUE THREAD

**Issue by klassegeljakt** [jgm/pandoc-citeproc#339]
I need to cite the chapters of online documentations. Given a bibtex entry:

```
@online{RustReference,
  title   = {The Rust Programming Language},
  url     = {https://doc.rust-lang.org/reference},
  author  = {{The Rust Team}},
  date    = {2017},
  urldate = {2018-03-27}
}
```

I'd like to write citations such as `[@RustReference, chap. 6]`, and generate `[1, chap. 6]`. It works for `@book` but not `@online`, is there some workaround to this problem?

**Comment by jgm** [comment]
This is probably a CSL stylesheet issue.  Your
stylesheet probably doesn't say to print the "locator"
for online content.  You could modify it, or use
another stylesheet.

**Comment by klassegeljakt** [comment]
The problem seemed to be with the CSL, I have to write `ch` instead of `chap` to make it work.
