### ISSUE TITLE
bibtex with relative path in YAML block not found. Only absolute paths work...

### ISSUE THREAD

**Issue by trenkert** [jgm/pandoc-citeproc#340]
I am trying to concatenate a number of md files to one larger md file. Each md is called article.md and lives in its own folder (numbered article01, article02...) next to its bibtex file called article.bib. 

Each md's YAML block contains the following line:

```
---
bibliography: article.bib
...
```

the script looks like this: 

```
for f in ./article*/article.md; do \
     pandoc --filter pandoc-citeproc --template=latex-templates/chapter-tex.md -t markdown_phpextra "$f"; \
     echo ""; echo ""; \
done >> ./book/complete_book.md
```

This setup does not work. pandoc warns that it doesn't find the bibliography file article.bib.

However, when I change the line in the YAML block to, for example, 

```
---
bibliography: /home/paul/work/mybook/article04/article.bib
...
```

it suddenly works.

Is there a way to make it work with relative paths as well?

**Comment by jgm** [comment]
This is really a pandoc issue, not pandoc-citeproc.
It's essentially the same as #3752.
You can use relative paths, but they're interpreted relative to the working directory, which may not be the directory containing the file you're processing.  However, you can add a directory manually to the `--resource-path` (see the manual).  You could easily modify your script to add the directory containing the file being processed.

**Comment by trenkert** [comment]
Pandoc is an incredible piece of software, thank you so  much for it. But what is truly amazing is your support and the way you explain this stuff to noobs, @jgm ! Thanks again!

**Comment by frederik-elwert** [comment]
I ran across the same issue, and I could not solve it using `--resource-path`. According to the docs, the option only affects images, so is it actually doing something with bibliography paths?

**Comment by jgm** [comment]
You might be right.  I'd have to check the pandoc-citeproc code, but don't have time at the moment.  Probably the code could be changed to be sensitive to resource-path.
What version of pandoc-citeproc are you using?

In any case, a sure workaround is to cd to the directory containing the markdown file before using pandoc; with the above Makefile this would be a trivial addition of a few characters.

**Comment by frederik-elwert** [comment]
```
$ pandoc-citeproc --version
pandoc-citeproc 0.16.2
```

cding would solve this particular problem, but in my setup, it turned out to be more complicated, as it breaks paths to templates, csl files, etc. which I would then have to adjust.
