### ISSUE TITLE
Separate suffix with colon in inline citation

### ISSUE THREAD

**Issue by wuffi** [jgm/pandoc-citeproc#341]
Citing two authors inside the same parenthesis works very nicely.Tthey only need to be separated by a semicolon: `[@Author1; @Author2]`

Separating a suffix with a semicolon from the actual citation is not possible: `[@Author1; see also fig. 1]`

Is there a way to achieve this?

**Comment by jgm** [comment]
Yes, backslash-escape the semicolon.
```
[@Author1\; see also fig. 1]
```
