### ISSUE TITLE
Bulk conversion problem

### ISSUE THREAD

**Issue by trenkert** [jgm/pandoc-citeproc#344]
This is probably not a bug but a question I cannot figure out.

I have multiple folders named "a01", "a02", "a03" etc.

Each of them contains one arbitrarily named markdown file and one arbitrarily named bibtex file. 

For instance: 

```
a05
    - blogpost.md
    - ipsum.bib

a09
    - amy.md
    - x544.bib

```

I want to bulk convert all of them, treating each md file separately and using each bibtex file in the same folder as their bibliography. I came up with the following rudimentary bash script:

```
#!/bin/bash

n=0
for f in ./a*/; do \
    (( n++ ))
    echo $n;

pandoc ./a0$n/*.md --filter pandoc-citeproc --bibliography=./a0$n/*.bib --template=textemplate.md -t markdown_phpextra -o ./output/completed_files/0$n.md
```

The interesting thing is this: without giving the path to the bibtex file, pandoc renders all the markdown files just fine. The same happens, when I specify each and every bibtex file by name in the YAML headers of each md file. 

But what I want is for pandoc to simply render each md file with each bib file as long as they are in the same folder, regardless of their file names - exactly the way pandoc does already do this with all *.md files. 

Can anybody help me?

**Comment by jgm** [comment]
Yes, I can help (sorry, it's a bit late).  Try with
```
--bibliography ./a0$n/*.bib
```
The problem is that when you use `--bibliography=./a03/*.bib`, shell doesn't know that it's only the part after `=` that is the path, so the `*` doesn't work as you'd expect.

**Comment by trenkert** [comment]
Thanks a lot! This worked!
