### ISSUE TITLE
pandoc-citeproc fails to parse \{`u}

### ISSUE THREAD

**Issue by icornelius** [jgm/pandoc-citeproc#345]
The latex command 
```
\{`u}
```
causes pandoc-citeproc to err out. See [discussion at retorquere/zotero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex/issues/1040#issuecomment-411240662).

**Comment by jgm** [comment]
It's invalid LaTeX, and it will also cause an error in LaTeX.
The correct LaTeX would be `` \`u `` or ``{\`u}``.
