### ISSUE TITLE
Customise citation links

### ISSUE THREAD

**Issue by TammoR** [jgm/pandoc-citeproc#346]
I would like to choose to link my bibliography entries to local (pdf) files instead of only the citation information at the end of the file. This would be incredibly useful when taking notes locally to quickly access the corresponding pdf files.

I tried implementing a filter to this end, but the citation information including the "#ref-bibtexkey" that I'd like to modify had different coordinates for different bibliography entries.

**Comment by jgm** [comment]
A pandoc filter is an AST -> AST transformation.  Here's the kind of AST you get from pandoc + pandoc-citeproc:
``` haskell
Pandoc (Meta ...)
[Para [Cite [Citation {citationId = "item1", citationPrefix = [], citationSuffix = [], citationMode = AuthorInText, citationNoteNum = 0, citationHash = 1}] [Str "Doe",Space,Str "(2005)"]]
,Div ("refs",["references"],[])
 [Div ("ref-item1",[],[])
  [Para [Str "Doe,",Space,Str "John.",Space,Str "2005.",Space,Emph [Str "First",Space,Str "Book"],Str ".",Space,Str "Cambridge:",Space,Str "Cambridge",Space,Str "University",Space,Str "Press."]]]]
```

Each bibliographic entry is in a Div with id `ref-XXX`, where `XXX` is the citation key.

So your filter should pattern-match on
``` haskell
Div (ident,[],[]) [Para ils] | "ref-" `isPrefixOf` ident
```
and then replace `Para ils` with
```
Para [Link ("",[],[]) ils ("mypdfs/" ++ drop 4 ident ++ ".pdf", "")
```
This will link each bibliography entry to `mypdfs/CITATIONID.pdf`.
