### ISSUE TITLE
"status" variable dropped in bibtex -> json conversion

### ISSUE THREAD

**Issue by drammock** [jgm/pandoc-citeproc#347]
Here's a one-liner showing a BibTeX record sent to `pandoc-citeproc` via stdin:
```
echo "@article{mweInPress, title = {The title}, author = {Author, First and Other-Author, Second}, journal = {The Journal}, status = {in press}}" | pandoc-citeproc -j -f bibtex
```
in the output, the "status" field is lost:
```
[
  {
    "author": [
      {
        "family": "Author",
        "given": "First"
      },
      {
        "family": "Other-Author",
        "given": "Second"
      }
    ],
    "container-title": "The Journal",
    "id": "mweInPress",
    "title": "The title",
    "type": "article-journal"
  }
]
```
meaning that even if I customize my CSL style to use the "status" field when "issued" is missing, it won't work because "status" is no longer present.  A work-around is to convert the whole BibTeX database to JSON in advance, manually edit the relevant record to restore the "status" variable, and then provide `pandoc` with the JSON bibliography file instead of the BibTeX one...  but it would be nice if that wasn't necessary.

**Comment by njbart** [comment]
AFAICT, BibTeX does not support a `status` field (no such thing mentioned in Patashnik 1988a, 1988b; or Markey 2009).

Biblatex, on the other hand, has a `pubstate` field (Lehman 2018, 24) which *is* supported by pandoc-citeproc.

---

<div id="refs" class="references">

<div id="ref-lehman:2018biblatex">

Lehman, Philipp. 2018. “The Biblatex Package.” Version 3.11. <http://mirror.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf>.

</div>

<div id="ref-markey:2009tame">

Markey, Nicolas. 2009. “Tame the BeaST: The B to X of BibTeX.” <http://tug.ctan.org/info/bibtex/tamethebeast/ttb_en.pdf>.

</div>

<div id="ref-patashnik:1988bibtexing">

Patashnik, Oren. 1988a. “BibTeXing.” <http://mirrors.ctan.org/biblio/bibtex/base/btxdoc.pdf>.

</div>

<div id="ref-patashnik:1988designing">

———. 1988b. “Designing BibTeX Styles.” <http://mirrors.ctan.org/biblio/bibtex/base/btxhak.pdf>.

</div>

</div>

**Comment by drammock** [comment]
Ah. That would explain why it gets dropped. I was assuming that any syntactically valid BibTeX file would get converted to corresponding syntactically valid JSON, it didn't occur to me that there would also be a lexical check on the BibTeX field names.  But of course there would have to be *something* in place in order to parse authors / editors differently from titles, etc.  Is there a particular reason why it's *good* to drop fields that aren't defined in the BibTeX specification?

**Comment by njbart** [comment]
Actually, pandoc-citeproc does map `pubstate` to CSL `status` even when the source is bibtex. Couldn’t you switch to using `pubstate` rather than `status` in your bibtex data?

**Comment by drammock** [comment]
:man_facepalming: of course.  Thanks for pointing to the obvious solution that I was missing.
