### ISSUE TITLE
If $HOME is not set, pandoc-citeproc fails

### ISSUE THREAD

**Issue by alexmsmartins** [jgm/pandoc-citeproc#35]
The bug manifests itself if one tries to run pandoc without $HOME being set first.

Here is the shell session that reproduces the error.

      alex@msbg8:WikiModelsServer$ pandoc --version
      pandoc 1.12.3.3
      Compiled with texmath 0.6.6, highlighting-kate 0.5.6.
      ......
      alex@msbg8:WikiModelsServer$ pandoc-citeproc --version
      pandoc-citeproc 0.3.0.1
      alex@msbg8:WikiModelsServer$ pandoc --bibliography=research.bib notes.md -o notes.pdf
      alex@msbg8:WikiModelsServer$ unset HOME
      alex@msbg8:WikiModelsServer$ pandoc --bibliography=research.bib notes.md -o notes.pdf
      pandoc-citeproc: HOME: getAppUserDataDirectory: does not exist (no environment variable)
      pandoc: Error running filter pandoc-citeproc

To contextualize, I am using tup as the build system. Tup creates a clean environment to make sure build predctability is possible. And this includes not setting $HOME. As such when tup calls the above command, an error occurs.

I am not sure if this is a pandoc-citeproc bug or a design decision. But if not depending on environment variables when they are not defined is, at all, possible, the fix would be very appreciated.

**Comment by bebraw** [comment]
@jgm We bumped into this with Travis. Related: https://github.com/bebraw/pypandoc/pull/68 . It might be nice to have more control over `pandoc-citeproc` so we can make it work in Travis environment.

**Comment by jgm** [comment]
We use `getAppUserDataDirectory` (from Haskell standard libraries) to retrieve the csl directory path (on linux, `~\.csl`, but it might be different on other systems).

This is where the error is raised -- I guess it assumes HOME is defined.

I think I can simply trap the isDoesNotExistError error.
