### ISSUE TITLE
Name order wrong for editors in specific CSL style file

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [jgm/pandoc-citeproc#351]
When invoking the CSL style `zeitschrift-fur-kunstgeschichte.csl` (https://www.zotero.org/styles/zeitschrift-fur-kunstgeschichte), pandoc-citeproc fails to put editors' family names first in the bibliography.

The style is supposed to print a citation with an author's or editor's first name followed by their last name:
`Friedrich Nietzsche (Hg.), Die Geburt der Tragödie aus dem Geiste der Musik, 1872.`;

and to print the bibliography entry with the last name first, followed by their first name:
`Nietzsche, Friedrich (Hg.), Die Geburt der Tragödie aus dem Geiste der Musik, 1872.`

However, the bibliography entry looks identical to the citation when an _editor_ is given instead of an author.
(Books with an author are being handled 'correctly' by pandoc-citeproc.)

Note that the CSL file is not the culprit: When adding a bibliography with identical entries (obtained from, say, `--bib2json`) in Word or LibreOffice Writer, the bibliography looks correct.

--------------
See for instance the following MWE:
```
% file: NamesOrder.tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[style = authoryear]{biblatex}
\usepackage{filecontents}
\begin{filecontents}{test1.bib}
  @book{Knu86,
    author = {Knuth, Donald E.},
    year = {1986},
    title = {The \TeX book},
  }
  @collection{Nie72,
  	editor = {Nietzsche, Friedrich},
  	title = {Die Geburt der Tragödie aus dem Geiste der Musik},
  	year =  {1872}
  },
\end{filecontents}
\addbibresource{test1.bib}

\begin{document}
\cite{Knu86}
\cite{Nie72}
\end{document}
```
(Then, convert the bibliography via `pandoc-citeproc -j test1.bib > test1.json` in order to be able to use the same bibliography in a word processor with Zotero directly.)

Covert via
```
~/.local/bin/pandoc NamesOrder.tex \
--bibliography=test1.json \
--csl=zeitschrift-fur-kunstgeschichte.csl \
-M lang=de-DE \
-o test.docx
```

**Comment by AlfonsoMuskedunder** [comment]
Addendum: A CSL expert wrote to me that the

> conditional wrap around that line isn't very common in CSL styles (though perfectly "legal" CSL), so that might trigger a citeproc-pandoc bug?

The lines referred to are the two lines above and below [line 76](https://github.com/citation-style-language/styles/blob/9e60a404fe3628ae1b8d1c455118d61db19d0f30/zeitschrift-fur-kunstgeschichte.csl#L76), respectively.

Indeed, when I remove them, at least the bibliography entry for an edited books look correct (but, naturally, it adds distortions elsewhere).

Could it be that pandoc-citeproc does not handle the `<choose><if ...> ... </if></choose>` construction properly...?

**Comment by jgm** [comment]
For reference, here's how the CSL gets parsed into a Style:
```haskell
      , ( "author-bibliography"
        , [ Names
              [ "author" ]
              [ Name
                  NotSet
                  emptyFormatting
                  [ ( "and" , "text" )
                  , ( "delimiter-precedes-et-al" , "never" )
                  , ( "delimiter-precedes-last" , "never" )
                  , ( "name-as-sort-order" , "first" )
                  ]
                  ""
                  []
              , NameLabel
                  Short emptyFormatting { prefix = " (" , suffix = ")" } Contextual
              ]
              emptyFormatting
              ", "
              [ Substitute
                  [ Names
                      [ "editor" ]
                      [ Name NotSet emptyFormatting [] "" [] ]
                      emptyFormatting
                      ""
                      []
                  , Choose
                      (IfThen
                         Condition
                           { isType = [ "entry-encyclopedia" ]
                           , isSet = []
                           , isNumeric = []
                           , isUncertainDate = []
                           , isPosition = []
                           , disambiguation = []
                           , isLocator = []
                           }
                         None
                         [ Names
                             [ "editor" ]
                             [ Name NotSet emptyFormatting [] "" [] ]
                             emptyFormatting
                             ""
                             []
                         ])
                      []
                      []
                  , Variable [ "title" ] Long emptyFormatting ""
                  ]
              ]
          ]
        )
```

**Comment by jgm** [comment]
> Could it be that pandoc-citeproc does not handle the `<choose><if ...> ... </if></choose>` construction properly...?

I'm coming around to this conclusion.  As you say, if you take it out and just keep the embedded names element, this works.
