### ISSUE TITLE
parsing latex commands in yaml block

### ISSUE THREAD

**Issue by trenkert** [jgm/pandoc-citeproc#353]
I have the following variable in a yaml block:

```
---
logo: '`\faTwitter`'
---
```

This is a latex command from the `fontawesome` package and it inserts the twitter logo at the point where the variable is called (which is within a tikzpicture node).

The problem is that it *only* works (kinda) with this exact combination of single quotation mark and backtick. If I change anything it simply doesn't render at all.

*However*: in the current state it renders the logo, but together with the backticks (which I don't want). In the end it looks like this:

![auswahl_230](https://user-images.githubusercontent.com/143727/46953914-73699480-d08f-11e8-8c08-17227002f50b.png)

I've tried different things like verbatim commands in yaml, but this is the only way something renders at all. 

Which would be the right way to do this?

**Comment by jgm** [comment]
http://pandoc.org/MANUAL.html#generic-raw-attribute

You don't say what output format you're targetting.  If you're targeting latex, then you should also just be able to do

```
---
logo: '\faTwitter'
...
```
but if that doesn't work, try
```
---
logo: '`\faTwitter`{=latex}'
...
```

**Comment by trenkert** [comment]
yes, my target format is Latex. And unfortunately, your suggestions don't work. The body of those files gets rendered, yet all data from the yaml blocks is ignored.

**Comment by jgm** [comment]
`logo` in YAML metadata will only do anything if you use `--standalone/-s` and a custom template that does something with the `$logo$` variable and loads the latex package needed for this macro.

**Comment by trenkert** [comment]
I realize this. I am using pandoc -s with a template using the $logo$ variable, and the template loads the latex-package. It also "works" in the example above - it just keeps the backticks for no reason..

**Comment by jgm** [comment]
OK, I can't tell what's happening from your
description. But this is not the right place to ask
questions. Please ask on pandoc-discuss, and give full
instructions for reproducing the issue, and then it's
likely someone will help you.
