### ISSUE TITLE
Implement a more advanced punctuation moving mechanism?

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc-citeproc#354]
I have encountered one problem with the way that pandoc moves punctuation around. If we have an example like this:

`"A nice quotation" [@article].`

With a bibtex file:

```
@article{article,
author = {Doe, John},
title = {Important article},
journaltitle = {Important Journal},
pages = {1-20},
year = {2018},
}
```

Pandoc with chicago-author-date.csl leads to:
"A nice quotation" (Doe 2018).

Pandoc with chicago-note-bibliography.csl leads to:

```
"A nice quotation."[^1]

[^1]: Doe, "Important article".
```

It is great that pandoc-citeproc and CSL allow switching between inline citations and note citations so easily. However, while it is the norm in America usage that commas and periods at the end of quotes go inside quoation marks, in German usage they are only placed within the quotation marks if they actually occur there in the quotation. (I think the same is true even for British usage.)

So basically we have the following options:

Final punctuation is part of the original quotation:

"A nice quotation."[^1]

If the final punctuation is not part of the original quotation, we usually have two options:
a) "A nice quotation".[^1] (my preference) 
b) "A nice quotation"[^1]. (also quite common)

So I think we would at least need a way to indicate if the punctuation mark belongs to the quotation or not.

But, things might get even more complicated since it might also be relevant if the quotation is part of another sentence:
`This sentence ends with "a quotation" [@article].`
Again, I think American usage would be:
This sentence ends with "a quotation."[^1]
Here, I would prefer:
This sentence ends with "a quotation".[^1]
Sometimes, you can find the recommendation to put the period inside the quotations marks if they are part of the original quotation, but, honestly, in this case I would tend to never put the period inside the quotation marks.

So basically, we have the problem that author date styles are much simpler in this regard. Looking at the example above, we simply can not know if the punctuation mark belongs to the quotation or not.

I know of course about `notes-after-punctuation`, but this has the downside that switching between different citation formats will require manual manipulation. So I think a more advanced punctuation moving mechanism could be highly benificial.

**Comment by jgm** [comment]
We can make this more "automatic" by making the default depend on the locale.
For example, if only American usage moves the punctuation, we can make the default be true iff locale is en-US.  To implement this, I'd need to know more about which other locales, if any, typically move punctuation in this way.

**Comment by denismaier** [comment]
I've been thinking again about the question how output agnostic writing can be done with pandoc. What do you think about the idea to provide a way to specify if the punctuation is part of the original quotation or not?

Like so:
`"A simple quotation" [@doe]\.` 
The backslash specifies that the following period is not part of the quotation and shall thus not be moved inside the quotation marks.

Or:
`"A simple quotation{.}" [@doe].`
This quotation indeed ends with a period.

I admit the syntax is ugly, perhaps there are better ideas. But that aside, I think the possibility to write in such a way that one could switch between in-text and note-based styles without changing the document source would be absolutely amazing.

**Comment by denismaier** [comment]
Just another idea that might actually be much easier and less ugly:
The current syntax for citations is this:

```
"A simple quotation" [@doe].
```
Citations are written like parenthetical citations. The assumption seems to be that this is the standard way and that this should then be converted to note-based citations afterwards. But this leads to semantic loss. It's impossible to know if the period belongs to the quotation or not.

If we simply change the syntax and the defaults to this:

```
"A simple quotation." [@doe]
"Another simple quotation". [@doe]
```

Now, it's entirely clear that in the first sentence the period is part of the quoted sentence. In the second sentence it is not. 

With a note-based citation style this is fine that way. (The space before the citation must still be collapsed, of course.) If we now change to a parenthetical citation style the punctuation must be moved after the citation.

So in this example, the mechanism for moving punctuation would work in the opposite, but I think in a less ambiguous way.

What do you think?

**Comment by jgm** [comment]
It's an interesting idea.  One could keep the current behavior (I think that would be necessary for backwards compatibility) while also adding a transformation for the case where a citation follows `."` or `".`.

**Comment by denismaier** [comment]
That would be awesome and a great enhancement for anyone writing languages other than US English.
Do you think it's indeed possible to add a new option like `--punctuatuation-after-citation` that performs that kind of transformation? Anything I can do to help here?

**Comment by jgm** [comment]
Possible, yes!  The main limitation (a severe one, I'm afraid) is developer time.

**Comment by denismaier** [comment]
Never mind. I've just found the nice [lua filter example](https://pandoc.org/lua-filters.html#examples) "Remove spaces before citations". This is already quite close to what I need. I'll have a look tomorrow if I can adapt this to my use case. (If not, I'll ask on pandoc-discuss.)

**Comment by denismaier** [comment]
Ok. This filter seems to work:

```lua
local function ends_with_punctuation(str)
  return str:sub(-1) == '.'
    or str:sub(-1) == ','
    or str:sub(-1) == ';'
    or str:sub(-1) == '!'
    or str:sub(-1) == '?'
end

local function is_punct_last_in_quote (doublequote)
  return doublequote and doublequote.t == 'Quoted' and doublequote.quotetype == 'DoubleQuote'
    and doublequote.content[#doublequote.content].t == 'Str'
    and ends_with_punctuation(doublequote.content[#doublequote.content].text)
end

local function is_quote_space_before_normal_citation (doublequote, spc, cite)
  return 
  doublequote and doublequote.t == 'Quoted' and doublequote.quotetype == 'DoubleQuote'
  and spc and spc.t == 'Space'
  and cite and cite.t == 'Cite'
  -- citationMode must be NormalCitation
  and cite.citations[1].mode == 'NormalCitation'
end

local function is_quote_punctuation_space_before_normal_citation (doublequote, punct, spc, cite)
    return 
      doublequote and doublequote.t == 'Quoted' and doublequote.quotetype == 'DoubleQuote'
      and punct and punct.t == 'Str' and (punct.text == '.'  or punct.text == ',' or punct.text == ';')
      and spc and spc.t == 'Space'
      and cite and cite.t == 'Cite'
      -- citationMode must be NormalCitation
      and cite.citations[1].mode == 'NormalCitation'
end

  
function Inlines (inlines)
  -- both loops go from end to start to avoid problems with shifting indices.

  -- doublequote punct space citation => doublequote space citation punct
  for i = #inlines-3, 1, -1 do
      if is_quote_punctuation_space_before_normal_citation(inlines[i], inlines[i+1], inlines[i+2], inlines[i+3]) then
        -- save current inline elements
        local doublequote = inlines[i]
        local punctuation = inlines[i+1]
        local space = inlines[i+2] 
        local cite = inlines[i+3]
        -- swap inline element order
        inlines[i] = doublequote
        inlines[i+1] = space
        inlines[i+2] = cite
        inlines[i+3] = punctuation
      end
    end

  -- punct doublequote space citation => doublequote space citation punct
  for i = #inlines-2, 1, -1 do
    if is_punct_last_in_quote(inlines[i]) and is_quote_space_before_normal_citation (inlines[i], inlines[i+1], inlines[i+2]) then
      -- get punctuation
      punctuation = pandoc.Str(inlines[i].content[#inlines[i].content].text:sub(-1))
      -- remove punctuation from quotation
      inlines[i].content[#inlines[i].content].text = inlines[i].content[#inlines[i].content].text:sub(1,-2)
      -- reinsert punctuation after cite element
      inlines:insert(i+3, punctuation)
    end
  end
  return inlines
end
```

I have only used it with a simple test document:

```
---
references:
- id: doe
  title: A book
  issued:
    - year: 2020
  author:
    - family: Doe
	  given: John
  type: book
---

"Punctuation inside." [@doe] 

"Punctuation inside," [@doe]
 
"Punctuation outside". [@doe]

"Punctuation outside", [@doe]
```

What do you think? Any comments, possible problems?
I'll also post on pandoc-discuss for suggestions, but shall we share the filter---once it's ready?
