### ISSUE TITLE
Add newline-delimited JSON as input/output format

### ISSUE THREAD

**Issue by nichtich** [jgm/pandoc-citeproc#357]
File extension `.ndjson` should be supported for newline-delimited CSL-JSON (one record per line).

**Comment by jgm** [comment]
Do you mean for CSL bibliographies?
Is there a standard usage of `.ndjson` for these?
If this is a fairly idiosyncratic request, then I think it's better to convert using a tool like `json-to-ndjson` rather than cluttering pandoc-citeproc with this extra format.

**Comment by nichtich** [comment]
Yes, CSL bibliographies in `.ndjson` files, so they can directly be used with pandoc-citeproc instead of having to join them to a JSON array (for instance with [ndjson-to-json](https://www.npmjs.com/package/ndjson-to-json)). These files are easier to process with standard command line tools (e.g. `wc -l` to count the number of references). As far as I understand [ndjson-conduit](https://hackage.haskell.org/package/ndjson-conduit) pandoc-citeproc would not need to parse the full bibliograpy file but filter entries from the data stream. Possible alternatives for large bibliographies:

* preprocess the bibliography
* get bibliographic items from a database (this is another issue)
