### ISSUE TITLE
Booktitle case for CSL

### ISSUE THREAD

**Issue by jedbrown** [jgm/pandoc-citeproc#358]
I believe that the case of the `booktitle` field of `@inproceeding` should be preserved regardless of `langid`. In the `biblatex-examples.bib` entry for `moraux`, if you delete the line
```
  langid       = {french},
```
or change it to `english`, the entire booktitle is shown in lower case. `bibtex` and `biber`/biblatex do not exhibit this behavior.

cf. misguided PR: https://github.com/citation-style-language/styles/pull/3760

**Comment by adam3smith** [comment]
(I suggest leaving this on hold until the linked PR on CSL is clarified; I'm not convinced citeproc-pandoc's behavior is incorrect)
