### ISSUE TITLE
Adding unnumbered class to bibliography is not always appropriate

### ISSUE THREAD

**Issue by danmackinlay** [jgm/pandoc-citeproc#359]
Some style guides (e.g. IEEE) demand that the bibliography section be numbered like a normal section.

However, as documented [in the manual](http://pandoc.org/MANUAL.html#citations) 

> Note that the `unnumbered` class will be added to this header, so that the section will not be numbered.

This default behaviour is therefore something we need to be able to suppress.

**Comment by jgm** [comment]
dan mackinlay <notifications@github.com> writes:

> This default behaviour is therefore something we need to be able to suppress.

You can.  Just add the section heading you want to the
very end of your markdown file.  Pandoc-citeproc will detect
the final  heading with no contents and use it for the
references.

**Comment by danmackinlay** [comment]
Oh! I could have sworn... Right. Nevermind. Thank you.

**Comment by danmackinlay** [comment]
No, wait, I'm not crazy. What you said is correct, @jgm if I do not use ``--pandoc-citeproc`` but rather 
``--biblatex``.

However, if I use --citeproc and --csl options to render using pandoc and citeproc,
then the last line of my markdown document
```markdown
# Acknowledgements

Thanks, mom.

# References
```
appears in the .tex output file as
```latex
\hypertarget{acknowledgements}{%
\section{Acknowledgements}\label{acknowledgements}}

Thanks, mom.

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
...
```
That asterisk is LaTeX-ese for "unnumbered".

This might merit an MVE; I will table that for after my IEEE deadline tomorrow, and in the interim, delete the asterisk by hand.

**Comment by jgm** [comment]
Sure enough: I hadn't remembered, but pandoc-citeproc
does add the `unnumbered` class even if you don't have
it.

But this should work:

    # References
    
    ::: {#refs}
    :::

**Comment by jgm** [comment]
See #1277 and commit 039d504f5ab771b9af3fddb5e94c2c4e6ae61051 for background.

**Comment by jgm** [comment]
The workaround is to use:
```
# References

::: {#refs}
:::
```
if you don't want `unnumbered`.

The header is no longer inside the div, so part of the rationale outlined in commit 039d504 is obsolete.
However, I wouldn't like to break existing documents by changing the default now.

**Comment by danmackinlay** [comment]
thanks @jgm - I am presuming we should close this then. Unless you'd like me to submit a documentation pull request?

**Comment by jgm** [comment]
Sure, if there are specific changes to the docs that would help, we'd consider them
