### ISSUE TITLE
Single quotes/apostrophes or spaces in names mess up pandoc filter output

### ISSUE THREAD

**Issue by cormacrelf** [jgm/pandoc-citeproc#360]
```
$ pandoc-citeproc --version
pandoc-citeproc 0.14.8
```

The CSL I am using (AGLC) has footnote citations like `John Smith`. The relevant CSL is:

```xml
<names variable="author">
  <name delimiter-precedes-last="never" and="text" delimiter=", " initialize="false" initialize-with=""/>
  ...
</names>
```

This works fine for most names. However, citing anyone with an apostrophe in their name messes up this scheme. I'm using a guy called `Michael L'Estrange` for this exercise.

Use a a .bib file like so:

```sh
# no-curly.bib
author = {L'Estrange, Michael}
```

First, it parses the name correctly in `--bib2yaml` mode.

```yaml
  - family: L’Estrange
    given: Michael
```

But then, as a filter, pandoc-citeproc produces the AST

```json
{ "t": "Str", "c": "L’EstrangeMichael"},{"t": "Space"}
```

If you add some curly braces, it separates the L'EstrangeMichael into two Strs but still puts them backwards. It also neglects to add a space.

```sh
# curly.bib
author = {{{L'Astname}}, Firstname}
```
```json
{ "t": "Str", "c": "L’Estrange" }, { "t": "Str", "c": "Michael" }, { "t": "Space" }
```

The correct AST is:

```json
{ "t": "Str", "c": "Michael" }, { "t": "Space" }, { "t": "Str", "c": "L’Estrange" }, { "t": "Space" }
```

I have a zip to repro the whole thing. I have written a Lua filter to fix the bug just for me, so you can open good-output.pdf to see what it's meant to look like. Also, see the other citation in there (without any quotes/apostrophes) that has correct output all the time. You will notice that the subsequent reference has the correctly parsed last name.

[lestrange-bug.zip](https://github.com/jgm/pandoc-citeproc/files/2524572/lestrange-bug.zip) (Run `./test.sh no-curly.bib` for json out + diff, `test.sh no-curly.bib pdf` for pdf output).

Bad output:

![screen shot 2018-10-29 at 20 36 14](https://user-images.githubusercontent.com/378760/47641505-5fa74d80-dbba-11e8-8c4c-66203c3890d5.png)

Good output:

![screen shot 2018-10-29 at 20 37 12](https://user-images.githubusercontent.com/378760/47641539-73eb4a80-dbba-11e8-9358-314163d581c1.png)

I should also note that the output in Zotero's preview window is correct. (I'm guessing it uses citeproc-js.)

**Edit: this appears to happen for multi-lastname (ie spaces), as well.**

Example:

```sh
# .bib
author = {Last1 Last2, First}
```

Output

```json
{ "t": "Str", "c": "Last1" }, { "t": "Space" }, { "t": "Str", "c": "Last2First" }
```

**Comment by jgm** [comment]
This seems to happen with footnote styles, but not author-in-text styles.
It must have something to do with the transformations we're doing on footnotes.

**Comment by jgm** [comment]
This probably is due to the code we added to handle Chinese names.
The test for "all byzantine" characters is apparently failing here because of the unicode punctuation.

**Comment by jgm** [comment]
Argh.  It was a typo, two transposed characters.
