### ISSUE TITLE
Translation de-DE: et. al.

### ISSUE THREAD

**Issue by bvolkmer** [jgm/pandoc-citeproc#363]
As far as I know, et. al. is also used in german citations. It is not wrong, but very uncommon to use u.a.

**Comment by jgm** [comment]
We get these locale files from CSL upstream, so that's
probably where you should direct your request.

https://github.com/citation-style-language/locales

**Comment by bvolkmer** [comment]
Thanks. I didn't know that. There the issue known. I leave the link for others with this problem:
citation-style-language/locales#123
