### ISSUE TITLE
Emphasis in titles trips up double→single quotation marks conversion if using JSON db

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#373]
Emphasized/italicized strings in titles trip up the conversion from (curly) double to (curly) single quotation marks carried out when the whole title is wrapped in an outer set of quotation marks – but only when using a JSON bib db. (No such problem with, at least, YAML and biblatex bib dbs.)

pandoc and pandoc-citeproc: latest dev

First example, using a yaml bib db:

```
cat > test.yaml << EOT
references:
- id: item1
  type: article-journal
  author:
  - family: Doe
    given: Jane
  issued:
    - year: 2018
  title: '“Some *important* quote” in a title'
EOT

pandoc -s -F pandoc-citeproc -t plain << EOT

Foo [@item1].

# References {-}

---
bibliography: test.yaml
...
EOT
```

Expected = actual output:

```
Foo (Doe 2018).

REFERENCES

Doe, Jane. 2018. “‘Some _Important_ Quote’ in a Title.”
```

Second, the same with a (content-wise identical) JSON db.

```
cat > test.json << EOT
[
  {
    "author": [
      {
        "family": "Doe",
        "given": "Jane"
      }
    ],
    "id": "item1",
    "issued": {
      "date-parts": [
        [
          2018
        ]
      ]
    },
    "title": "“Some <i>important</i> quote” in a title",
    "type": "article-journal"
  }
]
EOT

pandoc -s -F pandoc-citeproc -t plain << EOT

Foo [@item1].

# References {-}

---
bibliography: test.json
...
EOT
```

Expected output: as above

Actual output:

```
Foo (Doe 2018).

REFERENCES

Doe, Jane. 2018. ““Some _Important_ Quote” in a Title.”
```

FWIW, with a biblatex db (below), output is as expected, i.e., contains single quotes, too.

```
@article{item1,
  author = {Doe, Jane},
  date = {2018},
  title ={“Some \textit{important} quote” in a title}
}
```

**Comment by jgm** [comment]
This is already reported: jgm/pandoc#3424
Unfortunately not a trivial fix.

**Comment by jgm** [comment]
Anyway, this is probably a pandoc "add-on" anyway...does zotero/citeproc-js do better on this?

**Comment by njbart** [comment]
With `“Some <i>important</i> quote” in a title` in a Zotero title field, Zotero/citeproc-js works as expected. (Tested with LO, style: Chicago 17e author-date, language: en-US.)

**Comment by cormacrelf** [comment]
I don’t think it’s explicitly part of the CSL spec, but the existence of the “open-inner-quote” and “close-inner-quote” terms heavily implies that quotes should alternate.

**Comment by njbart** [comment]
It’s not in the CSL specs themselves (http://docs.citationstyles.org/en/stable/specification.html) or the CSL primer (http://docs.citationstyles.org/en/stable/primer.html), but close by:

From http://docs.citationstyles.org/en/stable/translating-locale-files.html#punctuation:

> When a CSL style renders a title in quotes through the use of the quotes attribute, it uses the “open-quote” and “close-quote” terms. When the title contains internal quotes, these are replaced by “open-inner-quote”, “close-inner-quote”.

**Comment by njbart** [comment]
Output from pandoc 2.11 is as expected now. Closing.
