### ISSUE TITLE
processCites' does not add references (information missing in documentation?)

### ISSUE THREAD

**Issue by andrewufrank** [jgm/pandoc-citeproc#374]
using `processCites'` does not add the references; the csl and the bibliography are in the input file (YAML) and processing the same inputs with `pandoc -f markdown -t html  --filter=pandoc-citeproc -o p1.html postWithReference.md` gives the desire output with references resolved.

I assume that I misunderstand the documentation or some critical information is not mentioned or there is a bug (in version pandoc-citeproc-0.14.8.1 - I did not see anything in closed issues relevant). Thank you for help!

I have created a small example in git@github.com:andrewufrank/hakyll-citeproc-example.git (executable `site2`) with simplified code. 

The code is: 

```
[markdownToHTML4 :: Text -> PandocIO Value
markdownToHTML4 t = do
  pandoc   <- readMarkdown markdownOptions  t
  let meta2 = flattenMeta (getMeta pandoc)

  -- test if biblio is present and apply 
  let bib = Just $ ( meta2) ^? key "bibliography" . _String
  pandoc2 <- case bib of
    Nothing -> return pandoc
    _ -> do
                res <- liftIO $ processCites' pandoc --  :: Pandoc -> IO Pandoc
                when (res == pandoc) $ 
                    liftIO $ putStrLn "*** markdownToHTML3 result without references ***" 
                return res

  htmltex <- writeHtml5String html5Options pandoc2

  let withContent = ( meta2) & _Object . at "contentHtml" ?~ String ( htmltex)
  return  withContent

getMeta :: Pandoc -> Meta
getMeta (Pandoc m _) = m](url)
```

and the input file is: 

```
---
title: postWithReference
author: auf
date: 2010-07-29
keywords: homepage
abstract: |
    What are the objects of
    ontologists .

nocite: | 
  @navratil08

bibliography: "/home/frank/Workspace8/SSG/site/resources/BibTexLatex.bib"
csl: "/home/frank/Workspace8/SSG/site/resources/chicago-fullnote-bibliography-bb.csl"
---

An example post. With a reference to [@Frank2010a] given.

## References
```

**Comment by jgm** [comment]
I don't see anything obviously wrong with that code at
first glance.  However, it's just a fragment; I can't
just run it to test.

I'd suggest creating a MINIMAL and complete example to
reproduce the problem.

**Comment by andrewufrank** [comment]
I have created small example which runs. Could you check it out?  git@github.com:andrewufrank/hakyll-citeproc-example.git
it is executable site2 (site is using Hakyll, described in the readme)

**Comment by jgm** [comment]
The problem is that you're not enabling `Ext_citations` when reading markdown.

**Comment by andrewufrank** [comment]
Thank you very much for your attention to my problem. Would it be possible to include warnings where the `processsSite` haddock commentary? I have not seen any place where this option is explained and checked the (long) list of extensions and did not understand that I had to include it.
