### ISSUE TITLE
Document use of --metadata-file option

### ISSUE THREAD

**Issue by hubgit** [jgm/pandoc-citeproc#378]
Now that [pandoc has a `--metadata-file` option](https://pandoc.org/MANUAL.html#reader-options), it would be useful to document its usage (as either JSON or YAML) in the [filter options](https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md#filter-mode) documentation.

**Comment by jgm** [comment]
I think it's okay as it is.  It says that these fields will be sought in the metadata.  If you want to know how to add things to metadata, the pandoc documentation will tell you that (as well as a lot of other things you need to know, like the proper formatting of markdown citations).

If there's a change, I think it should be to refer to the pandoc man page, as we do here:
```
(See the `pandoc` (1) man page under "Citations" for
details on how to encode citations in pandoc's markdown.)
```
Something like
```
(See the `pandoc` (1) man page under `--metadata`, `--metadata-file`,
and "YAML Metadata" for details on how to set metadata fields in
pandoc's markdown.)
```

**Comment by hubgit** [comment]
It did take a while to work out how to pass the `link-citations` and `reference-section-title` options to pandoc-citeproc, so I think it would be useful to say _something_, but I don't particularly mind what it is - the suggestion above looks good.
