### ISSUE TITLE
Support multiple citations at the same location with JATS input

### ISSUE THREAD

**Issue by hubgit** [jgm/pandoc-citeproc#380]
It seems that with Markdown input it's possible to cite multiple references at the same location by separating the identifiers with semi-colons, e.g. `[@ref1; @ref2; @ref3; @ref4; @ref5]`.

I've been trying to achieve the same with JATS input, but multiple space-separated values within the `rid` attribute are not recognised as multiple individual reference ids, e.g. `<xref ref-type="bibr" rid="ref1 ref2 ref3 ref4 ref5"/>`.

Is there a way to mark up multiple citations at the same location in JATS XML so that they're recognised by pandoc-citeproc?

**Comment by hubgit** [comment]
This seems to be an issue with pandoc's JATS reader, so I've [raised it there](https://github.com/jgm/pandoc/issues/5310).

**Comment by jgm** [comment]
Fixed in pandoc!

**Comment by hubgit** [comment]
Thanks @jgm!
