### ISSUE TITLE
punctuation-in-quote has strange behaviour

### ISSUE THREAD

**Issue by Porges** [jgm/pandoc-citeproc#383]
While investigating https://github.com/jgm/pandoc-citeproc/issues/382 I noticed that my punctuation was being moved inside the quotes, despite not having `punctuation-in-quote` set to `true` in my CSL file.

After adding `<style-options punctuation-in-quote="false" />` the punctuation is no longer moved.

According to the [CSL spec](http://docs.citationstyles.org/en/stable/specification.html#locale-options) this option is meant to default to `false`.

**Comment by Porges** [comment]
Ah – in `citeproc-pandoc` this is set on a locale basis. I’ll switch to `en-GB` to get my desired behaviour.

**Comment by Porges** [comment]
Actually something still isn't working properly:

The `en-GB` locale has `punctuation-in-quote="false"` but if I simply use `<locale xml:lang="en-GB">` then `punctuation-in-quote` is somehow `true`. Even worse it is overriding my style-local setting, so an explicit `<style-options punctuation-in-quote="false" />` has no effect.

**Comment by Porges** [comment]
It seems to be a problem with the `mergeLocales` function, but I'll investigate more later...

**Comment by dionojs** [comment]
We have a similar (maybe worse) issue  when using an OJS plugin (Citation Style Language) that uses citeproc -php.

Commas are put outside quotes for all American English citation styles.
we have `punctuation-in-quote="true" `  in the  ".../lib/locales/locales-en-US" of the plugin and the locale set to en-US in the csl style file. I also tried putting the `punctuation-in-quote="true"` in the csl style file but again it did not work.

**Comment by denismaier** [comment]
@dionojs I am not sure this is the right place for this report as it is clearly not a pandoc-citeproc issue...

**Comment by dionojs** [comment]
I apologize if it is so, but I wasn't sure where to put it.
It even took me several attempts to successfully submit the issue (I just registered in Github in order to report this).

**Comment by dionojs** [comment]
I also post it at
https://github.com/seboettg/citeproc-php/issues/84

**Comment by denismaier** [comment]
No worries, I just wanted to make sure your question get's seen by the people who need to see it.
