### ISSUE TITLE
`page-first` in csl file cannot handle non numeric pages when converting tex to docx.

### ISSUE THREAD

**Issue by jagkagd** [jgm/pandoc-citeproc#386]
Some jounals now, e.g., _Light: Science & Applications_ or _Science Advances_, use pages including non numeric characters like `e20` or `eaat2355`. But it seems that variable `page-first` in CSL file cannot be rendered by pandoc-citeproc correctly.

version: pandoc 2.6, pandoc-citeproc 0.14.5

CSL file: advanced-optical-materials.csl [https://github.com/citation-style-language/styles/blob/master/advanced-optical-materials.csl](url)

sample.bib

> 
@article{ding_metallic_2012,
title = {Metallic Subwavelength-Cavity Semiconductor Nanolasers},
  volume = {1},
  issn = {2047-7538},
  doi = {10.1038/lsa.2012.20},
  number = {7},
  journal = {Light Sci. Appl.},
  author = {Ding, K. and Ning, C. Z.},
  month = jul,
  year = {2012},
  pages = {e20-e20}
}

sample.tex
`
\cite{ding_metallic_2012}
`

command line
`pandoc -s sample.tex --bibliography=sample.bib --csl=advanced-optical-materials.csl -o paper.docx --filter pandoc-citeproc`

output
`[1] K. Ding, C. Z. Ning, Light Sci. Appl. 2012, 1.`

expected output
`[1] K. Ding, C. Z. Ning, Light Sci. Appl. 2012, 1, e20.`

**Comment by jgm** [comment]
To clarify, are you saying that `page-first` works
when the first page is all digits, but not when it
contains a letter?  Or that `page-first` never works?

**Comment by jagkagd** [comment]
> 
> To clarify, are you saying that `page-first` works when the first page is all digits, but not when it contains a letter? Or that `page-first` never works?

It works when the first page is all digits, but not when it contains a letter.
