### ISSUE TITLE
error for most CSL files from https://github.com/citation-style-language/styles

### ISSUE THREAD

**Issue by ttxtea** [jgm/pandoc-citeproc#388]
Get an error of the type

~~~
pandoc-citeproc: ParseError {errorContexts = [], errorMessage = "Failed reading: takeWhile1", errorPosition = 44:3 (2579)}
Error running filter pandoc-citeproc:
Filter returned error status 1
~~~

for most csl files from [the csl repo](https://github.com/citation-style-language/styles]. For example [this one](https://github.com/citation-style-language/styles/blob/master/the-journal-of-neuroscience.csl) fails and produces the errors above.

In fact, [this](https://github.com/citation-style-language/styles/blob/master/cell-numeric-superscript.csl) is one of the view styles that work with pandoc.

Without `csl` citeproc works very fine.

**Comment by jgm** [comment]
My guess is that you're downloading the HTML rendering of these files, not the raw CSL files.
Try this: https://raw.githubusercontent.com/citation-style-language/styles/master/the-journal-of-neuroscience.csl

**Comment by ttxtea** [comment]
Oh dear - slightly embarrassing. You are absolutely right that was it! Thanks.
