### ISSUE TITLE
Citations in parentheses in a note-based citation style add unwanted delimiters

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [jgm/pandoc-citeproc#389]
Placing a citation within parentheses in a note-based citation style adds an unwanted 'prefix' comma (and, if applicable in the respective style, a suffix dot).

Here's a small example document,
```
\cite{Pierguidi2017}
\footnote{Foo (\cite[23]{Pierguidi2017}) bar.}
\footnote{Fuh \parencite{Pierguidi2017} bah.}
```
and the bib
```
@Book{Pierguidi2017,
  author   = {Pierguidi, Stefano},
  title    = {Pittura di marmo. Storia e fortuna delle pale d'altare a rilievo nella Roma di Bernini},
  date     = {2017},
  location = {Florenz},
  series={Biblioteca dell’Archivum Romanicum. Serie 1, Storia, Letteratura, Paleografia},
  number={470},
}
```
When I convert this with, say, `pandoc TestDoc.tex --bibliography=Test.bib --csl=journal-fur-kunstgeschichte.csl -o Test.docx`, I get the output
![screenshot from 2019-03-03 18-02-56](https://user-images.githubusercontent.com/10466043/53698560-a7471b80-3dde-11e9-8643-f03df7816efb.png)

In the second footnote, both a leading comma and a following dot are added to the citation.

(In https://github.com/jgm/pandoc-citeproc/issues/385 it was stated that `\parencite{}` is treated as a 'regular' `\cite{}`, which is also apparent in the above example; so that does not appear to be an alternative to achieve the desired outcome.)

**Comment by jgm** [comment]
AlfonsoMuskedunder <notifications@github.com> writes:

> Placing a citation within parentheses in a note-based citation style adds an unwanted 'prefix' comma (and, if applicable in the respective style, a suffix dot).

Well, this is a note style, so a citation will be
formatted as a footnote.  To avoid a footnote inside a
footnote, pandoc-citeproc tries to convert this to a sentence.
In this case it ignores the surrounding context ();
maybe we could add a check for this.

But really it's better to avoid using citations inside
footnotes when you're using a note citation style.
Instead, make the whole note a citation with a prefix
and suffix.

**Comment by AlfonsoMuskedunder** [comment]
Thank you for your answer. I have to use a note style; and in the book I'm converting, lots of footnotes are quite extensive and contain several citations as well as additional text, so I think relying on prefixes and suffixes alone is not really feasible. I guess I could always reformulate the text or seek and replace the "(, " in the converted document. I just thought bringing this to attention couldn't hurt. =)

**Comment by AlfonsoMuskedunder** [comment]
I'm not sure if this is a bug, but the comma after the opening bracket still appears if the closing bracket is immediately followed by a period.

See for instance:
```
---
references:
- id: Pierguidi2017
  type: book
  author:
  - family: Pierguidi
    given: Stefano
  issued:
  - year: 2017
  title: Pittura di marmo. Storia e fortuna delle pale d’altare a rilievo nella roma
    di bernini
  collection-title: Biblioteca dell’Archivum romanicum. Serie 1, storia, letteratura,
    paleografia
  collection-number: '470'
  publisher-place: Florenz
...

<!-- ~/.local/bin/pandoc Test_parencite.md -F ~/.local/bin/pandoc-citeproc --csl=chicago-note-bibliography-with-ibid.csl -o Test_parencite.docx -->

[@Pierguidi2017, S. 23]
[^1]
[^2]

[^1]: Foo ([@Pierguidi2017, S. 23]) bar.
[^2]: Foo ([@Pierguidi2017, S. 23]).
```
This the output I see:
![Screenshot from 2019-03-09 17-49-58](https://user-images.githubusercontent.com/10466043/54074536-d4d70d80-4293-11e9-9ec3-3bf01788825c.png)

**Comment by denismaier** [comment]
Biblatex has a command `\smartcite`: It normally behaves like \footcite but like \parencite in a footnote. Perhaps pandoc-citeproc should adopt this kind of behaviour with note-based styles:

[@doe] in the text: produce a footnote
[@doe] in a note: put the citation in parentheses.

**Comment by erz96cxw** [comment]
I have the same problem. In the humanities one often uses extensive footnotes, which interlace comments and references. References are not in parentheses, but just in the text, note style. Writing in LaTeX/Biblatex one can emulate this with autocite, but the syntax is cumbersome and prone to error.

So a footnote like: 
`\footnote{It has been pointed out that blah, see \cite[32]{@smith}.}. On the other hand scholars have argued…, \cite[cf.][55]{@miller}. `

Should yield a footnote output like (and does indeed in LaTeX):
`
1 It has been pointed out that blah, see John Smith, _My Great Argument_ (Louisville, KY: Mountain Books Ltd, 2010), p. 32. On the other hand scholars have argued…, cf. Walter Miller, _The Counter-Argument_ (Boston, MA: Ivory Tower Books, 2012).
`

Unfortunately, citeproc renders both references in parentheses, and using \textcite{} creates other problems.

Luckily it is possible to get rid of the parentheses around citations in footnotes via Luafilters. Make a new filter "nopar.lua" with code: 

```
function Note(note)
  return pandoc.walk_inline(note, {Cite = function(cit)
      if (cit.citations[1].mode=='NormalCitation') and (#cit.content > 1) then 
        if cit.content[2].c=='(' then
          cit.content[2].c='';
        end
        if cit.content[#cit.content].c==')' then
          cit.content[#cit.content].c=''
        end
      end
    return cit
  end})
end
```

This needs to run **after** the citeproc filter in your pandoc command:
`pandoc --citeproc --lua-filters=nopar.lua …`

Hope this helps anybody with a similar issue.
