### ISSUE TITLE
'Ibid.' not capitalized at the beginning of a sentence when invoked within footnote

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [jgm/pandoc-citeproc#390]
In note-based citation styles with 'ibid', citations that do print as 'ibid.' and that are being invoked from within a footnote apparently do not get capitalized.

Example document:
```
\cite{Lipinska2014}
\cite{Lipinska2014}
\Cite{Lipinska2014}
\footnote{\cite{Lipinska2014}. \cite{Lipinska2014}.}
\footnote{\Cite{Lipinska2014}. \Cite{Lipinska2014}.}
\footcite{Lipinska2014}
\Footcite{Lipinska2014}
```
and example bib:
```
@book{Lipinska2014,
  location = {Leiden and Boston},
  title = {Moving Sculptures},
  subtitle = {Southern Netherlandish Alabasters from the 16th to 17th Centuries in Central and Northern Europe},
  isbn = {978-90-04-27093-0},
  pagetotal = {386},
  timestamp = {2016-08-29T13:43:40Z},
  language = {english},
  number = {2},
  series = {Studies in Netherlandish Art and Cultural History},
  author = {Lipi{\'n}ska, Aleksandra},
  date = {2014}
}
```
With `pandoc TestDoc_ebdKlein.tex --bibliography=Test.bib --csl=chicago-note-bibliography-with-ibid.csl -o Test.docx`, I get
![screenshot from 2019-03-03 19-54-56](https://user-images.githubusercontent.com/10466043/53700000-44f61700-3dee-11e9-8439-6edecd947d67.png)

Most importantly to me, irrespective of the capitalization of the cite command itself, none of the citations invoked from within an explicit `\footnote{}` are capitalized. (See footnotes 4, 5.)

Called from outside an explicit footnote, irrespective of the capitalization of the cite command `\cite`/`\autocite`, 'Ibid.' *will* be capitalized.

Only for the `\footcite` command, capitalization appears to make a difference (footnotes 6, 7).

**Comment by jgm** [comment]
The discrepancy between `\footcite` and `\Footcite` surprised me, but it turned out to be a bug in pandoc.  After the change I just made, they should both produce the uncapitalized version.

In general, pandoc's translation of biblatex citation commands to native pandoc citations is not going to be 100% accurate, because these are quite different systems.  There's no flag or parameter in a pandoc citation that says "capitalize the first letter."  So we do the best we can and translate `\Footcite` and `\footcite` the same way.

You get capitalization for regular cite commands that are being transformed into footnotes because it's a footnote style.  This is because of a general transformation we run when converting citations to notes.
It isn't run on things that are already notes.

In principle we could have our function look also for existing notes that happen to start with a citation, and apply the capitalization there, too.

**Comment by AlfonsoMuskedunder** [comment]
Thank your for taking the time to consider this. In general - to the best of my knowledge - biblatex's citation commands work independent of whether an 'in-text' or a note citation style is being loaded. Conversely, where and how a citation appears is governed by the appropriate choice of citation commands.

So when reading a LaTeX document that was written with the output of note-based citations in mind, one will probably hardly ever encounter the standard `\cite` command in the text. In other words, when you write
> You get capitalization for regular cite commands that are being transformed into footnotes because it's a footnote style.

, this rule should have rather little empirical relevance, since a LaTeX document wouldn't have been written accordingly to begin with, or am I wrong? Instead, in theses cases one will mostly see either `\footcite` or `\footnote{ [...] \cite{...} [...]}`.

> In principle we could have our function look also for existing notes that happen to start with a citation, and apply the capitalization there, too. I believe that would help with your case.

It would, yes, in those cases where a footnote starts with a citation first, which then may or may not be followed by additional text. At least in the `\footcite` use case, I guess for now I might try to add something along the lines of `\renewcommand{\footcite}{\cite}` in the source tex document to achieve the same.

But in those cases when a footnote first sees some text - ended by a punctuation mark that warrants capitalization afterwards -, which is then followed by a citation, this would still produce uncapitalized 'ibid.'s, am I wrong?

Could one test, in addition, whether a citation is preceded by a dot punctuation, indicating the end of a sentence? Or is that impossible, which you mean when you write
> There's no flag or parameter in a pandoc citation that says "capitalize the first letter."

?

P.S.: Sorry for putting so much emphasis on the capitalization of the LaTeX citation commands themselves in the original post. I think I misinterpreted the function of said capitalization.

**Comment by jgm** [comment]
> , this rule should have rather little empirical relevance, since a LaTeX document wouldn't have been written accordingly to begin with, or am I wrong? Instead, in theses cases one will mostly see either \footcite or \footnote{ [...] \cite{...} [...]}.

Yes, but this is one of the differences between citeproc and biblatex.  Biblatex allows you to produce a mix of footnote and parenthesized citations in the same document; with citeproc, it's either a footnote style (in which all citations are footnotes) or a parenthesized or numeric style.  So we do the best we can.
