### ISSUE TITLE
Cannot be built in Ubuntu 18.04

### ISSUE THREAD

**Issue by helocy** [jgm/pandoc-citeproc#395]
Please check the following build error log:

$ cabal build
Building pandoc-citeproc-0.16.1.3...
Preprocessing library pandoc-citeproc-0.16.1.3...
[ 6 of 23] Compiling Text.CSL.Util    ( src/Text/CSL/Util.hs, dist/build/Text/CSL/Util.o )

src/Text/CSL/Util.hs:163:49: error:
    • No instance for (FromJSON Inline)
        arising from a use of ‘parseJSON’
    • In the second argument of ‘fmap’, namely ‘parseJSON v’
      In the expression: inlinesToString `fmap` parseJSON v
      In an equation for ‘parseString’:
          parseString v@(Array _) = inlinesToString `fmap` parseJSON v

src/Text/CSL/Util.hs:201:14: error:
    • No instance for (Text.Pandoc.Walk.Walkable Block Block)
        arising from a use of ‘walk’
    • In the expression: walk f'
      In an equation for ‘onBlocks’:
          onBlocks f
            = walk f'
            where
                f' (Para ils) = Para (f ils)
                f' (Plain ils) = Plain (f ils)
                f' x = x

**Comment by jgm** [comment]
Not sure what's happening here, but I suggest you
update pandoc-types to 1.17.5.4.

**Comment by helocy** [comment]
I already used pandoc-types-1.17.5.4

**Comment by helocy** [comment]
> Not sure what's happening here, but I suggest you update pandoc-types to 1.17.5.4. ZhiChao Yu <notifications@github.com> writes:
> […](#)
> Please check the following build error log: $ cabal build Building pandoc-citeproc-0.16.1.3... Preprocessing library pandoc-citeproc-0.16.1.3... [ 6 of 23] Compiling Text.CSL.Util ( src/Text/CSL/Util.hs, dist/build/Text/CSL/Util.o ) src/Text/CSL/Util.hs:163:49: error: • No instance for (FromJSON Inline) arising from a use of ‘parseJSON’ • In the second argument of ‘fmap’, namely ‘parseJSON v’ In the expression: inlinesToString `fmap` parseJSON v In an equation for ‘parseString’: parseString v@(Array _) = inlinesToString `fmap` parseJSON v src/Text/CSL/Util.hs:201:14: error: • No instance for (Text.Pandoc.Walk.Walkable Block Block) arising from a use of ‘walk’ • In the expression: walk f' In an equation for ‘onBlocks’: onBlocks f = walk f' where f' (Para ils) = Para (f ils) f' (Plain ils) = Plain (f ils) f' x = x -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #395

I already used pandoc-types-1.17.5.4

**Comment by jgm** [comment]
Well, the only explanation I can think of for your error is that it's trying to link against a very old version of pandoc-types.  Turning on verbosity options in cabal should tell you exactly what version it's using.

I would strongly recommend using `cabal new-build` or `stack` instead of plain `cabal`.
