### ISSUE TITLE
erroneous extra comma in citation within parentheses

### ISSUE THREAD

**Issue by korakinos** [jgm/pandoc-citeproc#397]
```
$ pandoc --version
pandoc 2.7.1
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7
```

Using the [chicago-annotated-bibliography.csl](https://www.zotero.org/styles/chicago-annotated-bibliography) (Github wouldn't let me upload the CSL file)  style file from the Zotero Style Repository, In PDF rendering, I'm getting an extra comma and whitespace in the beginning of citations if I place them in parentheses before a comma or fullstop within a footnote. An example is probably clearer:

temp.md:
```
---
csl: CSL/chicago-annotated-bibliography.csl

---

[^footnote1]

[^footnote2]

[^footnote1]: This footnote mentions source1 ([@source1, 42]) and source2 ([@source2, 42]) within a sentence without a problem.

[^footnote2]: In this footnote source1 is mentioned in front of a comma ([@source1, 23]), and source2 in front of a fullstop ([@source2, 23]). In both cases an additional comma and whitespace are being inserted at the beginning of each citation in rendering.
```

To reproduce, copy temp.md from above, download the CSL file above and place it in the same directory, create a dummy bib file and run pandoc:
```
$ touch bogus.bib
$ pandoc   --output="temp.pdf" --bibliography="bogus.bib" "temp.md"
```

The resulting PDF is attached.
[temp.pdf](https://github.com/jgm/pandoc/files/3026486/temp.pdf)

**Comment by AlfonsoMuskedunder** [comment]
I suppose the OP uses the newest pandoc-citeproc version, because she/he differentiates between parentheses that are immediately followed by punctuation (an extra comma appears inside the parentheses) and those that are not (no additional comma appears). This is consistent with this comment: https://github.com/jgm/pandoc-citeproc/issues/389#issuecomment-471200372_

**Comment by korakinos** [comment]
```
$ pandoc-citeproc --version
pandoc-citeproc 0.16.1.3
```

**Comment by korakinos** [comment]
I believe @AlfonsoMuskedunder has the right idea and this is a duplicate of #389. I'm closing this issue
