### ISSUE TITLE
Wrong conversion of @software biblatex key

### ISSUE THREAD

**Issue by nkoester** [jgm/pandoc-citeproc#403]
I am trying to convert my bib file to json but some keys do not convert correctly:

a.bib:
```
@software{hadoop,
  author = {{Apache Software Foundation}},
  title = {Hadoop},
  url = {https://hadoop.apache.org},
  version = {0.20.2},
  date = {2010-02-19},
}
```
call:
```
$ pandoc-citeproc --bib2json /tmp/a.bib -f biblatex
[
  {
    "URL": "https://hadoop.apache.org",
    "author": [
      {
        "literal": "Apache Software Foundation"
      }
    ],
    "id": "hadoop",
    "issued": {
      "date-parts": [
        [
          2010,
          2,
          19
        ]
      ]
    },
    "title": "Hadoop",
    "type": "book",
    "version": "0.20.2"
  }
]
```

The ```@software``` key here is converted to ``` "type": "book"``` (?). The mapping table in the ```resolveKey``` function suggests to do ```"software" -> "computer software"```, but it does not seem to be applied. Forcing the format to either bibtex or biblatex does not change this. Am I doing something wrong here or could this be a bug?

Here some version infos:
```
$ pandoc-citeproc --version
pandoc-citeproc 0.16.2

$ uname -a
Linux 5.0.8-arch1-1-ARCH #1 SMP PREEMPT Wed Apr 17 14:56:15 UTC 2019 x86_64 GNU/Linux
```

**Comment by jgm** [comment]
See line 1321 for the mapping to Book. resolveKey is just used for the "genre" addition when type is e.g. "thesis." But we need the main type to be a valid CSL type. Here are the valid CSL types:
```
article
article-magazine
article-newspaper
article-journal
bill
book
broadcast
chapter
dataset
entry
entry-dictionary
entry-encyclopedia
figure
graphic
interview
legislation
legal_case
manuscript
map
motion_picture
musical_score
pamphlet
paper-conference
patent
post
post-weblog
personal_communication
report
review
review-book
song
speech
thesis
treaty
webpage
```
I don't see how to classify software here. Maybe someone else will know how this is standardly done in CSL?

**Comment by njbart** [comment]
The CSL specs indeed do not include a `software` type, nor anything that comes even close. Zotero has a “Computer Program” type – and exports it to CSL `book`. I think we just copied Zotero’s behaviour, and it’s probably the best we can do, for now.

As long as pandoc(-citeproc)’s or Zotero’s output for such items conforms to the relevant style guide’s instructions, I don’t really see a problem. If it does not, though, please file a bug report for that particular CSL style.

**Comment by jgm** [comment]
OK, closing then!
