### ISSUE TITLE
Pandoc Citeproc doesn't support citation type of "monograph"

### ISSUE THREAD

**Issue by coryschires** [jgm/pandoc-citeproc#405]
## Problem
Pandoc Citeproc fails if given a citation with a `type` of `monograph`. For example, here is a snippet of CSL-JSON that includes a `type` of `monograph`:

```
{
  "id":"8086",
  "URL":"https://scholar.harvard.edu/files/mkraft/files/kraft_2018_interpreting_effect_sizes.pdf",
  "type":"monograph",
  "title":"Interpreting effect sizes of education interventions",
  "author":[
    { "given":"M.A.","family":"Kraft" }
  ],
  "issued":{"date-parts":[[2018]]},
  "container-title":"Brown University working paper"
}
```

In my experience, the CSL-JSON spec is unfortunately loose. Thus, as far as I know, there's not a definitive list of what types should be supported / valid. Nonetheless, I think Pandoc Citeproc should support a type of `monograph`:

1. Monographs are a fairly common and long-standing medium for academic research – distinct from similar formats such as books or journal articles.
2. Browsing Crossref data, I sorta frequently see a type of `monograph`, suggesting this is a common type used by scholarly publishers.

### Steps to reproduce
Pandoc version: 2.7.3
Files: [jats-example-files.zip](https://github.com/jgm/pandoc-citeproc/files/3303797/jats-example-files.zip)

1. `pandoc -s --metadata-file metadata.json --bibliography bib.json --filter pandoc-citeproc --csl jats.csl --to jats example.md -o output.xml`
2. You will see the following error message:

> Error reading bibliography /app/public/jats-example-files/bib.json Error in $[0].type: 'monograph' is not a valid reference type
> Error running filter pandoc-citeproc:
> Filter returned error status 1

## Solution
Ideally, citations with a `type` of `monograph` would just work, same as other types (e.g. `journal-article`, `book`, etc`).

Let me know if there's anything I can do to help resolve this issue. And thanks for maintaining this library!

**Comment by njbart** [comment]
> Thus, as far as I know, there's not a definitive list of what types should be supported / valid. 

Yes there is: http://docs.citationstyles.org/en/1.0.1/specification.html#appendix-iii-types. And `monograph` is not included in this list, so this isn’t a pandoc-citeproc bug.

I’m afraid the only solution when faced with non-standards-conforming CSL JSON data is to preprocess these yourself.

**Comment by coryschires** [comment]
Well, I stand corrected! Thanks for letting me know. 

I will update my code as necessary.

**Comment by coryschires** [comment]
Also, annoying that Crossref doesn't observe / enforce this list?! But that's just me griping.
