### ISSUE TITLE
Apply formatting to the reference-section-title

### ISSUE THREAD

**Issue by dagostinelli** [jgm/pandoc-citeproc#407]
In my case, I'm trying to output a document in MLA style.  In this style, the references area is to be labeled "Works Cited" and the section header is to be centered, not bold.  It does not appear that pandoc-citeproc permits styling to the section header.  Is that correct?  If so, I'd like to request that it does.  Here is an example:

**mla-template.tex**
```
\documentclass[12pt,letterpaper]{article}
\usepackage{ifpdf}
\usepackage{hyperref}
\usepackage{mla}
\begin{document}
\begin{mla}{$firstname$}{$lastname$}{$instructor$}{$course$}{$date$}{$title$}
$body$
\end{mla}
\end{document}
```

**essay.md**
```
---
firstname: Charlie
lastname: Brown
instructor: Mrs. Teacher
course: Biology 1
date: July 15, 2019
title: On Promises
bibliography: essay.bib
---

Lorem ipsum (@pizza2000identification) dolor sit amet, consectetur adipiscing elit. Ut in tellus nibh. Phasellus ultrices rhoncus lectus in ornare. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut in molestie quam. Integer fringilla leo at dui sagittis, ut rhoncus elit dictum. Suspendisse non enim neque. Etiam congue quam sit amet lacus venenatis tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus sed lacus pulvinar, hendrerit justo a, molestie orci. Curabitur euismod nunc ut interdum porta. Quisque imperdiet imperdiet tempor. Praesent ac mattis magna.
```

**essay.bib**

```
@article{pizza2000identification,
  title={Identification of vaccine candidates against serogroup B meningococcus by whole-genome sequencing},
  author={Pizza, Mariagrazia and Scarlato, Vincenzo and Masignani, Vega and Giuliani, Marzia Monica and Arico, Beatrice and Comanducci, Maurizio and Jennings, Gary T and Baldi, Lucia and Bartolini, Erika and Capecchi, Barbara and others},
  journal={Science},
  volume={287},
  number={5459},
  pages={1816--1820},
  year={2000},
  publisher={American Association for the Advancement of Science}
}
```

`$ pandoc -s essay.md -o essay.pdf --template=mla-template.tex --filter pandoc-citeproc -M reference-section-title="Works Cited"`

**Comment by jgm** [comment]
Items passed in with `-M` are just treated as strings. Two possible solutions:

1. Instead of using `-M` on command line, add `reference-section-title` to your YAML metadata:

```
reference-section-title: Works *cited* with **formatting**
```

2.  Don't use it at all; instead, end your document with a section heading (see the pandoc-citeproc man page).

**Comment by dagostinelli** [comment]
In the standard MLA style, the section header "Works Cited" needs to be centered with no bold. That's the issue here in a nutshell.

**Comment by dagostinelli** [comment]
Based on your solution of not doing it at all, I decided to put some inline latex right in the markdown.  So, at the bottom of the .md file, I added:

```
\newpage {\centering Works Cited\par}
\leftskip=2em
\parindent=-2em
```

This accomplished what I wanted.  Works Cited is now centered with no bold.  Also, the references now have hanging indent (what I wanted) 

It's a drag to have to include those three lines in every .md file.  They belong in the template file.   I don't see a way to do that -- but I think that's a different issue.

**Comment by jgm** [comment]
"Darryl T. Agostinelli" <notifications@github.com> writes:

> It's a drag to have to include those three lines in every .md file.  They belong in the template file.   I don't see a way to do that -- but I think that's a different issue.  

You could use a lua filter to insert them.
