### ISSUE TITLE
<group delimiter=", " /group> in CSL style is not rendered

### ISSUE THREAD

**Issue by raphgauthier** [jgm/pandoc-citeproc#414]
Hi everybody,

I have encountered an issue when trying to set a delimiter between author and date in a inline citation. 

I use `pandoc --version` 2.7.3 and `pandoc-citeproc --version` 0.16.2 on Fedora 30.

My command line is:
`pandoc -s --bibliography library.bib --filter pandoc-citeproc --csl apa.csl 02_bibliographie.md -t html -o test.html`

where apa.csl is the following [file](https://github.com/jgm/pandoc-citeproc/blob/5051575d8376debf78c9f3d1ca0008f64d814216/tests/apa.csl), modified from line 437 to 449 with the following citation layout: 

```xml 
<citation et-al-min="3" et-al-use-first="1" et-al-subsequent-min="3" et-al-subsequent-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true" collapse="year" givenname-disambiguation-rule="primary-name">
    <sort>
      <key macro="author"/>
      <key macro="issued-sort"/>
    </sort>
    <layout delimiter="; ">
      <group delimiter=", ">
        <text macro="author-short"/>
        <text macro="issued-year"/>
        <text macro="citation-locator"/>
      </group>
    </layout>
  </citation>
```
The received outputs are:
>Jondreville & Dourmad 2005
>Dourmad et al. 2012
>Dourmad et al. 1997 
>Deluyker et al. 1990

where we would expect:

>Jondreville & Dourmad, 2005
>Dourmad et al., 2012
>Dourmad et al., 1997 
>Deluyker et al., 1990

with ',' as group delimiter between author(s) and issued year.

When using the same apa.csl with Mendeley LibreOffice plugin and LibreOffice Writer, the delimiter is correctly rendered.

Do you know what's happenning ?
Thanks

**Comment by raphgauthier** [comment]
Moreover, I have just discovered that playing with the layout options lead to strange results.
With this code:

```xml
<citation et-al-min="3" et-al-use-first="1" et-al-subsequent-min="3" et-al-subsequent-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true" collapse="year" givenname-disambiguation-rule="primary-name">
    <sort>
      <key macro="author"/>
      <key macro="issued-sort"/>
    </sort>
    <layout prefix="(" suffix=")" delimiter="; ">
      <group delimiter=", ">
        <text macro="author-short"/>
        <text macro="issued-year"/>
        <text macro="citation-locator"/>
      </group>
    </layout>
  </citation>
```

the result is 
>Deluyker et al. (1990)

where we would expect 
>(Deluyker et al., 1990)

**Comment by njbart** [comment]
Please always (!) provide an [MWE](https://stackoverflow.com/help/minimal-reproducible-example).

That being said, I’ll try a stab in the dark: You’re not using `@deluyker1990` rather than `[@deluyker1990]` in your md file, are you?

**Comment by raphgauthier** [comment]
Thank you @njbart. Indeed, I used `@deluyker1990` instead of `[@deluyker1990]`.... My apologies
