### ISSUE TITLE
pandoc-citeproc fails on Linux: "Could not find locale data for C-UTF"

### ISSUE THREAD

**Issue by dhimmel** [jgm/pandoc-citeproc#420]
As reported in https://github.com/manubot/manubot/issues/167, calling `pandoc-citeproc --bib2json` on some Linux systems results in the following error:

```
pandoc-citeproc: Could not find locale data for C-UTF
```

I believe the error is printed by this line of the source code:

https://github.com/jgm/pandoc-citeproc/blob/24fad3f764ed1840c8a166e15b474156d5838491/src/Text/CSL/Data.hs#L44

We have experienced this error on two occasions, both using the version of pandoc-citeproc that is bundled with pandoc 2.7.3:

1. calling `pandoc-citeproc --bib2json` via a subprocess in python on ubuntu-latest via GitHub Actions. pandoc was installed using `dpkg --install` here. [build log](https://github.com/dhimmel/manubot/runs/276607154#step:8:208)
2. calling `pandoc-citeproc --bib2json` via a subprocess in python on linux via AppVeyor. Pandoc was installed via conda here. [build log](https://ci.appveyor.com/project/olgabot/primate-brain-organoid-paper/builds/28554556#L403)

Note that the error does not occur on our Travis CI linux builds nor on local linux builds. So perhaps it has something to do with how locales are set for certain CI-optimized linux distros.

I tried lot's of workarounds in https://github.com/manubot/manubot/pull/136 and couldn't figure out any workarounds for this error. @jgm any suggestions?

**Comment by jgm** [comment]
What does `locale` say on your system?

**Comment by dhimmel** [comment]
On the [GitHub Actions build](https://github.com/dhimmel/manubot/commit/664b4ec748f9cd201597b4110e445fa9c293409d/checks?check_suite_id=292383870#step:2:7), `locale` returns:

```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by dhimmel** [comment]
Thanks @jgm for the fix in https://github.com/jgm/pandoc-citeproc/commit/ed70000e20527057aa2df49a9facb5439346224c. In the near-term, is there a way to set our locale information to avoid triggering the error?

**Comment by jgm** [comment]
Sure, you could export `LANG=en_US.UTF-8`.
