### ISSUE TITLE
How can I add non-standard variables?

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc-citeproc#421]
Not a real issue but where would I add non-standard variables to pandoc-citeproc or custom item types?
Currently, pandoc-citeproc seems to ignore variables it does not know.

**Comment by nathanlesage** [comment]
You mean variables that you can pass to Pandoc, e.g. with a switch `--variable=value`? Did you either try a YAML frontmatter or add them to the command in the preferences?

**Comment by jgm** [comment]
That's right, pandoc-citeproc parses CSL files to a structure representing a Style, so things that can't be represented in that structure are just ignored.  There is currently no way aronud this limitation.

**Comment by denismaier** [comment]
But I guess I could add things in reference.hs and then compile from source, right? Will this override the already installed version or will I end up with two versions? If I end up with two versions, is there a best practice to make sure the right one is used?

**Comment by denismaier** [comment]
Or are there more places where I need to add a custom CSL variable?

**Comment by denismaier** [comment]
I have now managed to add a custom type bookinbook. It works if I use the filter option with explicit paths. But the standard behaviour seems to be that pandoc uses its own version of pandoc-citeproc even though my version is started when called from the command line. How can I change that?

**Comment by jgm** [comment]
No, pandoc will just use the version in your path.  I'm not sure what is happening here, but maybe the path is set differently in the environment where you run pandoc?

**Comment by denismaier** [comment]
I'll investigate. I'm running both from the same command line.

**Comment by denismaier** [comment]
Another question: a custom item type w

**Comment by denismaier** [comment]
Oh and I'm on Windows if that makes a difference.

**Comment by jgm** [comment]
It probably does. Try setting the path in the registry if you have only set it in the terminal.

**Comment by denismaier** [comment]
I've set it via system preferences and in the terminal. Same results. What helps is renaming the original pandoc-citeproc binary. Are you sure pandoc isn't prioritising its own directory, and starting lookups in the path only if the filter isn't found there?

**Comment by jgm** [comment]
Sorry, you're right.
From the manual:
```
    In order of preference, pandoc will look for filters in

     1. a specified full or relative path (executable or
     non-executable)

     2. `$DATADIR/filters` (executable or non-executable)
     where `$DATADIR` is the user data directory (see
     `--data-dir`, above).

     3. `$PATH` (executable only)
```
So if you have an executable filter in the working directory, it will use that.

**Comment by denismaier** [comment]
I'll test later. Is there a difference between system path and user path settings?
