### ISSUE TITLE
What is the mapping between bibtex @ entry types, and CSL types?

### ISSUE THREAD

**Issue by dfkotz** [jgm/pandoc-citeproc#423]
I've searched this repo, and the web, for some documentation explaining how bibtex entry types (like @article, @misc, @webpage) are translated into CSL "type" values.  Where might I find that documentation?

I'm also looking for the mapping between bibtex field names (like howpublished, abstract) and CSL variables.  Where might I find that documentation?

I am using pandoc-citeproc to produce an HTML version of a bibtex file, and crafting a custom CSL style.. so I need to know how the bibtex will be represented in CSL variables.

**Comment by denismaier** [comment]
I don't think there is documentation. I guess you'd have to look in the sources.

**Comment by denismaier** [comment]
Here: https://raw.githubusercontent.com/jgm/pandoc-citeproc/master/src/Text/CSL/Input/Bibtex.hs

Search for an item type to find the mappings. It's easy enough to understand even for someone without Haskell knowledge (like me)...

**Comment by njbart** [comment]
Exactly. In addition, `pandoc-citeproc -y example.bib` is useful for double-checking.

**Comment by dfkotz** [comment]
Thanks Denis and Nick - both tips were very helpful!

On Nov 19, 2019, at 12:40 PM, Nick Bart <notifications@github.com<mailto:notifications@github.com>> wrote:


Exactly. In addition, pandoc-citeproc -y example.bib is useful for double-checking.
