### ISSUE TITLE
Problem with container-author with pandoc-citeproc

### ISSUE THREAD

**Issue by microniko** [jgm/pandoc-citeproc#425]
I think`pandoc-citeproc` donesn't recognize `container-author` (author of book when you quote an other of a book) BibTeX use « `collaborator` » term.

I'm using `apa-no-ampersand.csl` (from[CSL website](https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa-no-ampersand)).

BibTeX of the chapter :

```
@incollection{carteronVolontairesPourNuit2008,
	abstract = {...},
	address = {{Toulouse}},
	author = {Carteron, Hélène},
	booktitle = {{Pourquoi travaillons-nous~?}},
	collaborator = {Linhart, Daniele},
	doi = {10.3917/eres.linha.2008.01.0239},
	file = {},
	isbn = {978-2-7492-0879-4},
	language = {FR},
	pages = {239–264},
	publisher = {{ERES}},
	series = {{Clinique du travail}},
	title = {{8. Volontaires pour la nuit : des ouvrières de l'industrie laitière}},
	year = {2008}
}
```
It works in Zotero preview :
 

![zotero](https://user-images.githubusercontent.com/3257805/69884923-ffae3980-12da-11ea-9721-7a5bd56fcdb5.png)

But not in a PDF :

![pdf](https://user-images.githubusercontent.com/3257805/69884884-c4ac0600-12da-11ea-9690-2565eeb75a1b.png)

```
$ pandoc --version
pandoc 2.2.1
```

**Comment by jgm** [comment]
Can you point to documentation on the `collaborator` field?  I see `collaborator` as a possible value for `editortype` in biblatex, but not as a field in its own right.  And I don't see it in bibtex docs I've looked at.

**Comment by jgm** [comment]
I think that if you use `editor` instead of `collaborator` you'll get precisely the output you say you want.

**Comment by denismaier** [comment]
Biblatex`s equivalent for `container-author` is `bookauthor`. Perhaps you might want to try this.

**Comment by microniko** [comment]
@denismaier : you're right. `bookauthor` works. :+1: 
 
Now, I have to figure out how to tell Zotero how to export this field correctly  _(If you have an idea :angel: )_ !

**Comment by denismaier** [comment]
Zotero Better Bibtex should do the job.

**Comment by microniko** [comment]
I'm using BBT. Perhaps this is a bug in BBT,?!
