### ISSUE TITLE
superscript citations (eg Nature style) appearing after punctuation instead of before

### ISSUE THREAD

**Issue by samuelmehr** [jgm/pandoc-citeproc#433]
Hi, I'm using the standard Nature csl (https://www.zotero.org/styles/nature) but citations are rendering abnormally, appearing after preceding punctuation instead of in the location specified in R Markdown.

For example, the text `experiences [@Paper8; @Paper9; @Paper10].` renders as in the following image:
<img width="246" alt="Screen Shot 2020-01-13 at 4 03 22 PM" src="https://user-images.githubusercontent.com/41483946/72300373-7acf8180-36c8-11ea-8c78-0577cb628cea.png">

The rendered text "8-10" should appear before the period, as is Nature house style, but appears after. This doesn't appear to be affected by adding `lang: en-UK` to the yaml header.

**Comment by jgm** [comment]
Put
```
notes-after-punctuation: false
```
in your metadata.

**Comment by samuelmehr** [comment]
ah brilliant! thanks :D
