### ISSUE TITLE
Label elements should never be rendered when the variable is empty

### ISSUE THREAD

**Issue by nchachereau** [jgm/pandoc-citeproc#437]
The CSL specification states about the `label` element: 

> The `label` rendering elements outputs the term matching the variable selected with the required variable attribute, which must be set to “locator”, “page”, or one of the number variables. The term is only rendered if the selected variable is non-empty.
> -- [source](https://citation-style-language.readthedocs.io/en/stable/specification.html#label)

Hence, given the minimal document and style given below, one would expect the following output:

> John Smith, Some Book, Lausanne, 2009

Instead, we get:

> John Smith, Some Book, Lausanne, 2009, pages

Here is the **test case**.

_minimal-test-style.csl:_
```xml
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="note" default-locale="en-US" version="1.0">
  <info>
    <title>Minimal style to reproduce bug</title>
    <id>http://www.example.org/styles/minimal-test-style</id>
    <author>
      <name>Nicolas Chachereau</name>
      <email>nicolas@nchachereau.ch</email>
    </author>
    <updated>2020-01-27T14:27:45+01:00</updated>
  </info>
  <citation>
    <layout>
      <group delimiter=", ">
        <names variable="author"/>
        <text variable="title"/>
        <text variable="publisher-place"/>
        <date variable="issued" form="numeric" date-parts="year"/>
        <group delimiter="&#160;">
          <number variable="number-of-pages"/>
          <label variable="number-of-pages"/>
        </group>
      </group>
    </layout>
  </citation>
</style>
```

And Markdown file:
```markdown
---
references:
- id: hirt2009
  author:
    - family: Smith
      given: John
  issued:
    - year: 2009
  publisher: Publishing House
  publisher-place: Lausanne
  title: >-
    Some Book
  type: book
csl: minimal-test-style.csl
---

> Here is a quote. [@hirt2009]

```

I stumbled upon this problem because I am one of the authors of the [infoclio-de.csl](https://www.zotero.org/styles/infoclio-de?source=1) style and a user reported to me the problem that using the style with pandoc led to strange mentions of "Bd." (abbreviation for "Band", German for "volume").

However, this does not happen with all possible values of `variable` on the `label` element. It seems to work with `locator`, `issue` (tested on type: article-journal), and `volume`, but not with most (all?) other values, such as `collection-number`, `edition`, `number-of-pages` and `number-of-volumes`.

(While debugging this problem, I noticed an inconsistency in the CSL specification: most variables that can be selected with `label` are not listed in the [Terms appendix of the specification](https://citation-style-language.readthedocs.io/en/stable/specification.html#appendix-ii-terms), while the documentation about localizing terms seems to state that the name `attribute` can only be set to one of the terms listed in that Appendix. Furthermore, it is unclear what is meant by "the term matching the variable". This has not prevented the definition of the term `number-of-pages` in [the official CSL locale for en-US](https://github.com/citation-style-language/locales/blob/master/locales-en-US.xml). In the infoclio-de style, I defined the term `number-of-volumes`.  Furthermore, the bug in pandoc-citeproc is apparently unrelated to this inconsistency, as it also happens with `edition`, even though that term is listed in the Appendix.)

It would be great if pandoc-citeproc would simply only render the `label` element when the selected variable is non-empty, just like citeproc-js.

**Comment by jgm** [comment]
Fixed, thanks!

**Comment by nchachereau** [comment]
Wow! That was fast! Thank you!
