### ISSUE TITLE
Using a div with #refs in org-mode

### ISSUE THREAD

**Issue by credmp** [jgm/pandoc-citeproc#438]
I am using org-mode as my input for a document. When using markdown I can use `<div id="#refs"></div>` to insert the list of references in the place that I want.

With org-mode this behaviour does not work, the div is included in the pdf instead of the reference list. 

I did find the `reference-section-title` option, which allows the setting of the header, but I need to add appendixes afterwards, which does not seem possible without the div, which is not something supported by org-mode.

**Comment by tarleb** [comment]
Raw HTML in org-mode is not parsed into pandoc's internal format. Try this instead:

``` org
#+ATTR_HTML: :id refs
#+BEGIN_bibliography
#+END_bibliography
```

**Comment by credmp** [comment]
That works! Thank you very much.
