### ISSUE TITLE
'accessed' does not work with .bib

### ISSUE THREAD

**Issue by jeanlego** [jgm/pandoc-citeproc#439]
Every internet search points back to #330 as to why accessed does not work with bib files.

# Workaround
if you want to have the accessed CSL field populated for websites use 
```bib
@online{some-key,
	title = {Awesome Title},
	url = {https://www.my.url/},
	urldate = {1970-01-01}
}
```

once converted to pdf it looks like this in ACM

```
[1] Awesome Title. Retrieved January 01, 1970 from https://www.my.url/
```

# Possible Fix
I haven't looked at it thoroughly but adding support to the accessed keyword looks it should be as easy as adding another line to support it here shouldn't it?
https://github.com/jgm/pandoc-citeproc/blob/d7eb5fd15980ba40d7bffd6d2f031a229881668f/src/Text/CSL/Input/Bibtex.hs#L1502

```
 accessed' <- getDates "accessed" <|> getOldDates "url" <|> return [] 
```

this way something like this would work

https://github.com/citation-style-language/styles/blob/059ea335d3f05c4d1417648b00b8c19de98fd7bb/acm-sig-proceedings.csl#L136-L145
```
        <else-if type="webpage">
          <group delimiter=". ">
            <text variable="URL" font-style="italic"/>
            <date variable="accessed" prefix="Accessed: ">
              <date-part name="year" suffix="-"/>
              <date-part name="month" form="numeric-leading-zeros" suffix="-"/>
              <date-part name="day" form="numeric-leading-zeros"/>
            </date>
          </group>
        </else-if>
```

**Comment by jgm** [comment]
Sure, we could do this, but it would mean creating our own Frankenstein version of bibtex format, since bibtex/biblatex don't recognize an `accessed` key.  I don't want to do that.  We try to support *valid* bibtex/biblatex, and that isn't a format whose specification we control.

**Comment by jeanlego** [comment]
thank you!
I will close this then :)

as a side note, my google-fu seems to not return anything in terms of documentation for what is valid bibtex/biblatex. 
I was under the impression that bibtex/biblatex only described the format in terms of 
```
@type{lookup-key,
    key = { value }
    ....
```

but that an `.sty` was responsible for describing the valid keys for each type.

**Comment by jgm** [comment]
See sec 2.1 of biblatex manual.
