### ISSUE TITLE
Beamer Bibliography on New Slide

### ISSUE THREAD

**Issue by HackerWithoutACause** [jgm/pandoc-citeproc#441]
Hello, I want my bibliography to be on separate slide. I have tried modify the template for the environment`cslreferences` with `\begin{frame}{...}` and `\end{frame}` but this won't work because `cslreferences` surround by the auto-generated frames. If there is any fix I would like to know.

**Comment by jgm** [comment]
Try using an explicit fenced div with id `refs` to place the bibliography.  If the bibilography header is > slide level, it won't cause a frame to be created.

**Comment by HackerWithoutACause** [comment]
I am sorry but I am not using html, I am using Markdown.

**Comment by jgm** [comment]
Yes, I know. pandoc's markdown has a syntax for fenced divs -- see the documentation for pandoc and for pandoc-citeproc.

**Comment by HackerWithoutACause** [comment]
Thank you this resolves my issue.
