### ISSUE TITLE
Disambiguation: setting for `disambiguate-add-names` is not followed

### ISSUE THREAD

**Issue by kaarelmand** [jgm/pandoc-citeproc#443]
Citation styles that have not been configured to use `disambiguate-add-names`, still do so (even if the setting is explicitly set to `"false"` in the `citation` header). This is against the citation style language specifications ([link to relevant bit](http://docs.citationstyles.org/en/1.0.1/specification.html#disambiguation)). Or maybe the problem is something with `disambiguate-add-year-suffix`? I'm using Pandoc version 2.9.2 and pandoc-citeproc version 0.17.

**Example**

`test.bib`:
```
@article{partin_2013_LargescalefluctuationsPrecambrian,
  title = {Large-Scale Fluctuations in {{Precambrian}} Atmospheric and Oceanic Oxygen Levels from the Record of {{U}} in Shales},
  author = {Partin, Camille A. and Bekker, A. and Planavsky, N. J. and Scott, C. T. and Gill, B. C. and Li, C. and Podkovyrov, V. and Maslov, A. and Konhauser, K. O. and Lalonde, S. V. and Love, G. D. and Poulton, S. W. and Lyons, T. W.},
  date = {2013-05},
  journaltitle = {Earth and Planetary Science Letters},
  volume = {369–370},
  pages = {284--293},
  doi = {10.1016/j.epsl.2013.03.031},
}

@article{partin_2013_Uraniumironformations,
  title = {Uranium in Iron Formations and the Rise of Atmospheric Oxygen},
  author = {Partin, Camille A. and Lalonde, S. V. and Planavsky, N. J. and Bekker, A. and Rouxel, O. J. and Lyons, T. W. and Konhauser, K. O.},
  date = {2013-12-20},
  journaltitle = {Chemical Geology},
  volume = {362},
  pages = {82--90},
  doi = {10.1016/j.chemgeo.2013.09.005},
  series = {Special {{Issue}} Dedicated to {{H}}.{{D}}. {{Holland}}: {{Evolution}} of the Atmosphere and Ocean through Time}
}
```

`test.md`:
```
---
csl: elsevier-harvard.csl
bibliography: test.bib
...

Test inline citation:
[@partin_2013_LargescalefluctuationsPrecambrian; @partin_2013_Uraniumironformations].
```

The .csl file in use is `elsevier-harvard.csl` from [here](https://github.com/citation-style-language/styles/blob/master/elsevier-harvard.csl). It contains the following line:
```
<citation et-al-min="3" et-al-use-first="1" disambiguate-add-givenname="true" disambiguate-add-year-suffix="true" collapse="year" cite-group-delimiter=", ">
```
(The same behaviour occurs when `disambiguate-add-names="false"` is added to the above line.)

I called `pandoc -o test.pdf --filter pandoc-citeproc test.md`.

**Actual result:**

Citation is formatted as `(Partin, Bekker, et al., 2013; Partin, Lalonde, et al., 2013)`.

**Expected result:**

Citation formatted as `(Partin et al., 2013a, 2013b)`. This happens, for example, when using the same .csl file in the same inline citation in Zotero/Libreoffice.

**Comment by dagdrommer** [comment]
Just the same problem here. @kaarelmand did you find a workaround?

...I would love to see a fix. 👍

**Comment by kaarelmand** [comment]
Unfortunately, nothing short of manually changing the output. Which I have to do each time I send a manuscript off to my supervisors or collaborators, since my field is firmly MS Office territory. Been thinking of learning Haskell just to try to eventually fix this...

**Comment by denismaier** [comment]
@dagdrommer @kaarelmand John has been working on a new citeproc that will eventually replace pandoc-citeproc. Maybe it works there correctly? @jgm ? You can already try it out if you use a pandoc nightly.

**Comment by kaarelmand** [comment]
Wow, that's good news!

I've compiled the development version of pandoc, but for some reason I cannot figure out how to get it to render the in-line citations. I understand `--filter pandoc-citeproc` no longer works.

**Comment by denismaier** [comment]
Use -citeproc instead

**Comment by kaarelmand** [comment]
Perfect, it works with `--citeproc`! This saves me so much work, thanks!

**Comment by kaarelmand** [comment]
It seems that since Pandoc 2.11 was released with the new `citeproc`, this bug is no longer relevant as a Pandoc user. Should I close it or leave it open, since the issue still exists in the now-superseded `pandoc-citeproc`?

**Comment by jgm** [comment]
It doesn't much matter, I guess, since I won't be maintaining this project any more. Some people have been closing issues, even though that's a bit misleading since this particular program still has the issues.
