### ISSUE TITLE
Role text missing when when editor and translator are identical

### ISSUE THREAD

**Issue by travelingancientphilosopher** [jgm/pandoc-citeproc#444]
Hi there, I've tried this with a couple different CSLs (Chicago 16th/17th ed's.)---if I have the editor/translator the same for a work, only the name shows up, but no role is mentioned (e.g. 'Edited and translated by ...').

E.g. with one entry (in Biblatex):

```
@book{Damascius2008,
  title = {Commentaire Sur Le {{Philèbe}} de {{Platon}}},
  author = {{Damascius}},
  editor = {Van Riel, Gerd},
  date = {2008},
  publisher = {{Les Belles Lettres}},
  location = {{Paris}},
  keywords = {\#nosource,Primary Source},
  translator = {Van Riel, Gerd}
}
```

Current result:
```
Damascius. 2008. Commentaire Sur Le Philèbe de Platon. Gerd Van Riel. Paris: Les Belles Lettres.
```

Expected result:
```
Damascius. 2008. Commentaire Sur Le Philèbe de Platon. Edited and translated by Gerd Van Riel. Paris: Les Belles Lettres.
```

If I change either one of the translator/editor lines, then the separate 'edited by'/'translated by' results show as expected.

**Comment by denismaier** [comment]
Looks like there's a bug with `editortranslator` handling. Have you tried with the same data in Zotero?

**Comment by jgm** [comment]
I'm sure this is a pandoc-citeproc bug.  I've tried a bit to pin this down but no luck yet.

**Comment by travelingancientphilosopher** [comment]
@denismaier:

> Looks like there's a bug with `editortranslator` handling. Have you tried with the same data in Zotero?

I did (in Zotero), and it comes out as expected:

```
Damascius. 2008. Commentaire Sur Le Philèbe de Platon. Edited and translated by Gerd Van Riel. Paris: Les Belles Lettres.
```

I fiddled around with a couple CSL files and tried pandoc-citeproc, but the same thing still resulted.
