### ISSUE TITLE
Year with suffix 

### ISSUE THREAD

**Issue by microniko** [jgm/pandoc-citeproc#446]
Hi,

I have a problem if I add 2 references of the same source without another source both : the year of the source has a letter suffix. 

For example (extract from my markdown document) :

```
D'un point de vue […] [@bartheAnalyseActiviteTravail2004].

Aussi, […] risque d'accident au cours de la nuit de travail [@bartheAnalyseActiviteTravail2004].
```

> D’un point de vue [. . . ] (Barthe, Quéinnec, et Verdier, 2004b).
> Aussi, [. . . ] risque d’accident au cours de la nuit de travail (Ibid.).

In my bibliography, these authors has publish only one publication in 2004.

And, if any source is between there is no suffix :
```
D'un point de vue […] [@bartheAnalyseActiviteTravail2004].

[@dejoursFacteurHumain2014]

Aussi, […] risque d'accident au cours de la nuit de travail [@bartheAnalyseActiviteTravail2004].
```

> D’un point de vue [. . . ] (Barthe, Quéinnec, et Verdier, 2004).
> (Dejours, 2014)
> Aussi, [. . . ] risque d’accident au cours de la nuit de travail (Barthe, Quéinnec, et Verdier, op.
cit.).

Is it a normal behavior ?

Thanks !

_pandoc 2.8.0.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
pandoc-citeproc : 0.14.3.1-4+b3
OS : Debian GNU/Linux_

**Comment by jgm** [comment]
That's very strange. Can you give full information for reproducing this?  Full bibliography entry, CSL used, command line used...

**Comment by microniko** [comment]
Hello,

I have created an archive with examples files (my original document is too big ;-))
[test.zip](https://github.com/jgm/pandoc-citeproc/files/4588949/test.zip). You can find [the CSL file here](https://framagit.org/microniko/csl/-/blob/master/ifcs-et-iae-nantes-NT.csl).

PDF files were produced by these commands :

```
$ pandoc test.md -o test.pdf --filter pandoc-citeproc
$ pandoc test_ko.md -o test_ko.pdf --filter pandoc-citeproc
```

I'm afraid this this problem will not easy to reproduce.

I hope it will be usefull.

**Comment by microniko** [comment]
Hi.
I think I have solved a part of the problem.
When I change the order of `<citation>` items in CSL file (you can see the [last commit](https://framagit.org/microniko/csl/-/commit/0d61465aefa44c7d3032e08ffe4c1fd73a5c2a17)), there is no suffix near the year anymore.
Do you have an idea why the `<citation>` items order affects *pandoc-citeproc* ?

PS : I solved the problem for the test.zip but not for my main document there are still 2 bugs but I should find a solution by tinkering in the text.

**Comment by microniko** [comment]
Well,
Finally, the order of *ibid.*, *op. cit*… was not correct with the new CSL file :\
I think there is a problem with the disambiguation of the year, so I set `disambiguate-add-year-suffix` to `false` to wait for another solution.
I don't know if the problem is comes from  *pandoc-citeproc* or with the CSL file.

**Comment by denismaier** [comment]
What happens when you don't specify a special csl style? What's the result with chicago-author-date?

**Comment by microniko** [comment]
It's OK with `chicago-author-date.csl` but this style doesn't have any complex citation with *Ibid.*, *Op. cit.*…

**Comment by microniko** [comment]
Is this bug is a duplicate of #53 ?

**Comment by denismaier** [comment]
Ok, as per @adam3smith, this seems to be a bug in pandoc-citeproc. Ibid. should have no effect on disambiguation.

**Comment by microniko** [comment]
Ok @denismaier, I hope it can be fixed.
