### ISSUE TITLE
Support field in biblatex entries to overwrite citation formatting

### ISSUE THREAD

**Issue by rriemann-eu** [jgm/pandoc-citeproc#455]
Dear all,

I am confronted with issues due to weak intercomperability between special-purpose biblatex packages ([oscola](http://mirrors.ctan.org/macros/latex/contrib/biblatex-contrib/oscola/oscola.pdf) and the CSL oscola. I mentioned this problem previously [here](https://github.com/jgm/pandoc-citeproc/issues/435#issuecomment-647360671) in issue #435 .

I think one solution would be to have pandoc-citeproc look in the biblatex bibliography for a special field like `cite_overwrite = {citation \textit{here}}` and use this one instead of the output from the CSL algorithm. Of course, this would prevent switching easy citation styles, but at least I could use the same bibliography file for biblatex and pandoc-citeproc.

Example of citations that I cannot produce with pandoc-citeproc from biblatex bibliography files:

![image](https://user-images.githubusercontent.com/55188356/85271794-8c893200-b47b-11ea-9953-81d4023bdfba.png)

**Comment by njbart** [comment]
My guess is that the biblatex-CSL crossover you’re proposing isn’t really on the cards.

However, it does seem there might be room for improvement concerning the treatment of legal material in pandoc-citeproc.

Currently, `pandoc-citeproc -y file.bib` converts your example from https://github.com/jgm/pandoc-citeproc/issues/435 to the following (CSL YAML for better readability, but CSL JSON fields should be identical):

```
---
references:
- id: gdpr
  type: legislation
  issued:
  - year: 2016
    month: 5
    day: 4
  accessed:
  - year: 2018
    month: 1
    day: 7
  title: <span class="nocase">Regulation (EU) 2016/679 of the European Parliament
    and of the Council of 27 April 2016 on the Protection of Natural Persons with
    Regard to the Processing of Personal Data and on the Free Movement of Such Data,
    and Repealing Directive 95/46/EC (General Data Protection Regulation)</span>
  title-short: GDPR
  container-title: OJ
  collection-title: L
  page: '1'
  genre: regulation
  keyword: eu
  number: 2016/119
  URL: http://data.europa.eu/eli/reg/2016/679/oj/eng
  language: en-US

- id: ecj:c-311/18-agop
  type: legal_case
  issued:
  - year: 2018
  title: <span class="nocase">Data Protection Commissioner v Facebook Ireland Limited,
    Maximillian Schrems</span>
  collection-title: C
  publisher: ECJ
  page: '21'
  volume: '249'
  note: Opinion of AG Saugmandsgaard Øe
  keyword: eu
  number: C-311/18
...
```

If you could indicate what CSL field content does produce satisfactory results with pandoc-citeproc using oscola.csl, I am sure we could have a closer look at how to improve the biblatex -> CSL conversion process.

BTW, wrapping entire title fields in braces is counterproductive. Only individual terms/phrases such as names should be protected in this way.
