### ISSUE TITLE
Square brackets in title data parsed as links

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc-citeproc#457]
Motivated by [this dicussion](https://discourse.citationstyles.org/t/sub-field-parsing/550/26) on in-field markup in CSL, I checked whether square brackets in title data are indeed parsed as links by pandoc – it turns out they are, see output. Note that even the title in the `references` part of the YAML header is modified.

I feel this is a bug: Bibliographic data is one area that should not be modified in such a way at all.

```
pandoc -s -F pandoc-citeproc -t markdown-citations << EOT

# A section title

Link to [a section title].

Foo [@item1].

---
references:
- id: item1
  type: book
  title: The title contains a string that matches [a section title]
  issued:
  - year: 2014
reference-section-title: References
...
EOT
```

Output:

```
---
reference-section-title: References
references:
- id: item1
  issued:
  - year: 2014
  title: 'The title contains a string that matches [a section
    title](#a-section-title)'
  type: book
---

A section title
===============

Link to [a section title](#a-section-title).

Foo (*The Title Contains a String That Matches [a Section
Title](#a-section-title)* 2014).

References {#bibliography .unnumbered}
==========

::: {#refs .references .hanging-indent}
::: {#ref-item1}
*The Title Contains a String That Matches [a Section
Title](#a-section-title)*. 2014.
:::
:::
```

**Comment by jgm** [comment]
It's not a bug.  Pandoc has a consistent policy of parsing all YAML metadata as Markdown.  The references are in YAML metadata.  By the time pandoc-citeproc sees this metadata, it has already been parsed as a link.

**Comment by njbart** [comment]
OK, it’s not a huge deal since in most workflows I’m aware of, my own ones included, biblio data are not provided in YAML headers, but rather in separate files – where the problem described above does not arise. Still, I feel biblio data should be exempted/protected from interference in *all* contexts, without any exception.

Thanks for the clarification nonetheless.

**Comment by jgm** [comment]
The question is, what is "interference"?
Pandoc (and pandoc-citeproc) do allow formatting inside titles, beyond the limited formatting CSL JSON gives you.  That allows us to handle math well, for example.  Links are just another example.

If you were concerned about converting a bibliography format to pandoc front matter, and a literal bracketed text got converted to a pandoc link, that would be another question.  But I gather it's not about that.
