### ISSUE TITLE
Type ENCYC not recognised in conversion from RIS to YAML

### ISSUE THREAD

**Issue by bpj** [jgm/pandoc-citeproc#459]
I need to make a reference to a Wikipedia page, but when I convert the RIS generated by Zotero to YAML with pandoc-citeproc I get this error:

````
$ pandoc-citeproc -f RIS -y upa.ris >upa.yaml
hs-bibutils: Did not recognize type 'ENCYC' of refnum 1 ().
	Defaulting to STD.
````

The YAML has this, not quite what I would expect:

````yaml
- id: ref1
  type: no-type
````

````
$ pandoc-citeproc --version
pandoc-citeproc 0.17
````

Relevant files attached.
[ris-type-encyc.zip](https://github.com/jgm/pandoc-citeproc/files/4933531/ris-type-encyc.zip)

**Comment by jgm** [comment]
You can submit a report to hs-bibutils, or better to bibutils (it's just a wrapper around a C library).
Nothing else we can do here.
