### ISSUE TITLE
How to use NBIB as bibliography file

### ISSUE THREAD

**Issue by chrisothal** [jgm/pandoc-citeproc#460]
I noticed in the manual that pandoc-citeproc supports using .nbib files as bibliography files. How can I use a citation in my document with a reference stored in an .nbib file? Do I have to add a separate ID field?

Edit: After running `pandoc-citeproc -y -f nbib<reference.nbib` I see it takes the first author's last name and the year as the ID.

However, this method fails when I have two articles with the same first author and year, but saved in two separate .nbib files using the command: `pandoc test.md -o test.pdf --bibliography=citation1.nbib --bibliography=citation2.nbib`. When I combine the two articles into one citation file, the references are differentiated from each other: `pandoc test.md -o test.pdf --bibliography=citation3.nbib`

test.md
```
Test citation 1 [@Last2020].

Test citation 1 [@Last2020a].

Test citation 2 [@Last2020b].
```

citation1.nbib
```
PMID- 1
DP  - 2020 Jul 25
TI  - Title
FAU - Last, F M
AU  - Last FM
FAU - Secondlast, F M
AU  - Secondlast FM
PT  - Journal Article
JT  - Journal name
```

citation2.nbib
```
PMID- 2
DP  - 2020 Jul 25
TI  - Title
FAU - Last, F M
AU  - Last FM
FAU - Thirdlast, F M
AU  - Thirdlast FM
PT  - Journal Article
JT  - Journal name
```

citation3.nbib
```
PMID- 1
DP  - 2020 Jul 25
TI  - Title
FAU - Last, F M
AU  - Last FM
FAU - Secondlast, F M
AU  - Secondlast FM
PT  - Journal Article
JT  - Journal name

PMID- 2
DP  - 2020 Jul 25
TI  - Title
FAU - Last, F M
AU  - Last FM
FAU - Thirdlast, F M
AU  - Thirdlast FM
PT  - Journal Article
JT  - Journal name
```

**Comment by jgm** [comment]
Sorry, the construction of the id is all done by the bibutils library which we simply depend on.
And note, we may phase out support for this, since I'd prefer to avoid depending on a C library.
I'd recommend using bibutils or something else to convert your nbib to something pandoc-citeproc likes more.

**Comment by chrisothal** [comment]
Got it! I could include a line that concatenates all nbib files together into one file before running pandoc-citeproc and that way bibutils can properly handle the ID correctly.
