### ISSUE TITLE
nocite option in defaults.yml is ignored

### ISSUE THREAD

**Issue by rriemann** [jgm/pandoc-citeproc#461]
Dear all,

I tried to move the meta data field from the frontmatter `nocite: '@*'` to the [default file](https://pandoc.org/MANUAL.html#default-files) that pandoc introduced recently.

But when I put it under metadata or variables, but pandoc-citeproc does not pick it up in HTML output.

example `default.yaml` file:

```
variables:
  nocite: '@*'
metadata:
  nocite: '@*'
```

I'm on pandoc 2.9.2.1 (Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2).

Best,  
Robert

**Comment by jgm** [comment]
The reason for this is subtle, but it is explained in the docs if you dig.
Metadata in defaults files is processed differently than metadata in markdown files.
In markdown files, metadata is parsed as markdown.
In defaults files, it is parsed as  plain text (after all, the input format might be anything).
`@*` parsed as markdown gives you a wildcard citation.  But as plain text it isn't anything but the letters `@*`.
