### ISSUE TITLE
Need for producing a .tex file embedding the standard \cite latex citation calls

### ISSUE THREAD

**Issue by manumart** [jgm/pandoc-citeproc#467]
A scientific journal asks me to produce a latex .tex file along with a .bib file, with citations in text the usual "latex" way. Hence I would need citeproc to simply replace the @jons_smith_1995 like citations with standard latex call (\cite{jons_smith_1995} for instance), and stop before inserting in the text the "final" citation (Jons et al. 1995). Is there a way to do this with pandoc-citeproc?

Thank you in advance,    Manuel

**Comment by denismaier** [comment]
Sure, just don't use pandoc-citeproc. The `--biblatex` or `--natbib` parameters should do what you need: https://pandoc.org/MANUAL.html#citation-rendering

(By the way, you should switch to the new citeproc anyway; use `--citeproc` instead of `-F pandoc-citeproc`)
