### ISSUE TITLE
Formatting of Hispanic names

### ISSUE THREAD

**Issue by davepwsmith** [jgm/pandoc-citeproc#50]
Sorry to raise another issue that I suspect will be a flaw of CSL or Biblatex rather than this library, but seems to be related to parsing of names with dropping/non-dropping particles. A biblatex bibliography entry for poet Carlos Drummond de Andrade which is such:

```
@article{citekeyblah,
  pages = {1},
  title = {{No meio do caminho}},
  url = {http://www.brasiliana.usp.br},
  volume = {{1}},
  number = {3},
  journaltitle = {{Revista de Antropofagia}},
  author = {Drummond de Andrade, Carlos},
  urldate = {2014-05-19},
  date = {1928-07},
  year = {1928},
  file = {revista-de-antropofagia_1928_3.pdf:/Users/davidsmith/Zotero Library/storage/7ESFHIJE/revista-de-antropofagia_1928_3.pdf:application/pdf}
}
```

Should ideally display as:
Drummond de Andrade, Carlos (1928), “No meio do caminho”, Revista de Antropofagia, vol. 1, no. 3, pp. 1, obtido de http://www.brasiliana.usp.br

but instead displays as:
Andrade, Carlos Drummond de (1928), “No meio do caminho”, Revista de Antropofagia, vol. 1, no. 3, pp. 1, obtido de http://www.brasiliana.usp.br

Now I know that I can wrap the family names in braces thus:
`author = {{Drummond de Andrade}, Carlos},`

and it will have the desired effect, but this seems to be a fairly poor solution for something that is not only a common, but practically a universal way of formatting names from hispanic/lusophone countries, especially since the biblatex format at least nominally supports comma separation of first/given names to specify this.

I'm afraid my knowledge of programming, and particularly haskell is pretty limited, but there seems to be a bit of bibtex.hs which takes the comma-separated strings and turns them into a single string. Perhaps a better behaviour would be to keep them separate, and so be able to distinguish between family names and given names as groups of words?

**Comment by gracile-fr** [comment]
I'm a bit surprised by the example (Carlos Drummond de Andrade). I thought that, for Portuguese and Lusophone names, only the last surname had to be used for sorting, bibliography entries, etc.
http://www.loc.gov/books/?q=carlos+drummond+de+andrade&all=true
http://www.idref.fr/028032470

**Comment by nickbart1980** [comment]
I don’t know much about Portuguese names but I’ll note that his Portuguese Wikipedia entry (https://pt.wikipedia.org/wiki/Carlos_Drummond_de_Andrade, as well as his English and French Wikipedia entries) use “Drummond” as a short form throughout. 

So, though we can’t shorten “Drummond de Andrade” to “Drummond” for in-text citations within the current CSL framework – the CSL schema would have to introduce no less an additional `dropping-suffix` name part for that, I guess –, my impression is that “Drummond de Andrade” is probably acceptable, and certainly better than “Andrade” in this case.

Still, if any native speakers of Portuguese could comment, this would certainly be helpful.

**Comment by davepwsmith** [comment]
Not a native, but I stand by my original post! This was perhaps a poor choice of example -- many bibliographies would list as "Andrade, CD de" or something similar, although there is no hard and fast Rule. Portuguese names are a bit of a bibliographical nightmare, and people frequently choose which of their (many) surnames that they wish to use on an ad-hoc basis -- this is why many alphabetized lists of names in Portuguese are organized by given names first, followed by whatever surnames have been provided. Added to this is the fact that many surnames and given names are incredibly common -- much more so than in English. The Wikipedia article you cite is one example of how people get around the problem -- Drummond, as the least common of his names, is how he would probably have referred to himself and been referred to by his contemporaries. However, the following list, which I put on the bibtex thread has at least one example which would cause the parser as it was to choke incorrectly (the third one):

{Carlos} {Drummond de Andrade}
{João Cabral} de {Melo Neto}
{María del Carmen} {Pucci}
{João Guimarães} {Rosa}
{Haroldo} de {Campos}

In spite of all of this, I would say that the main point of my argument is that if I wish to alphatize my bibliography in x manner, and I have clearly indicated this with commas in the biblatex file, then my parser probably shouldn't try to second guess me! 

Anyhow, this bug has been satisfactorily squashed, so I don't really see what the fuss is about.

**Comment by gracile-fr** [comment]
No "fuss" at all. And I'm not willing to change anything. I was just curious of the example chosen to illustrate "Hispanic names" and since I assume that you've <a href="http://www.davidsmith.name/">obviously more knowledge</a> than me on this subject, I posted here.
Anyway, I think that CSL should be able to handle that in the future (i.e. to let the user choose how to parse these names) but that's not the right place to discuss it.
