### ISSUE TITLE
Enable field-level linking in citations

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#52]
Would it be possible to implement Zotero's option that suppresses the URL on a citation that also includes page numbers? (It could be nice sometimes to be able to suppress the DOI as well, since many publishers that otherwise follow a particular style don't give either the DOI or the URL for sources that originally appeared in print.)

**Comment by spl** [comment]
I'm also looking into a way of linking the title of a citation to a summary page (e.g. with the abstract) for the reference. As far as I understand the thread above, I believe a solution to this issue would solve my problem. I believe it's a pretty common thing to do if you're turning a bibliography into a webpage. So, consider me a :+1: here.

**Comment by and3k** [comment]
FYI, relevant discussion on CSL and "Suppress URL for items with page numbers": https://github.com/citation-style-language/styles/pull/1594
