### ISSUE TITLE
Generating internal links with citeproc

### ISSUE THREAD

**Issue by mclearc** [jgm/pandoc-citeproc#56]
A feature request: generate bibliographies using pandoc-citeproc (going from .md to .pdf via latex/xelatex) that provide internal links like the hyperref and backref options do in the biblatex package, all without having to generate a .tex file first and creating the PDF from that.

**Comment by jgm** [comment]
This is done (as of 3944dce01725ebe5f007ac2a7d2bb74b472b1b8e).
