### ISSUE TITLE
Status of using citeproc-hs

### ISSUE THREAD

**Issue by nomeata** [jgm/pandoc-citeproc#6]
Hi,

I noticed that gitit now depends on pandoc-citeproc, which contains a copy of citeproc-hs. In Debian, such code copies are usually not acceptable.

What is the reason for the code copy, and is there a tickets tracking its proper solution?

Thanks,
Joachim

**Comment by jgm** [comment]
I have not heard from Andrea for a year and a half.  citeproc-hs seems a dead project, so I think we can close this.
