### ISSUE TITLE
biblatex "bookinbook" -> CSL "chapter" (not "book")

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#62]
biblatex "bookinbook" entries are currently mapped to CSL "book". (This doesn't work well since CSL style files do not format "book" items with both title and container-title correctly.)

"bookinbook" should be mapped to CSL "chapter" instead. 

The problem, then, is that the title will be upright, and wrapped in quotes, but it should appear in italics, and without quotes. Adding italics should not be a problem, but what could we do to suppress quotes a CSL style file would normally add? I'm not aware of anything in the CSL specs that would allow such a thing. If we don't mind inventing something new, we could introduce some kind of inline markup, such as `<span class="noquotes">`, maybe?

**Comment by jgm** [comment]
I don't see any good way to deal with the quotes issue.  Since this seems to be a general CSL issue, I suggest you bring it up on the CSL list, and see how they would handle bookinbook.
