### ISSUE TITLE
Literal issued date not interpreted.

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#65]
Zotero still cannot manage date ranges (which is another story); the common [workaround](https://forums.zotero.org/discussion/6111/2/better-date-field/#Item_14) is to use an underscore instead of a dash. Pandoc-citeproc, however, does not pick up the date at all from the resulting JSON:

``` json
{
    "ISBN": "3406493556",
    "author": [
        {
            "family": "Stotz",
            "given": "Peter"
        }
    ],
    "call-number": "PA25 PA2616 .H24 Abt. 2, T. 5, Bd. 2, etc",
    "collection-number": "2.5",
    "collection-title": "Handbuch der Altertumswissenschaft",
    "event-place": "Munich",
    "id": "stotz:1996handbuch",
    "issued": {
        "literal": "1996_2004"
    },
    "language": "German",
    "number-of-volumes": "5",
    "publisher": "Beck",
    "publisher-place": "Munich",
    "shortTitle": "Handbuch",
    "source": "Library of Congress ISBN",
    "title": "Handbuch zur lateinischen Sprache des Mittelalters",
    "type": "book"
}
```

(It would, of course, be even better if the underscore could be automatically changed to a dash, but that's probably asking too much given that this is non-standard.)

**Comment by jgm** [comment]
@adunning @njbart I just wanted to check, for my new citeproc engine: is it still necessary to support this old workaround, or can we just leave `literal` dates as they are?

**Comment by njbart** [comment]
Zotero itself, to the best of my knowledge, still cannot properly handle date ranges. (citeproc-js does, but only if dates are provided in Zotero’s Extra field, using the so-called cheater syntax.) However, I guess those who do need date ranges almost invariably install the Better BibTeX plugin, which correctly exports date ranges to Bib(la)TeX, CSL JSON and CSL YAML. Hence I think the new citeproc wouldn’t have to bother any longer with the workaround discussed in this thread.

**Comment by denismaier** [comment]
FWIW, CSL 1.1 will bring a major overhaul to dates. Among other things, the EDTF format will be supported, and there will be proper support for date ranges.

**Comment by njbart** [comment]
@denismaier - Arguably, CSL JSON and CSL YAML, as well as (at least) citeproc-js and pandoc-citeproc already do offer proper support for date ranges. (I see switching to EDTF as a huge improvement, though.) It’s just the regrettable limitations of Zotero (when used without Better BibTeX) that used to require using workarounds such as the ones discussed here.

**Comment by denismaier** [comment]
> Arguably, CSL JSON and CSL YAML, as well as (at least) citeproc-js and pandoc-citeproc already do offer proper support for date ranges. (I see switching to EDTF as a huge improvement, though.)

You are right of course. Date range support is there. "Proper" should have been "better", "easier" or so.
While the old `date-parts` structure is still valid, you can now also use EDTF which should simplify things a bit.
