### ISSUE TITLE
Labels do not fall back from verb-short to verb

### ISSUE THREAD

**Issue by adunning** [jgm/pandoc-citeproc#72]
One can normally cite a book review using chicago-author-date.csl (and other styles that support it) by adding a reviewed author. This is mostly fine with pandoc-citeproc, but the word 'by' following the title is omitted, unlike citeproc-js:

```
pandoc -F pandoc-citeproc -t plain << EOT

---
references:
- ISSN: '0038-7134'
  DOI: 10.1017/S0038713400016407
  note: "ArticleType: book-review / Full publication date: Jul., 2006 / Copyright
    © 2006 Medieval Academy of America"
  volume: '81'
  URL: http://www.jstor.org/stable/20463899
  reviewed-author:
  - family: Boutry
    given: Monique
  page: '905-906'
  first-reference-note-number: 1
  container-title: Speculum
  language: Latin
  author:
  - family: Colish
    given: Marcia L.
  source: JSTOR
  id: colish:2006petri
  accessed:
    date-parts:
    - - 2013
      - 10
      - 18
  container-title-short: Speculum
  issued:
    date-parts:
    - - 2006
      - 7
  title: 'Petri Cantoris Parisiensis Verbum adbreviatum: Textus conflatus'
  type: article-journal
  issue: '3'
---

@colish:2006petri

EOT
```

## Expected Output

Colish (2006)

Colish, Marcia L. 2006. Review of _Petri Cantoris Parisiensis Verbum
adbreviatum: Textus conflatus_, by Monique Boutry. _Speculum_ 81 (3):
905–6. doi:10.1017/S0038713400016407.

## Actual Output

Colish (2006)

Colish, Marcia L. 2006. Review of _Petri Cantoris Parisiensis Verbum
adbreviatum: Textus conflatus_, Monique Boutry. _Speculum_ 81 (3):
905–6. doi:10.1017/S0038713400016407.

**Comment by nickbart1980** [comment]
Update: I checked again, and adding `<term name="reviewed-author" form="verb-short">by</term>` to *either* a `locales-en-US.xml` in pandoc-citeproc’s search path (currently ~/Library/Haskell/share/ghc-7.8.3-x86_64/pandoc-citeproc-0.7/locales/locales-en-US.xml) *or* the CSL style file being used is indeed a workaround that renders the example from the original post as expected. 
So it’s just the missing fallback from verb-short to verb that would need to be fixed in pandoc-citeproc.

**Comment by adunning** [comment]
The CSL people confirm @nickbart1980's assessment (and point to the same section of the spec): if `verb-short` does not exist in the locale file, citeproc should use the term marked as `verb` instead.

**Comment by adunning** [comment]
Brilliant; thank you!
