### ISSUE TITLE
Ibid. ambiguity

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc-citeproc#79]
When using a citation style that supports "Ibid." (I am using "chicago-fullnote-bibliography") I have noticed that pandoc-citeproc produces ambiguous or wrong results. Consider this example:

Sentence 1. [@a]
Sentence 2.^[Many examples can be found in the Babylonian Talmud.]
Sentence 3. [@a]

After Sentence 3 the source is rendered as "Ibid.". It should print the normal citation instead since after sentence 2 we have another footnote. (A similar example in LibreOffice with Zotero works just fine. Is it possible that pandoc-citeproc does not take "near-note" into account?)

The same also applies for author-date styles that use "Ibid." if we enter a manual citation from a classical source like the bible between two identical sources:

Sentence [@a]. Sentence (see Exodus 1:1). Sentence 3 [@a].
==> Sentence (a). Sentence (see Exodus 1:1). Sentence 3 (ibid.).

In BibLaTeX there is a command "\mancite" that prevents the wrong "ibid.". Perhaps it might be feasible to implement something like this in pandoc-citeproc?

**Comment by davepwsmith** [comment]
I would guess that this is almost certainly related to #53 and #53

**Comment by denismaier** [comment]
Just in case, someone has the same problem. [This filter](https://github.com/denismaier/pandoc-lua-mancite) is not a official solution, but it helps a bit.
