### ISSUE TITLE
Looks like XML parse error, but based on location of CSL file

### ISSUE THREAD

**Issue by magthe** [jgm/pandoc-citeproc#81]
After upgrading to 0.5 I've observed a very strange issue.  Processing of several of my files resulted in an error like this:

```
pandoc -t latex --filter pandoc-citeproc --template template.latex --csl=style.csl -o lfs_system_utp.pdf lfs_system_utp_t.mkd
pandoc-citeproc: error while parsing the XML string
pandoc: Error running filter pandoc-citeproc
```

I simply stopped using the (slightly custom) CSL file I want to use and instead fell back on the default one that comes with pandoc-citeproc.  That worked, and was all right for the moment.

After a few days I saw a message on a Haskell-related mailing list for the Arch Linux distro regarding this.  That mail described a work-around: just replace the default CSL file with the one you want to use.  Indeed, that works:

```
cp style.csl /usr/share/x86_64-linux-ghc-7.8.3/pandoc-citeproc-0.5/chicago-author-date.csl
pandoc -t latex --filter pandoc-citeproc --template template.latex -o lfs_system_utp.pdf lfs_system_utp_t.mkd
```

Clearly there is something going on here that is really surprising to a mere user.

**Comment by nylki** [comment]
I still have this issue with pandoc-citeproc 0.5 on Fedora 22. Is there a fix for this situation? I suppose I'd have to build pandoc-citeproc myself to get the most recent version?

**Comment by ousia** [comment]
> I still have this issue with pandoc-citeproc 0.5 on Fedora 22. Is there a fix for this situation? I suppose I'd have to build pandoc-citeproc myself to get the most recent version or wait until fedora puts it into their repository?

@nylki, there is a copr repository with pandoc statically linked from Jens Petersen (https://copr.fedoraproject.org/coprs/petersen/pandoc/).

I have just asked him whether he could add the latest version from pandoc-citeproc.

**Comment by nylki** [comment]
@ousia thanks! have you got a response from Jens Peter?

**Comment by ousia** [comment]
@nylki, you have a subpackage at https://copr.fedoraproject.org/coprs/petersen/pandoc/ (only for Fedora 22 or newer).
