### ISSUE TITLE
Parse date ranges YYYY-MM-DD_YYYY-MM-DD

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#86]
Zotero still cannot export date ranges to CSL JSON, but a common workaround, using an underscore as as a (nonstandard) range separator, is supported by pandoc-citeproc now (see https://github.com/jgm/pandoc-citeproc/issues/65).

My suggestion is to support date ranges including months and days, too. Thus, pandoc-citeproc should parse literal dates matching the patterns `YYYY-MM_YYYY-MM` or `YYYY-MM-DD_YYYY-MM-DD` as date ranges.

In addition, I'd suggest that pandoc-citeproc should be able to parse the standard date range separators `/`(solidus, forward slash, used by biblatex) and `--` (double hyphen, listed in ISO 8601 as a possible alternative to a solidus), too.

**Comment by nickbart1980** [comment]
Update: Zotero currently neither exports date ranges of the pattern described above nor date fields with solidus or double hyphen as “literal” CSL JSON dates, so this won't work.

An additional issue I came across is open date ranges: Zotero exports these as expected, but pandoc does not parse them as an open range – it'd be great if it would.

```
   "issued": {
        "literal": "1996_"
    },
```

**Comment by jgm** [comment]
So, just to be clear, zotero supports `1996_2000` and `1996_` but not `1996-12-15_2000_01_30`?

**Comment by nickbart1980** [comment]
Right. `1996_2000` and `1996_` are exported as "literal" but `1996-12-15_2000-01-30` as

~~~
"issued": {
"date-parts": [
	[
		"1996",
		12,
		15
	]
],
"season": "2000-01-30"
~~~

It’s probably better to persuade zotero to export *every* date containing an underscore as "literal" (see my posts at https://forums.zotero.org/discussion/40880/export-date-range-yyyymmddyyyymmdd-as-literal-date/) rather than trying to parse *this* output ourselves.

**Comment by nickbart1980** [comment]
I checked again, and apparently Zotero exports only very few strings unchanged, and the only ones that look usable contain numbers and underscores only (no hyphens):
`1985_1986` (pandoc parses this already), `1985_02_1986_03`, and  `1985_02_19_1986_03_27`.
It would be a bit of a hack, but then again not much different or worse than the `1985_1986` we're parsing already. – Thoughts?

**Comment by nickbart1980** [comment]
Alternatively, it would help if pandoc-citeproc extracted CSL variables embedded in the CSL note variable (https://github.com/jgm/pandoc-citeproc/issues/94): It turns out that `{:issued: 2012-01-22/2012-02-23}` in Zotero's "Extra" field is exported as is – and citeproc-js can actually parse and render this date range correctly. So it seems implementing https://github.com/jgm/pandoc-citeproc/issues/94 would amount, at the same time, to the best solution for the date range issue that's currently possible, given the limitations of Zotero.

**Comment by nickbart1980** [comment]
https://github.com/ZotPlus/zotero-better-bibtex now does a fantastic job parsing [EDTF] dates and date ranges, both from Zotero’s “Date” field and from CSL variables embedded in Zotero’s “Extra” field (`{:label: value}` and newline-separated `label: value` formats). See https://github.com/ZotPlus/zotero-better-bibtex/issues/360.

It also handles years < 1 very well: Since CE/BCE has no year zero but [EDTF] (like ISO 8601) has, BBT correctly maps `0000-12-31` to CSL JSON `"issued":{"date-parts":[[-1,12,31]]}` which is then rendered as “31 December 1 BCE”.

Hence I’d say this issue here could be closed for now.

[EDTF]: http://www.loc.gov/standards/datetime/pre-submission.html
