### ISSUE TITLE
Feature request: Extract CSL variables embedded in the CSL note variable

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc-citeproc#94]
It would be helpful if pandoc-citeproc could extract CSL variables embedded in the CSL note variable in CSL JSON databases. 

Embedding CSL variables inside the CSL note variable is a technique that can be used with database managers such as Zotero when no GUI fields are available that map to desired valid CSL variables. 

This would be very helpful for using variables such as original-date, status, doi (unavailable in Zotero for books, book sections, reports) etc. in pandoc-citeproc when using Zotero as a database, e.g., via zotxt.

citeproc-js, used by Zotero, has implemented this at least since 2011 (http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#supplementary-fields).

The syntax for adding supplementary fields via the note variable is as follows:

`{:authority:Superior Court of California}{:section:A}{:original-date:1777}`

For pandoc-citeproc, I would suggest removing these constructs from the note variable after parsing it; this would allow the note variable to be used for its original purpose, too.

**Comment by nickbart1980** [comment]
Just noticed that ‘Preliminary steps towards parsing supplementary fields in "note"’ has been patching Bibtex.hs. But unless I'm mistaken, Bibtex.hs is parsing only bibtex and biblatex databases, right?
So, to avoid misunderstandings, my request is about CSL JSON databases, to be able to use, e.g., data from Zotero via zotxt.
I wouldn't think it makes sense to support supplementary *CSL* fields in *bibtex/biblatex* database "note" fields: First, practically all CSL variables in question here have working biblatex counterparts anyway; and second, much too confusing.

**Comment by adunning** [comment]
There's [more documentation on this](https://forums.zotero.org/discussion/47132/book-sections-have-dois-too/) on the Zotero forums. Implementing this would save a huge amount of time, since I'm running into an increasing number of chapters with DOIs, and Chicago wants them to be cited, while proper Zotero support for this seems no closer than it was when this issue was first reported in 2009.

**Comment by adunning** [comment]
There's now a workaround for this: the Better BibTeX plugin for Zotero has a 'Pandoc JSON' format as of version 1.1, and will parse the `note` field in the manner requested by @nickbart1980 (cf. ZotPlus/zotero-better-bibtex#260). Given this, is it still necessary to implement this in pandoc-citeproc?

**Comment by nickbart1980** [comment]
Yes it is, since not everyone uses Better BibTeX.

pandoc-citeproc needs this for proper parsing whenever a CSL JSON database exported by Zotero is used, e.g., with zotxt.
