### ISSUE TITLE
Problem parsing the "publisher" field from .bib file

### ISSUE THREAD

**Issue by scaramouche1** [jgm/pandoc-citeproc#96]
If a book has a publisher that has "and" in its name (e.g., "Simon and Schuster"), pandoc-citeproc will wrongly transform it as if it were person names (e.g., the references would read "Simon; Schuster").

This happens when processing .bib files but not when processing YAML files.  Zotero does not make this transformation when using the same style sheet (chicago-author-date).

**Comment by nickbart1980** [comment]
This is intentional and complies with the bibtex and biblatex specs. In your example, you need to wrap the `and` in curly braces, like `publisher = {Simon {and} Schuster}`. See the biblatex manual, http://ctan.mirrorcatalogs.com/macros/latex/exptl/biblatex/doc/biblatex.pdf, “2.3.4 Literal Lists”.

**Comment by scaramouche1** [comment]
Thanks for the reply.  I'll have to update my .bib files then.
